### ISSUE TITLE
Adding MapActivity

### ISSUE THREAD

**Issue by rogersala** [jfeinstein10/SlidingMenu#10]
Hi!

First of all, congrats for this project! It helps me a lot and the most important thing: very easy!

But now I have a little bit problem. I'm working with activities. When the users click a menu item, new activity starts. But now I'd like to add a MapActivity, do you know how can I do?

Thanks! I'm waiting for your response

**Comment by jfeinstein10** [comment]
Thanks a lot :)
The whole point is to make your life easier and I guess it has so far!

I just pushed a SlidingMapActivity. I don't have any projects set up with MapActivities, so pull it and let me know if it works.

**Comment by rogersala** [comment]
Hi,

I'm not using Sherlock's libraries. But I change your code to MapActivity and I'll be test. My problem now is: how can I add SlidingMenu using fragments in my mapActivity class?

**Comment by rogersala** [comment]
Hi again,

Finally I get it! What I've done is:

1.- Import in your project this library: https://github.com/petedoyle/android-support-v4-googlemaps
2.- Your class SlidingMapActivity extends FragmentActivity (in the step1 the jar file contains FragmentActivity = MapActivity
3.- My class Map extends SlidingMapActivity.

Thanks and congrats again! And thank for your quick response.

**Comment by jfeinstein10** [comment]
Awesome! That sounds like a great solution. I'll point anybody else with your problem here in the future. Thanks for figuring this out.
