### ISSUE TITLE
Don't work with custom view in ActionBarSherlock

### ISSUE THREAD

**Issue by RobertoArtiles** [jfeinstein10/SlidingMenu#100]
Hi.
I think I found a bug
This piece of code works wrong (doesn't show custom view):

``` java
ActionBar actionBar = getSupportActionBar();
actionBar.setDisplayShowCustomEnabled(true);
TextView customTitleText = (TextView) getLayoutInflater().inflate(R.layout.actionbar_title, null);
ActionBar.LayoutParams params = new ActionBar.LayoutParams(ActionBar.LayoutParams.MATCH_PARENT, ActionBar.LayoutParams.MATCH_PARENT, Gravity.CENTER);
actionBar.setCustomView(customTitleText, params);
/.../
customTitleText.setText("some text");
```

And in case of calling requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
it shows custom view only in duration of progress. Without requestWindowFuture() don't work at all.

Thanks,
Roberto.

**Comment by jfeinstein10** [comment]
Changing MATCH_PARENT to WRAP_CONTENT works

Edit:
Looks like it's something wrong with setting the width to MATCH_PARENT.

**Comment by RobertoArtiles** [comment]
But in this case a standard title (which setups with setTitle()) is visible

**Comment by jfeinstein10** [comment]
You can remove it with `actionBar.setDisplayShowTitleEnabled(false)`

**Comment by jfeinstein10** [comment]
Closing this because it isn't an issue with the library, but I can continue to help if you need it :smile:

**Comment by RobertoArtiles** [comment]
> Closing this because it isn't an issue with the library, but I can continue to help if you need it 

Thanks. It would be great. Because now it doesn't work with this piece of code =)

``` java
actionBar.setDisplayShowHomeEnabled(false);
actionBar.setDisplayHomeAsUpEnabled(true);
actionBar.setHomeButtonEnabled(true);
```

If add setDisplayShowTitleEnabled(false).
It doesn't show back arrow.

**Comment by jfeinstein10** [comment]
You need to have "home" showing in order to have "home as up"

**Comment by RobertoArtiles** [comment]
Well. Thank you very much Jeremy.
You was very kind helping me :)
Solved this issue by setting title as a string with one space (In this case back arrow shows even without home icon)
Dirty solution but what can I do with customer imagination.

**Comment by jfeinstein10** [comment]
You're very welcome :)
Not a bad solution. You may also be able to hide the title and set the home icon to null.
