### ISSUE TITLE
Opening the menu suggestion

### ISSUE THREAD

**Issue by scruffyfox** [jfeinstein10/SlidingMenu#105]
Hey,

Firstly, really great library! I want to achieve this in my app (I plan on looking at it myself, but if any of you guys have suggestions, im all ears) where if you are on the left most fragment, you should be able to open the slide menu from swiping left to right from anywhere on the page (almost like the menu was a hidden fragment in a pager) and for every other page, you must use the gesture (from the left edge) or the up button.

Anyone have suggestions on how I can do this? or if it's currently being worked on?

Cheers!

**Comment by jfeinstein10** [comment]
I'm assuming that this refers to using a ViewPager. If so, you can just set an onPageChangeListener and every time you get to the 0 page, change the SlidingMenu touchModeAbove. Should work out of the box. Let me know how it goes.

**Comment by scruffyfox** [comment]
Works great, but now I cant slide right to change the page. Will have to hack the code a little to only detect left to right motions

**Comment by jfeinstein10** [comment]
I just fixed the directional sliding stuff in the slidingright branch. Might be a good place to look for your changes. I'll move them over to the head later.
