### ISSUE TITLE
Theme.NoTitleBar.Fullscreen behind view issue

### ISSUE THREAD

**Issue by azatoth77** [jfeinstein10/SlidingMenu#106]
Hi,
i'm using this library and work very well, but there is a problem when my Activity is in Fullscreen without TitleBar.

The View behind (a View that contain a ListView for a menu), on some device (HTC Desire with cyanogenmod 7.2.0.1, Samsung Galaxy Y rom stock), appear below the 'hidden' notification bar and a black background is visible...

With Galaxy Nexus and Galaxy Nexus S all work fine and this black background is not visible.

Can anyone help me?

Thanks
Dario

**Comment by jfeinstein10** [comment]
Should be fixed
