### ISSUE TITLE
SlidingActivity doesn't do anything.

### ISSUE THREAD

**Issue by the-freak** [jfeinstein10/SlidingMenu#108]
After wrestling with this library trying to get it to work for two days, I'm about ready to give up.  First I ran into compiler issues, then I ran into dependency issues, then more compiler issues, then crash bugs, then, well you get the idea.  Finally, today I got it working with the simple "Hello World!" app that the Android wizard generates without crashing and, lo-and-behold, it doesn't slide at all.

I wish libraries like this had a nice, drop-dead simple example for those of us who want to just get up and running.  A simple _Activity_ that works and demonstrates the minimum code required to integrate the library with an Activity, a couple simple resources, and that's it.  Nothing more, nothing less.

The only example available is Fragment based.  I don't mind if you have a more complex example - it is good for you as you test all the features, but please remember that new developers using a library are looking for the basics.

```
public class MainActivity extends SlidingActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      setContentView(R.layout.activity_main);
      setBehindContentView(R.layout.main_menu);
  }
}
```

That's my Activity code.  There's literally nothing else in the app.  I'm just wanting to experiment and play around with this library at this point.  Here's R.layout.activity_main:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent" >

<TextView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_centerHorizontal="true"
    android:layout_centerVertical="true"
    android:text="@string/hello_world"
    tools:context=".MainActivity" />

</RelativeLayout>
```

And here's R.layout.main_menu:

```
<ListView xmlns:android="http://schemas.android.com/apk/res/android"
android:layout_width="match_parent"
android:layout_height="match_parent">
</ListView>
```

I realize the ListView is empty, but I expect it to at least slide and show nothing rather than not slide at all.  The directions on this library's use are vague.

**Comment by jfeinstein10** [comment]
I understand that you may be frustrated, but that gives you absolutely no excuse to be as rude as you have been in your post above. In my mind, it is ridiculous for you to come here and bash this library because you can't figure out how to correctly import it into your project.

The library does work and is in apps that have millions of users every day such as Zappos, Plume, The Verge, and the Rdio beta app. It works and is the best implementation of this UI pattern out there; I've been working on it for several months and I can assure you of that.

That all being said, I will still try to help you: the default "sliding mode" for SlidingMenu is that it can only be slid from the left margin of the main page. Try to slide from the left edge of the screen to the right. Let me know if this works for you.

You can change this so that it can be slid from anywhere on main page with the line `getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN)`

**Comment by the-freak** [comment]
I reread what I originally wrote and put myself in your shoes as the recipient.  If someone said that to me, I wouldn't see it as rude.  Terse and descriptive with frustration weaved in, but not rude.  But then again, I've got thicker skin than most people and forget that other people are more fragile.  So, I'm sorry about that.  I was just opening a GitHub issue regarding the lack of directions and documentation on usage of this library.

Here's where I'm coming from:  I've used plenty of other Android libraries before without issue.  I expected to wrestle with this library a little because it is Android and Eclipse with a new library I haven't used before but this experience exceeded some internal threshold of tolerance given my experience with other libraries.  The fact is that this library doesn't import cleanly into a brand new Android project within the Eclipse environment and the instructions are rather vague on basic integration, which implies to me that it will be a painless and wonderful experience (it was everything but that).  I was also trying to integrate it with ActionBarSherlock, which works fine for me and has a similar integration pattern.  I ended up kicking the ActionBarSherlock library out of the mix completely until I got this working first.  In addition, writing "getSlidingMenu()." in Eclipse opens the standard drop window with a ton of options to select from - with no documentation on which ones are actually relevant to the SlidingMenu implementation.  Users of a library should not have to go digging into its source to figure out how to use it.  Unless I'm a complete idiot and missed a separate website somewhere, the documentation on this library is non-existent - the only documentation I've found is the README.md file here on GitHub (e.g. setTouchModeAbove() is undocumented in README.md - it wasn't obvious that I was supposed to call that).  As an Android developer, I generally expect to see a simple "get up and running quickly" example, which doesn't exist in this case, or decent documentation on a library, which also appears to not exist in this case.  I prefer the former because it is "copy-pasta ready" with the latter being icing on the cake for customization purposes.  The only correct response is to throw up one's hands in frustration and open a ticket and try to get one or the other to exist to not only help myself but also other developers who might like to use the library too.

Your suggested change does work and I think I can manage from this point now.  (Also got ActionBarSherlock working with this too).  As an experiment, I went back to the original code and it appears to work as well now that I know the "margin" is there and is the default setup but it is much too finicky - the margin is something like 2 pixels wide on my phone.  A user will only ever discover the margin by accident.

Thank you for your help and time spent on this project.  I still say it needs to have better documentation though.

**Comment by jfeinstein10** [comment]
Thank you very much for the apology. I 100% agree that my library does need more documentation, but with me being a full-time college student with a full-time job, it's been really hard for me to find time.

Also, while the method `setTouchModeAbove` itself is not documented, its analog in xml is in the README file (`sliding:touchModeAbove="margin|fullscreen"`). Following with standard Android naming conventions, there are setter and getter methods for this attribute. Its default value is also documented in the README if you want to find it.

Importing is also not that difficult. Right click on your workspace > select 'Import' > select 'Existing Projects into Workspace' > select 'library' or 'example' > click 'Finish'.

The margin is actually 10dp. And margin swiping is a feature that has been documented on many Android UI design blogs and is supported by the community.
