### ISSUE TITLE
How to set good display dimension ?

### ISSUE THREAD

**Issue by gbero** [jfeinstein10/SlidingMenu#109]
Dear,

First of all, many thanks for the good work on this library! It's incredibly nice :)

What I need is to set the size of the menu to fit for the content.
I don't want that the menu take near the whole screen while it only needs less than the quarter.

For the moment I'm using dimension like these : 

values-w720p-land
<dimen name="slidingmenu_behind_offset_width">580dp</dimen>

values-w600p-land
<dimen name="slidingmenu_behind_offset_width">360dp</dimen>

etc...

But this doesn't satisfy me and I'm sure that other apps may have better way of solving this problem :)

Thanks in advance,

**Comment by jfeinstein10** [comment]
This mechanism is definitely the correct one. Just play around with the values until you're happy :)
