### ISSUE TITLE
Disable swipe

### ISSUE THREAD

**Issue by hordurhauks** [jfeinstein10/SlidingMenu#110]
I'm trying to put this into the question section here on github since this is not a bug. Forgive me if it end up in issues :). How do you disable opening the menu with swipe? I want to open the menu with a button and disable the swipe since it can be annoying when you have a viewpager or horizontal scrollview for example on your main screen.

I was looking for available commands in the SlidingMenu object but couldn't find it. I was expecting something like getSlidingMenu().setSwipeEnabled(boolean enabled)

**Comment by staber** [comment]
you were close.

getSlidingMenu().setSlidingEnabled(false);

**Comment by hordurhauks** [comment]
Thanks man!
