### ISSUE TITLE
Second view gets behind the status bar - issue

### ISSUE THREAD

**Issue by asolis90** [jfeinstein10/SlidingMenu#114]
Hi,

First of all great work on this library.
Im having trouble at the time to show the behind view. Everything works fine just that the layout gets behind the status bar of the phone. Here is a picture of what i mean:
http://i50.tinypic.com/30w18hs.png

Please i need help.

Thanks,
Angel

**Comment by l-barbosa** [comment]
I'm experiencing this issue with the latest code.
Did you close the issue because it was fixed or was it not a bug? did you find a workaround?

Thanks for your help.
