### ISSUE TITLE
Support SherlockFragmentActivity

### ISSUE THREAD

**Issue by lancelotspa** [jfeinstein10/SlidingMenu#116]
Hi,

I'm trying to integrate this library which by the way works great into one of my apps. I have an activity that extends SherlockFragmentActivity, looking at the activities available there is no Sliding Activity that extends from SherlockFragmentActivity.

Is this something that you are planning to support or I should create my own activity that does that?

Thank you for the library.

R.

**Comment by jfeinstein10** [comment]
In the README file it explains how to alter the library for his purpose
