### ISSUE TITLE
Slide from right

### ISSUE THREAD

**Issue by korniltsev** [jfeinstein10/SlidingMenu#118]
Have you thought about implementing of an option to chose from what side the behind view should appear?

**Comment by jfeinstein10** [comment]
This already exists in the slidingright branch :)
Zappos is currently using this library from the right

**Comment by wuyexiong** [comment]
thank you very much

**Comment by wuyexiong** [comment]
one view Slide from right
Another view Slide from left ?

behind view a total of two <left and right>
and one aboveView

**Comment by jfeinstein10** [comment]
Yes, that's how it works

**Comment by ghost** [comment]
sorry if it was already answered before. I am just wondering if slide right branch will ever merge into master branch? if so, are there a estimate on when it will be merged. Tks

**Comment by jfeinstein10** [comment]
It will be merged over eventually. Don't really have a time estimate because I'm in school and my workload is always ridiculously high.
