### ISSUE TITLE
Crash on ICS 

### ISSUE THREAD

**Issue by imcaspar** [jfeinstein10/SlidingMenu#12]
Thanks for your great job~ on Android 2.3~3.0 devices it works like a charm:-)
unfortunately, when I test it on emulator4.03 and Moto Xoom(Android4.0.3), it crashed immediately

here is the logcat information:

07-17 11:13:33.670: E/AndroidRuntime(14276): FATAL EXCEPTION: main
07-17 11:13:33.670: E/AndroidRuntime(14276): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.slidingmenu.example/com.slidingmenu.example.ExampleActivity}: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.slidingmenu.lib.SlidingMenu
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.ActivityThread.access$600(ActivityThread.java:123)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.os.Looper.loop(Looper.java:137)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.ActivityThread.main(ActivityThread.java:4424)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at java.lang.reflect.Method.invokeNative(Native Method)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at java.lang.reflect.Method.invoke(Method.java:511)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at dalvik.system.NativeStart.main(Native Method)
07-17 11:13:33.670: E/AndroidRuntime(14276): Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.slidingmenu.lib.SlidingMenu
07-17 11:13:33.670: E/AndroidRuntime(14276):    at com.slidingmenu.lib.app.SlidingActivityHelper.onCreate(SlidingActivityHelper.java:35)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at com.slidingmenu.lib.app.SlidingFragmentActivity.onCreate(SlidingFragmentActivity.java:18)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at com.slidingmenu.example.ExampleActivity.onCreate(ExampleActivity.java:27)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.Activity.performCreate(Activity.java:4465)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
07-17 11:13:33.670: E/AndroidRuntime(14276):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
07-17 11:13:33.670: E/AndroidRuntime(14276):    ... 11 more

**Comment by jfeinstein10** [comment]
Hahaha oops. I forgot to commit something I deleted to GitHub. Just delete the folder res/layout-sw600dp-land.
I'll push the change when I get home. Sorry about that!

**Comment by jfeinstein10** [comment]
Done!

**Comment by jfeinstein10** [comment]
Does it work fine now?

**Comment by imcaspar** [comment]
it works~ thx a lot :-)

**Comment by jfeinstein10** [comment]
No problem. Sorry about that oversight.

**Comment by mh6300** [comment]
Thanks for this. Ran into the same issue for tablet users. Probably should of pulled latest.

**Comment by polyakovsky** [comment]
have the same problem with jelly bean :(

**Comment by jfeinstein10** [comment]
This issue was closed a long time ago. Please make sure you have the most up to date revision
