### ISSUE TITLE
SlidingMenu + Action Bar tabs results in an IllegalStateException

### ISSUE THREAD

**Issue by bill-beckham** [jfeinstein10/SlidingMenu#124]
According to the official Android documentation on Action Bar tabs, calling setContentView is not necessary because 'android.R.id.content' is used as the root element during fragment transactions.  However, SlidingMenu results in an IllegalStateException when attempting to follow the Android docs:

"java.lang.IllegalStateException: Both setBehindContentView must be called in onCreate in addition to setContentView."

I'm only calling setBehindContentView and I see where this message appears in the source for SlidingMenu but I'm not sure how to go about fixing it.  I also tried the latest from git with no change.  Is there a workaround I can use from my code or is this a bug or limitation in SlidingMenu?

**Comment by bill-beckham** [comment]
I worked around this issue by using setContentView() and passing in an empty LinearLayout with width and height set to 'match_parent' and an id that I used within the TabListener.

**Comment by jfeinstein10** [comment]
Yup, definitely the way to go around it for now. Sorry about that.

**Comment by xriu** [comment]
Can you put please a detailed example?

I have an empty linearlayout, but throws the same error for me.

"java.lang.IllegalStateException: Both setBehindContentView must be called in onCreate in addition to setContentView."

content.xml
LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tabcontent"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
/LinearLayout>

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.content);
    .....
    setBehindContentView(R.layout.menu_frame);
        getSupportFragmentManager()
    .beginTransaction()
    .replace(R.id.menu_frame, new ActivitySliding())
    .commit();
    ....
    SlidingMenu sm = getSlidingMenu();
    sm.setShadowWidthRes(R.dimen.shadow_width);
    sm.setShadowDrawable(R.drawable.shadow);
    sm.setBehindOffsetRes(R.dimen.slidingmenu_offset);
    sm.setTouchModeAbove(SlidingMenu.TOUCHMODE_NONE);

Thanks! :)

**Comment by Hikmat101** [comment]
This issue is still open.thats sad
