### ISSUE TITLE
Not smooth when starting new activity and closing SlidingMenu at the same time

### ISSUE THREAD

**Issue by micHar** [jfeinstein10/SlidingMenu#125]
First, let me say that I love your library! It's really great:)

I use it for navigation. The problem is that when I start a new Activity with an Intent and at the same time close the sliding menu, the whole thing becomes sluggish. I tested it on older devices, but also on HTC One S, which is rather fast, so I don't think this is possible to overcome. Starting new Activity is heavy, period. You can see it in The Verge app for example.

So I thought that I would close the menu first, and start the Activity with onClosedListener. The problem is that onClosedListener is fired very late, approximately 1 second after it's been closed. It's too much, isn't it? It's because of the interpolator - when the menu seems to be closed, the Scroller still computes the scroll.

So I came up with a hacky solution. I don't fire onClosed() in completeScroll(), but rather inside computeScroll(), just before it's finished scrolling (CustomViewAbove):

```
@Override
public void computeScroll() {
    if (!mScroller.isFinished()) {
        if (mScroller.computeScrollOffset()) {

            int oldX = getScrollX();
            int oldY = getScrollY();
            int x = mScroller.getCurrX();
            int y = mScroller.getCurrY();

            if (oldX != x || oldY != y) {
                scrollTo(x, y);
                pageScrolled(x);
            }
            if (DEBUG) Log.i(TAG, "computeScroll - still scrolling: "+x+"/"+mScroller.getFinalX());

            //fire closed listener A LITTLE BIT EARLIER
            if(x>=0.93*mScroller.getFinalX())
            if (mClosedListener != null && !isMenuOpen())
                mClosedListener.onClosed();

            // Keep on drawing until the animation has finished.
            invalidate();
            return;
        }
    }

    // Done with scroll, clean up state.
    completeScroll();
}
```

Of course it's far from being great. The main problem is that if fires several times. It was enough for me, though (as I'm launching my app in a few days). So I thought it may be useful for someone. It runs the close animation smoothly and then fires my Intent (of course you have to nullify the Intent once you started the activity).

I'm terribly busy, so I won't submit any changes now. I'll be happy to do it later, when I have time. But I'll write how it could be done, maybe someone will take the topic from there. And maybe you have another idea.

A showAbove(Intent i) method could be introduced. It would compute the scroll and when the menu is almost closed it would fire the Intent.

**Comment by jfeinstein10** [comment]
The main way of fixing this would be to use a Handler as in the Responsive UI Example in the example app. Thanks for this!
