### ISSUE TITLE
FEATURE_ACTION_BAR_OVERLAY is ignored

### ISSUE THREAD

**Issue by AhmadTK** [jfeinstein10/SlidingMenu#126]
I am using Sliding Menu with ActionBarSherlok, the thing is when I set "requestWindowFeature" to FEATURE_ACTION_BAR_OVERLAY and setting the sliding menu property "setSlidingActionBarEnabled" is set to true the result the actionbar is not getting overlay-ed.

does that has anything to do with the sliding menu implementation? if yes how can I fix that.

thank a lot

**Comment by jfeinstein10** [comment]
See the latest commit and the new .attachToActivity method

**Comment by AhmadTK** [comment]
thanks @jfeinstein10  I will try that asap

**Comment by AhmadTK** [comment]
@jfeinstein10 I have tried the new method attachToActivity but its not helping to view the ActionBar in Overlay mode.

Do you have anything in mind?

**Comment by AhmadTK** [comment]
Never mind I was using attachToActivity method without setting the Boolean parameter actionbarOverlay to TRUE. 
Thanks it works perfectly.

**Comment by chebTS** [comment]
Thanks for that bug fixing. It is very helpful.
