### ISSUE TITLE
Artifacts on opening/closing menu

### ISSUE THREAD

**Issue by czaku** [jfeinstein10/SlidingMenu#130]
Hey,

In the application we develop we expect some issues when opening/closin sliding menu when camera/map view are on content view (the behind view is just a list). We tested that behaviour on Samsung Galaxy S2 and S3, Google Nexus 7 shows no artifacts.

The artifacts make the behind view visible even when its hidden, or when the menu is opened parts of content view get mixed with behind view...

**Comment by jfeinstein10** [comment]
Can you please provide screenshots and be a little more specific?

**Comment by SundayLab** [comment]
Hi,

same Problem here menu behind a CameraView works fine on 2.2 and htc desire. But in 2.3.3 and above the BehindView is not properly painted means that parts of the CameraView are showing up. I wonder if there is a kind of hakish solution or do we have a serious bug ?

**Comment by SundayLab** [comment]
solved it ! Please make sure that your ContentView defines a background other wise its transparent and your BehindView gets that mixed up look
