### ISSUE TITLE
Replace Content-Fragment with other fragments

### ISSUE THREAD

**Issue by ajmalsalim** [jfeinstein10/SlidingMenu#134]
in the example project, I can see BirdGridFragment and ColorFragment are showing different pages of same type. How to add different fragments either replacing Content-Fragment (BirdGridFragment,ColorFragment etc) or including a fragment ?

Simply I just want to include different fragments depending upon the selected list item value in MenuFragment. For example, I have 3 MenuFrament List Items : Home, Message, Profile
I just want to load the Message Fragment upon clicking Message List Item and Profile Fragment upon Profile List Item. How to achieve this ?

**Comment by ajmalsalim** [comment]
never mind..solved

**Comment by ankitk93** [comment]
Hey , how did you solved it ?

**Comment by ajmalsalim** [comment]
LOL. It's been more than 4 years and you are supposed to use NavigationDrawer now.

**Comment by ankitk93** [comment]
yeah man that i know , but one of my suggested me to use this library. can we get connected i have a very little doubt which we can  discuss if you have time .
