### ISSUE TITLE
Removig the indicator in sliding content only mode (drawer opened)

### ISSUE THREAD

**Issue by ChristopheVersieux** [jfeinstein10/SlidingMenu#135]
Hello,

Thank a lot for the lib.

I have just a complain that is really annoying for the user.

When you choose a content only sliding menu the indicator stay when the drawer is opened. 

That should not be the case (compare with youtube app in screenshot below) because the user will think there is still something behind the home icon.

As a picture worth a thousand of words:

https://docs.google.com/open?id=0BxpXApcdNdskZndpSnh3RnRzclE

**Comment by dmalis** [comment]
Christopher Attach onopenedlistener and hide it for god sake :-)

**Comment by ChristopheVersieux** [comment]
For god sake, would be a nice enhancement to make it a default feature in the lib, I have searched the issues and never found something talking about this behavior.

Would be cleaner and nicer to have that by default.

Just sayin'

**Comment by dmalis** [comment]
Sure... I was just fooling around a little bit, no hard feelings. I agree
with you completely.

**Comment by jfeinstein10** [comment]
I think this is out of date and I don't understand the problem
