### ISSUE TITLE
SlideMenu Width issue on Tablet Emulator - Eclipse

### ISSUE THREAD

**Issue by ajmalsalim** [jfeinstein10/SlidingMenu#136]
I am having width issues on Google Tablet Emulator avail in eclipse.

http://s7.postimage.org/im9slv2q3/error_jf.jpg

**Comment by jfeinstein10** [comment]
I don't understand the issue. I need more information, but from the looks of it, your menu is too thin

**Comment by ajmalsalim** [comment]
Yup, Its looking good on other screens. See landscape view of same emulator

http://s12.postimage.org/r0wenl54t/landscape_jf.png

**Comment by jfeinstein10** [comment]
This isn't an issue with the library, but rather with how you implement it. You have to manually set the menu width yourself

**Comment by ajmalsalim** [comment]
Please tell me how to do it
I hope its in dimens.xml but I tried editing values, its not working

**Comment by jfeinstein10** [comment]
getSlidingMenu().setBehindOffset(int dimen)

OR

getSlidingMenu().setBehindOffsetRes(R.dimen...)

OR

getSlidingMenu().setBehindWidth(int dimen)

OR

getSlidingMenu().setBehindWidthRes(R.dimen...)

**Comment by ajmalsalim** [comment]
Is it possible to use auto width to the Side Menu depending upon the length of List View Item ?
