### ISSUE TITLE
Video "Repaint issue" rears its head again...

### ISSUE THREAD

**Issue by the-freak** [jfeinstein10/SlidingMenu#138]
Issue #62 is marked as resolved but I'm running the latest version here and VideoView shows a black box overlay when SlidingMenu is showing.  The VideoView is in a very simple SlidingActivity (no fragments - also, SlidingActivity is derived from SherlockActivity).

Running ICS on a real device.

**Comment by nathan1982** [comment]
I'm having the same issues as well with a plain camera view, 
anyone targeting resolution for this issue?
many thanks, 
Nathan

**Comment by jfeinstein10** [comment]
Make the background of your SurfaceView transparent. That has worked for everybody else (see every other issue report)
