### ISSUE TITLE
Problem with SherlockMapActivity in SlidingMapActivity

### ISSUE THREAD

**Issue by ehrior** [jfeinstein10/SlidingMenu#14]
I have just added the last version in Eclipse and I get the following error in the SlidingMapActivity:

The type com.google.android.maps.MapActivity cannot be resolved. It is indirectly referenced from required .class files

Whay should I do to fix it?

**Comment by imcaspar** [comment]
change build target to Google APIs 4.0.3 can fix this problem :-)

**Comment by ehrior** [comment]
Thanks! It works for me! You have saved me some headaches today!

**Comment by imcaspar** [comment]
glad I can help:-)  maybe you should close this issue.
