### ISSUE TITLE
Best way to use Sliding Menu with Google Maps

### ISSUE THREAD

**Issue by ajmalsalim** [jfeinstein10/SlidingMenu#141]
Now I am having a UI like this (http://s8.postimage.org/6y2voq4px/jfjf.png) I have only an Activity that extends SlidingFragmentActivity and 10 Fragments. Each of them will be accessed via Sliding Menu as shown in the image. I am using ABS also. (SlidingMenu library has ABS and MyProject Extends Sliding Menu)

1) Is this a correct way ?
2) If I need to use a MapView, how can I acheive that?
3) If I need to use Mapview in a Action bar Sherlock Tab. Is that possible?

**Comment by hwrdprkns** [comment]
I suggest you check out the android developer blog: http://android-developers.blogspot.com/

Use the v2 version of Google maps SDK, and you'll be able to include a Map Fragment in your code, and using a SlidingMenu should be the least of your problems. Also, I think you can close this issue now.
