### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by akex31** [jfeinstein10/SlidingMenu#145]
Hi, I would like to use your library for my project as it seems great and meet my need.

I can't compile the examples provided because i have the following errors :
- getSupportActionBar()  is undefined
- a few methods like onOptionsItemSelected() can't be override.

My ABS is working fine (and i version 4.2.0) and i had no trouble to set up the slidemenu library.

For ABS, slidemenu and the examples, i set a minsdk to 7 and target 17.
I use JRE6.

Thanks for helping !

**Comment by jfeinstein10** [comment]
Go into slidingFragmentActivity and make it extend SherlockFragmentActivity. That should be the only thing you needed. Other than that you can always download the example from the Play Store :)

**Comment by jtehlert** [comment]
Having the exact same problem. Changed the activity to SherlockFragmentActivity, but that just causes problems with these being "undefined for BaseActivity":
setBehindContentView(R.layout.menu_frame);
SlidingMenu sm = getSlidingMenu();
toggle();

**Comment by sergiocarabantes** [comment]
Same problem!. I can't compile the example

**Comment by jfeinstein10** [comment]
So to reiterate, your version of SlidingFragmentActivity extends SherlockFragmentActivity, correct?

**Comment by akex31** [comment]
The solution "Go into slidingFragmentActivity and make it extend SherlockFragmentActivity"  has worked for me !
And so for the library is working great for me.

Thanks.

**Comment by vanezkw** [comment]
I also have the same problem.

**Comment by ghost** [comment]
Thanks guys. It solved my problem. Just don't forget to import com.actionbarsherlock.app.SherlockFragmentActivity; or just simple hit Cmd+Shift+O :).

**Comment by vishwasdoth** [comment]
Can I user Sliding Menu with my custom ActionBar layout? I am using ABS.

**Comment by waiwu9292** [comment]
Hello,

How can I just take your content only sliding menu bar?

**Comment by jd-alexander** [comment]
I am having the same error as defined by jtehlert. I extended the slidingFragmentActivity to SherlockFragmentActivity, the error is still present.

**Comment by michaelye** [comment]
I have the same problem,and I fixed it by making com.slidingmenu.lib.app.SlidingFragmentActivity.java extends SherlockFragmentActivity,then you will get the error tip: "SherlockFragmentActivity cannot be resolved to a type".So just add the ActionBarSherlock's library for the slide_menu_library,then import correct package.Next add the slide_menu_library for the demo or your project.At last,clean the projects.

**Comment by lx3h** [comment]
Nothing is working for me after changing to "SherlockFragmentActivity".

**Comment by pamio** [comment]
I'm facing the same problem. I've tried above mentioned solutions but nothing worked out for me. I still have the problem and have found no solution yet.

**Comment by lx3h** [comment]
Hi Pramod,

I've this video which helped me out. Give it a go. 

https://www.youtube.com/watch?v=7Efi_4ajfOM&feature=youtube_gdata_player

Good luck! 

Cheers,
Locky

Sent from Yahoo! Mail on Android

**Comment by lakkad-amish** [comment]
I'm facing the same problem.but i didnt got any solution.
error : he method getSupportActionBar() is undefined for the type BaseActivity
Please help me i am new to this libraries.i always use my custom tabs.

**Comment by pamio** [comment]
I resolved the issue. @payraj143  .. Did you include the library properly, also did u do clean after that. My problem was that I did not extend it from SherlockFragmentActivity. You could follow the video mentioned in @lx3h's reply. That should do :)

**Comment by frodberserk** [comment]
awesome work :+1 :)

**Comment by frodberserk** [comment]
Import the actionbarsherlock library to sliding menu library. Then in SlidingFragmentActivity, extend it from Fragment activity to SherlockFragmentActivity. Clean it. Then in your project, import only Sliding Menu library. No need to import ActionbarSherlock library again. Also, make sure that you have same v4 support library in both acrtionbarsherlock and sliding menu libraries. :)

**Comment by DongyangYao666** [comment]
up is the solved method...

**Comment by srnaik** [comment]
Whatever frodberserk has mentioned is absolutely correct :-). Thank you :+1:

**Comment by noahmitchells** [comment]
I’ve been using Tachiyomi for reading manga and it’s honestly one of the best apps available. You can get the latest version safely from https://tachiyomiiapk.com/ no ads, no fake files.
