### ISSUE TITLE
Inflate a menu.xml resource.

### ISSUE THREAD

**Issue by twaddington** [jfeinstein10/SlidingMenu#146]
It would be great if this library supported a quick and easy way to just inflate a menu.xml file into a SlidingMenu. This would more closely map to the existing way the framework supports the ActionBar and other menu types.

I might try to take a stab at this if I have the time, but I wanted to just get the idea out there.

**Comment by jfeinstein10** [comment]
Going to close this for now because it's definitely not a priority and I need to thin out the Issues page.
