### ISSUE TITLE
ArithmeticException: divide by zero when using right panel

### ISSUE THREAD

**Issue by sebasrodriguez** [jfeinstein10/SlidingMenu#148]
The exception is thrown on the CustomViewAbove method pageScrolled.

This is the line that causes the problem.

final int position = xpos / widthWithMargin;

**Comment by jfeinstein10** [comment]
Do you have the most up to date code? What is widthWithMargin defined as?

**Comment by sebasrodriguez** [comment]
I've did a sysout for widthWithMargin and on my samsung S2 its value is 480 on left always, but when the mode for the sliding menu is right it says 480 and on the last call to the pageScrolled method is switched to 0. I have the most up to date code.

**Comment by jfeinstein10** [comment]
And widthWithMargin = getWidth()?

**Comment by jfeinstein10** [comment]
Gotcha and done now!

**Comment by sebasrodriguez** [comment]
Great man, you are the best. I've just tried it and it works fine. 

One doubt about the right panel, when I hit back on the left panel it shows the center view again, but on the right it goes to the previous open application. Where do you keep track of the navigation stack?

**Comment by jfeinstein10** [comment]
Awesome catch again. Fixed it :+1: 
Thanks for all your help. If you find anything else keep letting me know!
