### ISSUE TITLE
Can't get example program to work

### ISSUE THREAD

**Issue by jtehlert** [jfeinstein10/SlidingMenu#149]
I downloaded the sample program, and cannot compile it. 

I have included the library and ABS, but I get these erros in the BaseActivity
- getSupportActionBar() is undefined</li>
- a few methods like onOptionsItemSelected() can't be override.

Following the suggestion in another post with the same problem, I changed slidingFragmentActivity to SherlockFragmentActivity, but all that did was then cause these problems being "undefined for BaseActivity"
- setBehindContentView(R.layout.menu_frame);
- SlidingMenu sm = getSlidingMenu();
- toggle();

I know I can just download the app and see how it works, but I really want to understand and see how the code works before I start to implement it into my app.

**Comment by jfeinstein10** [comment]
Go into SlidingFragmentActivity and make it extend SherlockFragmentActivity instead of FragmentActivity. That's all you have to do.

**Comment by jtehlert** [comment]
Oh, the source. Sorry man, my bad.
