### ISSUE TITLE
Set Behind Content View

### ISSUE THREAD

**Issue by ikermart** [jfeinstein10/SlidingMenu#15]
First of all, congrats for your great library!
Sorry for my english too...
I'm new with Android, and maybe this question is very easy to resolve.
In setBehindContentView I put with xml layout that declares a fragment in it:

``` java
super.onCreate(savedInstanceState);
LayoutInflater inflater = getLayoutInflater();
View v = inflater.inflate(R.layout.list_vibing, null);
super.setContentView(v);
mSlidingMenu = (SlidingMenu) super.findViewById(R.id.slidingmenulayout);
setBehindContentView(R.layout.slidingmenumainlist);
```

slidingmenumainlist.xml :

``` xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="horizontal"
    android:layout_width="15dp"
    android:layout_height="match_parent">
    <fragment android:name="com.convertiva.vibetr.fragments.MenuFragment"
            android:id="@+id/menuList"
            android:layout_weight="1"
            android:layout_width="0dp"
            android:layout_height="match_parent" />
</LinearLayout>
```

The problem is that the behind ListView layout appears, better example as image:
![Alt text](http://www.convertiva.com/assets/img/app1.png)

------------------- Next image:

![Alt text](http://www.convertiva.com/assets/img/app2.png)

Is there any tecnique to hide the behindContent? 
Thank you!

**Comment by jfeinstein10** [comment]
This is because your layouts have transparent backgrounds (if you don't specify one, then it is transparent by default), so you can see through the above to the behind view. Go ahead and define android:background for you above and behind views and that should go away. Hope this helps!

**Comment by patjackson52** [comment]
So will setting the background work on the Sherlock.Dark Theme?

**Comment by ikermart** [comment]
Yes! That was the issue. Thank you!

**Comment by jfeinstein10** [comment]
Setting the background on Sherlock's Dark theme will probably solve the issue, but you have to choose your background wisely so the ActionBar will actually be dark
