### ISSUE TITLE
Dual Left and Right Menu Simultaneously

### ISSUE THREAD

**Issue by mohitsud** [jfeinstein10/SlidingMenu#150]
Outstanding library by the way. Best one by far ( and I tried lots of them ).

Does your library support a left menu AND a right menu, both having different views?

**Comment by jfeinstein10** [comment]
Thanks a lot :smiley_cat: 
Just put an example in the example app called `LeftAndRightActivity`.
It's a little complicated because I wanted the ActionBar to slide both ways. If you don't want that, then it's a heck of a lot easier.
