### ISSUE TITLE
Problem with SlidingMenu and NAVIGATION_MODE_TABS and setSlidingActionBarEnabled(false);

### ISSUE THREAD

**Issue by rbromulo** [jfeinstein10/SlidingMenu#152]
There is a problem when I slide with TABS. Checkout the images. 

There is a solution using SlidingMenu with Tabs and
ActionBarSherlock ? 

Unfortunally the examples that come with the
reposiroty of your project is running with the same behavior, when I
put Tabs

Code that I used

/*\* Set tab navigation mode */
mActionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

this.setSlidingActionBarEnabled(false);

**Comment by jfeinstein10** [comment]
This is not a problem, it's the default behavior. You were referring to The Verge app in what you want. Those are not ActionBar tabs, those are The Verge's custom implementation using a TabHost, etc.

Bottom line : if you want the tabs to slide, you cannot use ActionBar tabs

**Comment by rbromulo** [comment]
Sorry, I didn't know that it's the default behavior.

And 
Can you suggest me some URLs to know how can I achieve that behavior ?

For instance: Do I need to use android TabHost with ActionBarSherlock ?

**Comment by jfeinstein10** [comment]
http://stackoverflow.com/questions/11611405/android-how-do-i-use-tabhost-tabwidget-genrally-tabs-putting-different-activi

**Comment by rbromulo** [comment]
Thanks.
And right now I am looking for this with Swipe Gesture (like ViewPager) but I am not having good results in Google. =/

I will need this to simulate ViewPager and slide menu like Verge Application and others application like that, with ActionBarSherlock. =)

**Comment by jfeinstein10** [comment]
It has nothing to do with ActionBarSherlock. See here for an example:
http://thepseudocoder.wordpress.com/2011/10/13/android-tabs-viewpager-swipe-able-tabs-ftw/

**Comment by rbromulo** [comment]
Right now I get it !

Thanks a Lot jfeinstein. My Application is running like Verge App. =)

**Comment by rbromulo** [comment]
When I created a Example project I had this issue:
- The method onKeyDown(int, KeyEvent) is undefined for the type
  SlidingActivityHelper

Here It is the code

@Override https://github.com/Override
public boolean onKeyDown(int keyCode, KeyEvent event) {
boolean b = mHelper.onKeyDown(keyCode, event);
if (b)
return b;
return super.onKeyDown(keyCode, event);
}

Can you suggest to me, how can I fix this ? This is the unique problem to
run correctly the example that came with SlidingMenu

On Mon, Nov 26, 2012 at 6:55 PM, Jeremy Feinstein
notifications@github.comwrote:

> http://stackoverflow.com/questions/11611405/android-how-do-i-use-tabhost-tabwidget-genrally-tabs-putting-different-activi
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jfeinstein10/SlidingMenu/issues/152#issuecomment-10733459.

## 

"Tudo Vale a Pena se a Alma não é Pequena."

**Comment by rbromulo** [comment]
I've encountered the answer here:
https://github.com/jfeinstein10/SlidingMenu/pull/51

I,'ve just changed to onKeyUp and everithing works well

**Comment by rbromulo** [comment]
I've encountered the answer here:
https://github.com/jfeinstein10/SlidingMenu/pull/51

I,'ve just changed to onKeyUp and everithing works well

Can you close this thread if I am correct?
https://github.com/jfeinstein10/SlidingMenu/issues/152#issuecomment-10830326

Cheers,
Romulo

On Wed, Nov 28, 2012 at 10:47 PM, Romulo Bittencourt rbromulo@gmail.comwrote:

>  When I created a Example project I had this issue:
> - The method onKeyDown(int, KeyEvent) is undefined for the type
>   SlidingActivityHelper
> 
> Here It is the code
> 
> @Override https://github.com/Override
> public boolean onKeyDown(int keyCode, KeyEvent event) {
> boolean b = mHelper.onKeyDown(keyCode, event);
> if (b)
> return b;
> return super.onKeyDown(keyCode, event);
> }
> 
> Can you suggest to me, how can I fix this ? This is the unique problem to
> run correctly the example that came with SlidingMenu
> 
> On Mon, Nov 26, 2012 at 6:55 PM, Jeremy Feinstein <
> notifications@github.com> wrote:
> 
> > http://stackoverflow.com/questions/11611405/android-how-do-i-use-tabhost-tabwidget-genrally-tabs-putting-different-activi
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/jfeinstein10/SlidingMenu/issues/152#issuecomment-10733459.
> 
> ## 
> 
> "Tudo Vale a Pena se a Alma não é Pequena."

## 

"Tudo Vale a Pena se a Alma não é Pequena."
