### ISSUE TITLE
Question: ExampleList Tutorial?

### ISSUE THREAD

**Issue by Prometheus3k** [jfeinstein10/SlidingMenu#155]
Hi there,
I really like to use this library, but am having problems getting the 'ExampleListActivity' project found in the example folder in the git repo, to compile. I am getting errors once I import the project and done the following
- Imported SlidngMenu library to the project
- Set project build target as Android 4.0 (min sdk 7, target sdk 14)
- I am not using actionBarSherlock so have replaced calls to actionbarsherlock with calls to native actionbar

Is there something missing? I would just like to be able to run the project using native actionbar.

**Comment by jfeinstein10** [comment]
Converting everything will be a pain. You'll have to go and correct all the import statements. You'd be better off just installing the version on the Play Store (https://play.google.com/store/apps/details?id=com.slidingmenu.example)
