### ISSUE TITLE
Sliding works but tap does'nt? 

### ISSUE THREAD

**Issue by VeeruPV** [jfeinstein10/SlidingMenu#159]
Hi there
Thanks for this component, works perfectly.
However, it works only when i slide it to the right? I would like to add a tap event as well. Right now a tap does'nt do anything, only dragging the screen works.
And, am using it with actionbarsherlock

This is my code.

// customize the SlidingMenu
        this.setSlidingActionBarEnabled(true);
        getSlidingMenu().setShadowWidthRes(R.dimen.shadow_width);
        getSlidingMenu().setShadowDrawable(R.drawable.shadow);
        getSlidingMenu().setBehindOffsetRes(R.dimen.actionbar_home_width);
        getSlidingMenu().setBehindScrollScale(0.25f);
        getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
        getSlidingMenu().setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);

// customize the ActionBar
        ActionBar actionBar = getSupportActionBar();
        //actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);
        actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_STANDARD);
        actionBar.setIcon(R.drawable.menu_button);
        actionBar.setTitle("");  
        actionBar.setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setCustomView(gF.createTitle(this,"mFace Wall"));
        getSupportActionBar().setDisplayShowCustomEnabled(true);

**Comment by jfeinstein10** [comment]
Please read through the example code. There are several methods to do this such as 'showContent' 'showMenu' and 'toggle' that you can call in an incredibly simple OnClickListener

**Comment by VeeruPV** [comment]
Thanks for the quick reply.
Yes i understand there is a toggle menu, which i use in other parts of the app. 
The part i am confused is, where do i add the onclicklistener? Am sorry if i sounded dumb.

**Comment by jfeinstein10** [comment]
If you allow tapping on the content view to open the SlidingMenu, then the user can never touch anything in the content view, which is generally a terrible idea

**Comment by jfeinstein10** [comment]
If you want to attach it to a button, just do it where you usually do things like that
