### ISSUE TITLE
Unable to get ActionBar to display

### ISSUE THREAD

**Issue by RyanBeuler** [jfeinstein10/SlidingMenu#16]
I'm trying to create a very basic implementation of your SlidingMenu but am having problems getting the ActionBar to display.  When I run my app the sliding mechanic works fine as I can manually slide back and forth but unfortunately I'm not able to get the ActionBar to display.

here's my main activity....

public class MainActivity extends SlidingActivity {

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);
    requestWindowFeature(Window.FEATURE_ACTION_BAR);

    ActionBar actionBar = getSupportActionBar();

    SlidingMenu menu = (SlidingMenu)findViewById(R.id.slidingmenulayout);

    menu.setViewAbove(getLayoutInflater().inflate(R.layout.main1, null));
    menu.setViewBehind(getLayoutInflater().inflate(R.layout.main2, null));
    menu.setBehindOffsetRes(R.dimen.actionbar_home_width);
    menu.setBehindScrollScale(0.5f);
    menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
    menu.showAbove();   

    actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_STANDARD);
    actionBar.setDisplayHomeAsUpEnabled(true);
    actionBar.setIcon(R.drawable.sblogo);
    actionBar.show();
}
```

Other info:

My project and both libraries are set to API 14
I have android:theme="@style/Theme.Sherlock.Light.DarkActionBar" set in my Manifest's activity section.

If anyone has any ideas what I'm doing wrong or overlooking it would be greatly appreciated.  Thanks.

**Comment by jfeinstein10** [comment]
Don't directly set the menu's ViewAbove and ViewBehind. Do that through setContentView and setBehindContentView.
You should actually be getting an error message because setBehindContentView hasn't been called. I need to fix that bug.
Also, try to use getSlidingMenu() to retrieve the SlidingMenu.

**Comment by Macarse** [comment]
Try removing:

requestWindowFeature(Window.FEATURE_ACTION_BAR);

**Comment by jfeinstein10** [comment]
I had a couple of flags set wrong under the hood. It should be working now, but as I said, don't call menu.setViewAbove or menu.setViewBehind. Do it through the Activity level calls.

**Comment by RyanBeuler** [comment]
Ok thanks guys I'll give those suggestions a shot and see if it works...

**Comment by RyanBeuler** [comment]
Yup that solved it, ActionBar now displays.  Thanks for the help!

**Comment by jfeinstein10** [comment]
Awesome. Glad to help and thanks for inadvertently spotting that bug :)

**Comment by RyanBeuler** [comment]
No problem, I think I may have inadvertently spotted another one but I'll write it up in a new bug report just in case someone else runs into the same issue.. don't want to get it buried in this thread.
