### ISSUE TITLE
Allow for custom sorting/editing menu contents

### ISSUE THREAD

**Issue by uniquePWD** [jfeinstein10/SlidingMenu#162]
This would be a fantastic feature. Just thought I'd put it on the radar.

**Comment by jfeinstein10** [comment]
I don't quite understand what you mean here. What you put in the menu portion is up to you; I don't include a standard menu template.

**Comment by uniquePWD** [comment]
I meant in a way where I'd generate the content of the menu from a users subscriptions (for example) and if the user wanted the bottom subscription at the top, they could drag it there.

**Comment by jfeinstein10** [comment]
That's part of the way you implement whatever you decide to put in the menu, not part of the library. There are simple mechanism to change what you put in the menu already though
