### ISSUE TITLE
How can I set right menu offset?

### ISSUE THREAD

**Issue by Jimweb3** [jfeinstein10/SlidingMenu#165]
Sorry about the last easy question. :). .When I use Left and right model, I can only set the behind offset,and then the left and right menu have the same offset , how can I set left and right menu offset in different size? and I also want sliding is faster,can I set it ?

**Comment by jfeinstein10** [comment]
Right now, they'll both be the same thing. In the future they won't necessarily

**Comment by liruqi** [comment]
I'm working on this right now, I'll send pull request if finished.

**Comment by liruqi** [comment]
Done, although not so smooth, but it works.
https://github.com/liruqi/SlidingMenu/commit/5091c4d00f32552f0c212be8d1d50d791bdf82c2
