### ISSUE TITLE
Touch margin too small

### ISSUE THREAD

**Issue by Sloy** [jfeinstein10/SlidingMenu#173]
Hi,
I just updated the library and I've found that, when in TOUCHMODE_MARGIN I have to drag from the leftmost pixel of the screen to open the menu. 

The weird thing is that in the example application it works fine, with approximately 1/2 inch of margin to drag from. I don't know if it's some bug or I'm doing something wrong. My onCreate method is almost the same that the example's. 

``` java
public class BaseSlidingActivity extends SlidingFragmentActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // set the Behind View
        setBehindContentView(R.layout.menu_frame);
        FragmentTransaction t = this.getSupportFragmentManager().beginTransaction();
        Fragment mFrag = new SlidingMenuFragment();
        t.replace(R.id.menu_frame, mFrag);
        t.commit();

        // customize the SlidingMenu
        SlidingMenu sm = getSlidingMenu();
        sm.setShadowWidthRes(R.dimen.shadow_width);
        sm.setShadowDrawable(R.drawable.shadow);
        sm.setBehindOffsetRes(R.dimen.slidingmenu_offset);
        sm.setTouchModeAbove(SlidingMenu.TOUCHMODE_MARGIN);

        // customize the ActionBar
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            toggle();
            return true;
        }else{
            return false;
        }
    }
}
```

I've been playing with the code for a while but I can't find the problem

**Comment by geekkoz** [comment]
i was wondering the same, i modified the attribute MARGIN_THRESHOLD in the customeViewBehind class from 20 dipsto 50 dips and it seems to work for me.

**Comment by Matungos** [comment]
CustomViewAbove...

**Comment by arnestockmans** [comment]
I had the same issue, so I made a getter and a setter for this value. If you're interested in it, I just created a pull request for it.

**Comment by jfeinstein10** [comment]
I'll most likely be changing it to the recommended 48 dps

**Comment by jfeinstein10** [comment]
Has been increased to 48dp

**Comment by amnazhatdinov** [comment]
thanks, that works
