### ISSUE TITLE
setStatic issue

### ISSUE THREAD

**Issue by neepl** [jfeinstein10/SlidingMenu#177]
After call to `SlidingMenu.setStatic(true)` mCustomViewBehind goes null. So this code in CustomViewAbove stops working:

``` java
    protected void dispatchDraw(Canvas canvas) {
        super.dispatchDraw(canvas);
        // Draw the margin drawable if needed.
        mCustomViewBehind.drawShadow(mContent, canvas);

        mCustomViewBehind.drawFade(mContent, canvas, getPercentOpen());
        //      if (mSelectorEnabled)
        //          onDrawMenuSelector(canvas, getPercentOpen());
    }
```

Null-check is needed. Thanks.

**Comment by jfeinstein10** [comment]
Ah, I need to remove setStatic. It's an artifact that no longer applies.

**Comment by neepl** [comment]
Any suggestions what to use instead?

**Comment by jfeinstein10** [comment]
Two frames and put the menu in one and the content in another. Just like in the ResponsiveUiActivity in the example.

**Comment by neepl** [comment]
Thanks for the answer. And thanks for your library. It rocks!
