### ISSUE TITLE
CustomViewAbove is not invalidated after scrollTo

### ISSUE THREAD

**Issue by henieek** [jfeinstein10/SlidingMenu#179]
Hello,

Current scrollTo() method implementation in CustomViewAbove looks like that:

``` java
    @Override
    public void scrollTo(int x, int y) {
        super.scrollTo(x, y);
        mScrollX = x;
        if (mEnabled)
            mCustomViewBehind.scrollBehindTo(mContent, x, y);
//      if (mSelectorDrawable != null)
//          invalidate();
    }
```

Last two lines were commented-out in this commit: https://github.com/jfeinstein10/SlidingMenu/commit/38ba0eff8f5f6b7a16c5a0498ad1b97ac436ce5c

Unfortunately, that change caused SlidingMenu to not work correctly then you're trying to invoke:

``` java
getSlidingMenu().showMenu(false)
```

in onResume() method for example.

smoothScrollTo(int,int,int) is invalidating itself at the end of every invocation, and there is absolutely no problem with it when we call getSlidingMenu().showMenu(true) (or just showMenu()).

Thanks!

**Comment by jfeinstein10** [comment]
Think this has since been fixed.
