### ISSUE TITLE
Allow menu to fade in/out as it opens/closes

### ISSUE THREAD

**Issue by DougCompton** [jfeinstein10/SlidingMenu#18]
Here is a code snippet to allow the behind view to fade in/out as it is opening/closing.

Place this in CustomViewAbove.java (overwrite the existing onDraw)

```
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        final int behindWidth = this.getBehindWidth();

        // Draw the margin drawable if needed.
        if (mShadowWidth > 0 && mShadowDrawable != null) {
            final int left = behindWidth - mShadowWidth;
            mShadowDrawable.setBounds(left, mTopPageBounds, left + mShadowWidth,
                    mBottomPageBounds);
            mShadowDrawable.draw(canvas);
        }

        final float openPercent = (mScroller.getCurrX()) / (float) behindWidth;

        onDrawMenuFade(canvas, openPercent, behindWidth);
    }

    private static final int MAXIMUM_MENU_FADE = 170;
    private Paint mBehindFadePaint = new Paint();

    private void onDrawMenuFade(Canvas canvas, float openPercent, int width) {
        final int alpha = (int) (MAXIMUM_MENU_FADE * openPercent);

        if (alpha > 0) {
            mBehindFadePaint.setColor(Color.argb(alpha, 0, 0, 0));
            canvas.drawRect(0, 0, width, getHeight(), mBehindFadePaint);
        }
    }
```

**Comment by jfeinstein10** [comment]
This is great! Thanks for sharing!
It was a feature that I meant to do after a while but never got around to. I'll put it in to the repo as soon as I can.

**Comment by jfeinstein10** [comment]
Does this solution work for user scrolling? I can't seem to get it to work.

**Comment by DougCompton** [comment]
I noticed that yesterday, try this.

```
        float openPercent;
        if (mScrollState == SCROLL_STATE_DRAGGING) {
            openPercent= (behindWidth - Math.min(mLastMotionX, behindWidth)) / (float) behindWidth;
        } else {
            openPercent= (mScroller.getCurrX()) / (float) behindWidth;
        }
```

**Comment by DougCompton** [comment]
You mentioned there are a lot of bugs with fading.  What issues are you seeing?

**Comment by jfeinstein10** [comment]
Sometimes when closing or opening, the fade color will go to the extreme. For example, I'll be opening it and then when I'm halfway I'll let go and the color will go from half-faded to all the way faded and then to transparent when it opens all the way. I'm pretty sure it has something to do with `mScroller` not being updated on user touch. Maybe if I override scrollTo so it doesn't use the built in and always uses `mScroller`. I'll check it out later.

**Comment by iPaulPro** [comment]
I know this is in progress, but just a note: It would be great if we had the option to do the same type of fading (in reverse) with the above view.
