### ISSUE TITLE
How can i close the slidingmenu  when i use gesture in the fragment?

### ISSUE THREAD

**Issue by atomfirefly** [jfeinstein10/SlidingMenu#180]
Hi,guys 
First of all, a big thanks to the developer. The library works beautifully and runs smooth even on older devices. Now  i  want to close the slidingmenu when using Gestures in the fragment which is the behind view  , but the GestureDetector just can not  catch Gestures . So please nudge me in the right direction.

Thanks !

**Comment by jfeinstein10** [comment]
If you're using the fullscreen touch mode, it'll definitely have issues. I suggest using touch mode "none" if you're going to handle all close gestures yourself.

**Comment by atomfirefly** [comment]
thanks for you reply ! i have work out this problem !
