### ISSUE TITLE
TOUCHMODE_MARGIN  not working on unclickable layouts

### ISSUE THREAD

**Issue by imbryk** [jfeinstein10/SlidingMenu#181]
Hi,

I just noticed that `TOUCHMODE_MARGIN`  doesn't work for some of my layouts.
e.g. if you try to set content  with an empty `LinearLayout` it won't work, but if you put a `Button` in the layout:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" 
    android:background="@android:color/background_dark"
    >
    <Button 
        android:layout_width="match_parent"
        android:layout_height="200dp"/>
</RelativeLayout>
```

it will work, but only on clickable element - the button

I came to conclusion that view must be clickable, and indeed it's enough to set `android:clickable="true"` to make  `TOUCHMODE_MARGIN`  work

**Comment by Odrin** [comment]
\+ 1
I just tried it and it worked for my Xperia S

**Comment by hwrdprkns** [comment]
I also see with the fullscreen touch mode. If the view isn't clickable then the sliding menu doesn't seem to receive touch events.

**Comment by Gyllsdorff** [comment]
Same thing for me. 

When I have a layout with a empty relative layout and setTouchModeAbove(TOUCHMODE_FULLSCREEN) then I can't open the menu by dragging my finger on the main layout. It does work if I drag on the actionbar.

**Comment by hwrdprkns** [comment]
That's because the ActionBar is clickable. A quick workaround for this issue is to, whenever you have the menu enabled is `yourAboveView.setClickable(true)`.

The library should _probably_ do this for you... if sliding is enabled.

**Comment by hwrdprkns** [comment]
I think this can be closed now since the latest code fixes the problem.
