### ISSUE TITLE
Touches keep going through to the SlidingMenu even though it is not visible

### ISSUE THREAD

**Issue by ErnestG** [jfeinstein10/SlidingMenu#183]
I have touches that are going through my full screen layout, and clicking on the sliding menu. Any ideas?

**Comment by EpicDraws** [comment]
I see this as well whenever another view isn't placed on top. Essentially, the sliding menu should ignore clicks on the 'behind' layout when it is not visible.

**Comment by ErnestG** [comment]
I have a layout that takes up the whole screen by setting layout height and width to fill_parent, but it still accepts the clicks. What am I doing wrong?

**Comment by jfeinstein10** [comment]
Should be resolved now.
