### ISSUE TITLE
How to use SlidingMenu with ViewPager?

### ISSUE THREAD

**Issue by bartwell** [jfeinstein10/SlidingMenu#185]
I have ViewPager with content in MainActivity and I want to add SlidingMenu. I need that the SlidingMenu open only on the first page of ViewPager. I've found this example: https://github.com/Alexrs95/SlidingMenuAndViewPager

But in this implementation it doesn't working well: it hard to open menu (SlidingMenu only react on narrow left side of screen) and working on every page (not only first). How to implement it properly?

**Comment by CmoaToto** [comment]
You can use my fork : https://github.com/CmoaToto/SlidingMenu or my pull request (it's the same) https://github.com/jfeinstein10/SlidingMenu/pull/176 .

Set your SlidingMenu as usual then add your ViewPager as IgnoredView. To set it ignored only when on the first screen, set some listeners like that :

<pre>
    final ViewPager vp = ((ViewPager) findViewById(R.id.viewpager))
    vp.setOnPageChangeListener(new ViewPager.SimpleOnPageChangeListener() {
        @Override
        public void onPageSelected(int position) {
            super.onPageSelected(position);
            if (position == 0) {
                menu.removeIgnoredView(vp);
            } else {
                menu.addIgnoredView(vp);
            }
        }
    });
</pre>

**Comment by bartwell** [comment]
I am sorry, but this solution doesn't working for me with same symptoms...

**Comment by bartwell** [comment]
I've find ViewPagerActivity.java :-[ It's working fine.

**Comment by dasbiswajit** [comment]
I have got the slimier situation. it is working but my CirclePageIndicator is not working Any Idea @CmoaToto ?

My Code- 




public class MainActivity extends FragmentActivity {
//public class MainActivity extends SlidingFragmentActivity {
	
	// Declare Variables
	ViewPager viewPager;
	PagerAdapter adapter;	
	CirclePageIndicator mIndicator;	
	private int mWidthScreen;
	private int mHeightScreen;	
	private Bundle bundle;
	private List<Fragment> frgScreens;
	private int selectedtheme;
	private Handler mHandler = new Handler();
	//public  mlayoutForeground;
	
	//Menu buttons
	private ImageView mBtnMenu;
	private SlidingMenu menu;
	


	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		
		// Get the view from viewpager_main.xml
		setContentView(R.layout.viewpager_main);
		
		getScreenHeightWidhth();	
		buildargument();
		
		//setting the required theme
		this.selectedtheme=1;		
		initialisePaging(selectedtheme); //Page creating function
				
		generateMenu();
		
	
		
	}
	
	private void initialisePaging(int theme) {	
		
		// Locate the ViewPager in viewpager_main.xml
		viewPager = (ViewPager) findViewById(R.id.pager);
		
		//#FIXME try to implement like theme.basic
		//clearing old entries
		frgScreens=new Vector<Fragment>();
		
		if(theme==1)
		{
			frgScreens=this.basicThemes();
		}
		
		if(theme==2)
		{	
			
			frgScreens=this.forecastThemes();
		}
	
		
  	  //Bind result to ViewPagerAdapter	
		adapter =new ViewPagerAdapter(this.getSupportFragmentManager(), frgScreens);
					
		// Binds the Adapter to the ViewPager
		this.viewPager.setAdapter(adapter);		
		addAndConfigureCirclePagerAdapter();
		
		
			
	}
	
	
	/*
	 * forecast theme fragment
	 */
	private List<Fragment> forecastThemes()
	{
		Fragment frgForecast1=Fragment.instantiate(this,ForecastScreen1.class.getName());
		
		//#FIXME forecast2 problematic
		//Fragment frgForecast2=Fragment.instantiate(this,ForecastScreen2.class.getName());
		
		frgForecast1.setArguments(bundle);
		//frgForecast2.setArguments(bundle);
		
		
		List<Fragment> frgForecastScreens = new Vector<Fragment>();
		
		frgForecastScreens.add(frgForecast1);
		//frgForecastScreens.add(frgForecast2);
		
		return frgForecastScreens;
		
	}
	/*
	 * Basic theme fragments
	 */
	private List<Fragment> basicThemes()
	{
		//declaring fragments Group Basic
        Fragment frgBasic1=Fragment.instantiate(this,Basic1.class.getName());
        Fragment frgBasic2=Fragment.instantiate(this,Basic2.class.getName());
        Fragment frgBasic3=Fragment.instantiate(this,Basic3.class.getName());
        Fragment frgBasic4=Fragment.instantiate(this,Basic4.class.getName());
  
        //Passing arguments
        frgBasic1.setArguments(bundle);
        frgBasic2.setArguments(bundle);
        frgBasic3.setArguments(bundle);
        frgBasic4.setArguments(bundle);
     	
		
        //Loading screens into Fragment list
		List<Fragment> frgBasicScreens = new Vector<Fragment>();
		
		frgBasicScreens.add(frgBasic1);
		frgBasicScreens.add(frgBasic2);
		frgBasicScreens.add(frgBasic3);
		frgBasicScreens.add(frgBasic4);
		
		
		return frgBasicScreens;
		
	}
	
	
	 /*
	  * Applying circlepageradapter color
	  */
	 private void addAndConfigureCirclePagerAdapter()
	 {
		 
		 this.viewPager.setOnPageChangeListener(new ViewPager.SimpleOnPageChangeListener() {
			    @Override
			    public void onPageSelected(int position) {
					            super.onPageSelected(position);
					            if (position == 0) {
					                menu.removeIgnoredView(viewPager);
					            } else {
					                menu.addIgnoredView(viewPager);
					            }
					        }
					    });
		 
		mIndicator = (CirclePageIndicator) findViewById(R.id.indicator);
		this.mIndicator.setBackgroundColor(Color.TRANSPARENT);
		this.mIndicator.setPadding(5, 5, 5, 5);
		this.mIndicator.setRadius(12);
		this.mIndicator.setFillColor(Color.argb(255, 175, 220, 243));
		final float density = getResources().getDisplayMetrics().density;
		this.mIndicator.setRadius(6 * density);
		this.mIndicator.setViewPager(viewPager); 
		
		
	 }
	 
	/*
	 * Function to get height and width
	 * 
	 */
	private void getScreenHeightWidhth()
	{
		 DisplayMetrics localDisplayMetrics = new DisplayMetrics();
		 getWindowManager().getDefaultDisplay().getMetrics(localDisplayMetrics);		    
		 this.mWidthScreen = localDisplayMetrics.widthPixels;
		 this.mHeightScreen = localDisplayMetrics.heightPixels;	
		 mHandler.post(new DisplayToast(this, "Width Screen:"+ mWidthScreen + ". Height Screen: "+ mHeightScreen+ "."));
	}
	
	/*
	 * Bundle that bind extra arguments with every fragments
	 * mWidthScreen : Putting 'mWidthScreen'as a pasing argument
	 */
	private void buildargument()
	{
		this.bundle = new Bundle();
        bundle.putInt("mWidthScreen", this.mWidthScreen);
	}

	public void generateMenu()
	{
		//enable button
		//buttonsOn();
		
 		mBtnMenu = (ImageView) findViewById(R.id.btnMenu);
 		
 		menu = new SlidingMenu(this);
		menu.setMode(SlidingMenu.LEFT);
		menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
		menu.setShadowWidth(5);
		menu.setFadeDegree(0.0f);
		menu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);
		menu.setBehindWidth(500);
		menu.setMenu(R.layout.menu_frame);
		
 		mBtnMenu.setOnClickListener(new OnClickListener() {
 	        @Override
 	        public void onClick(View arg0) {
 	         // menu.showMenu();
 	           
 	          menu.toggle();
 	         mBtnMenu.setEnabled(true);
 	        }
 	    });
 		
 	
 	
 		
 		 
	}
	
	public void buttonsOff()
	  {
	    this.mBtnMenu.setEnabled(false);

	  }

	  public void buttonsOn()
	  {

	    this.mBtnMenu.setEnabled(true);
	  }

	
	 @Override
	    protected void onResume() {
	        super.onResume();
	    }

	    @Override
	    public void onDestroy() {
	        super.onDestroy();
	    }
	
	
}

When I run the code I found the circlepageindicator indicating first page if I am swiping to different page also. **Here is the snap short.**
![screenshot_2015-09-29-14-17-56](https://cloud.githubusercontent.com/assets/3852746/10159529/68b6fc44-66b6-11e5-9070-cc63c28a923a.png)

**Normally It should be like this.**

![screenshot_2015-09-26-08-33-50 1](https://cloud.githubusercontent.com/assets/3852746/10159585/c9c72572-66b6-11e5-9d92-e388faf6812c.png)


Regards
Biswajit
