### ISSUE TITLE
How can I swipe behind view to close slidingMenu?

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#186]
My behind view is on the left, when behind view is visible (open), I have to swipe above view in order to close the behind view. I am wondering if it is possible to swipe behind view to the left to close behind view. tks

**Comment by hwrdprkns** [comment]
Currently not possible with this library afaik.

**Comment by atomfirefly** [comment]
see the issue #180

**Comment by jfeinstein10** [comment]
Duplicate
