### ISSUE TITLE
Can we make background view as overlay on top of content view..

### ISSUE THREAD

**Issue by satyan** [jfeinstein10/SlidingMenu#188]
First, Thanks for the great library.. 

I wanted to know if there's an option to make the background view appear on top of the content view and not slide the content view.

An example would be Wunderlist's detail view.. It just appears on top of the content view and doesn't slide it to the left.

If its not available, do you have any recommendations? 

thanks,
Satya

![unnamed](https://f.cloud.github.com/assets/148153/21738/35a3225c-49cb-11e2-8fef-5269df21c03c.jpg)

**Comment by hwrdprkns** [comment]
You don't need a library this complex to implement something like that. Just use a DialogFragment with that layout and stuff and you should be alright.
