### ISSUE TITLE
WebView crashes

### ISSUE THREAD

**Issue by samuelngs** [jfeinstein10/SlidingMenu#19]
Hi :)

   Just want to report something.

```
       I found that WebView with SlidingMenu will crash when GPU rendering is enabled.
```

And it seems ok when GPU rendering is disabled. I tried it on several Jelly Bean and ICS devices.
SlidingMenu works perfect on ICS but not JellyBean. I think crashes will only occur on JB OS.
Except that, everything works great. Thanks for the library! (Sorry for my bad English)

**Comment by jfeinstein10** [comment]
Your English is great, don't worry!
This is strange, thanks for reporting it.

**Comment by gicp89** [comment]
I watend to know if you found a way to fix this problem? Since i'm having the same issue on my project and have not found a solution to it. Thanks for the library!

**Comment by samuelngs** [comment]
I believe using Webview inside fragment could fix your problem.
Let me know if it works for you :)

**Comment by gicp89** [comment]
I've been trying for the past three day to use my Webview inside a fragment without any success, can you help with how to do this or point me in the right direction?

**Comment by b4rd** [comment]
I've been using WebView in a fragment from the beginnig and also noticed the problem (JellyBean). Disabling hardareAccelerated solved it, but the sliding animation is not as smooth this way.
Edit: Setting the layerType to software on the WebView is sufficient.
