### ISSUE TITLE
Can I use two slidemenu?

### ISSUE THREAD

**Issue by Yria** [jfeinstein10/SlidingMenu#190]
I want to use Slidemenu to left and right.
Can I try it?

**Comment by hwrdprkns** [comment]
Absolutely. There is even support for this in the library, there's no need to create two instances of SlidingMenu!

**Comment by Yria** [comment]
Thank you for your response! What I meant to ask was if I can use both rightside and left side sliding menu in one same screen(view). How would I be able to do this?

**Comment by hwrdprkns** [comment]
Not sure what you're asking. You can have both a left and right sliding menu in one activity. You can't show them both at the same time.

**Comment by Yria** [comment]
I'm Sorry. I do not understand this library now until.
I solved problem. setContentView, setBehindContentView, setSecondaryMenu are use other view.
Thank you for your help.

---

Oh, I understand. but this library show same view in two sliding menu.
I want to show difference view in two sliding menu.
(ex: android facebook official app)

**Comment by hwrdprkns** [comment]
setContentView sets the content of the above view.
setBehindContentView sets the content of the left menu
setSecondaryMenu sets the content of the right menu
