### ISSUE TITLE
Overlay action bar in theme not honored by SLIDING_CONTENT

### ISSUE THREAD

**Issue by jwoolston** [jfeinstein10/SlidingMenu#192]
In our app we have been using SlidingMenu for 5 months or so as a static copy with no problems but recently moved to be synced with GitHub to stay up to date. After switching we have had an issue develop.

Our application's theme uses the windowActionBarOverlay attribute set to true and we set a transparency on the action bar. If we use SlidingMenu.SLIDING_WINDOW then the action bar appears correctly over the the content view, however it moves with the content which is not what we want so we use SlidingMenu.SLIDING_CONTENT. When we do this, the action bar is drawn behind our content and the lower half is obscured by the content. 

Is there a solution to this that I am unaware of? I am confused because all I did was update our version of the library so perhaps something changed with how it handles the views?

**Comment by jwoolston** [comment]
Switching from using the SlidingMenu as an XML view to using the sliding activity did not fix the issue. Also, when I switched to using the SlidingActivity from the library, the overlay theme setting is completely ignored.

**Comment by xiamubobby** [comment]
I'm stuck in just just the same problem deeply..., was about to issue that and then i saw this... but jfeinstein10 has no answer so far and Google does no help...
Shall i publish another same question? That's not cool, but no answer here...
Well Maybe he's working hard on it...

**Comment by jwoolston** [comment]
I don't think a new issue is needed. It will just pollute the already full issue list. A library like this tends to bring in a lot of traffic. People watching it will get emails about it so if we are getting no input its because nobody has input to give. I have been digging through the library trying to figure out the issue. I will do a deeper comparison of code that worked before to figure it out and keep this issue updated. In the mean time the only solution I have is to not use the overlay action bar for SLIDING_CONTENT.

**Comment by jfeinstein10** [comment]
Yeah, don't start another issue just to get my attention; that's just spamming and is really not appreciated. I'll try to take a look at this tonight.

**Comment by jfeinstein10** [comment]
See the latest commit and the new .attachToActivity method

**Comment by jwoolston** [comment]
Excellent. Thanks for the fix.

**Comment by jfeinstein10** [comment]
Also remember that is you're using ActionBarSherlock requestFeature does NOT work. You have to declare it in your theme "windowActionBarOverlay=true"

**Comment by xiamubobby** [comment]
Just works, thx lot lot.
