### ISSUE TITLE
Menu being drawn when closed

### ISSUE THREAD

**Issue by egfconnor** [jfeinstein10/SlidingMenu#193]
I've been using the show overdraw feature of Android 4.2 and noticed that my side menu listview is still being drawn when I close the side menu. A simple set visibility to gone would work, but I can't find any method that works for this. setOnClosedListener works fine but I can't detect when they start sliding the menu open to set it to visible again as far as I'm aware.

**Comment by jfeinstein10** [comment]
Hmm strange. If you look at line 204 of CustomViewBehind it should be GONE already. Can you debug there and see if it indeed getting set to GONE?

**Comment by egfconnor** [comment]
Turns out I was using a really old/wrong version of your library. I went to find line 204 and it was only 100 some lines long! Downloaded the current one and everything is fixed. Appreciate your response which did lead to me fixing it. :+1:

**Comment by jfeinstein10** [comment]
Glad to hear :smile: 
Happy coding!
