### ISSUE TITLE
Custom design in SlidingMenu

### ISSUE THREAD

**Issue by tuygun** [jfeinstein10/SlidingMenu#195]
Is it possible to make/put custom ui blocks inside the sliding menu. For example in Google+ they put menu items like "Home", "Profile" and etc,. after that they have "Notifications" part which is kind a different block. Another example is Evernote's application which has 2x2 matrix of actions. I would like to put there some interactive blocks like video or play,pause buttons for current playing music.  
Thanks, (I am really beginner for android)

**Comment by jfeinstein10** [comment]
You can put whatever the heck you want in the menu portion using the setMenu method
