### ISSUE TITLE
Change right menu width

### ISSUE THREAD

**Issue by mesmzk** [jfeinstein10/SlidingMenu#196]
Hi.  How can i correctly change width of right panel? I want the right panel don't get out from screen when app show left menu. So user can see all content at right panel. Can you suggest a solution?

**Comment by jfeinstein10** [comment]
You can't have left and right open at the same time

**Comment by mesmzk** [comment]
why not? i just done this by change linear layout parent of above view width. i also need ot change it during scrolling...

**Comment by jfeinstein10** [comment]
Then I don't really understand what you're saying

**Comment by mesmzk** [comment]
ok, never mind. for tablet version i need to show all content of right menu with the left menu open. i think i can figure it. thanks. sorry for my english.
