### ISSUE TITLE
Can i use the right side slidingmenu from Fragment Object(not from FragmentActivity)

### ISSUE THREAD

**Issue by yingkun** [jfeinstein10/SlidingMenu#197]
Now i have a left slidingmenu is for changing fragment and i want to have a right side to change content of the fragment  ,, Did you have a class of Fragmentsliding for use the right slidingmenu from fragment  ? ,, Can  you recommend me for the solution ? thank you very much and sorry for my bad english.

**Comment by jfeinstein10** [comment]
SlidingMenu.set mode(SlidingMenu.LEFT_RIGHT)
