### ISSUE TITLE
attachToActivity SLIDING_CONTENT bug with ABS on pre-3.0 devices

### ISSUE THREAD

**Issue by ahmedre** [jfeinstein10/SlidingMenu#198]
hi,
if using ActionBarSherlock on a pre-honeycomb device, `attachToActivity` with `SLIDING_CONTENT` blocks the content view from getting any touch events (or even rendering in normal cases).

one solution that works is to get the first child of the content in `attachToActivity` under the `SLIDING_CONTENT` case in `SlidingMenu.java`:

```
ViewGroup contentParent = (ViewGroup)activity.findViewById(android.R.id.content);
View content = contentParent.getChildAt(0);
```

i think the reason is that on pre-honeycomb, ABS does not actually live in the decor view, and `getContent` returns a `NineFrameLayout.`  the child of this is my layout's ViewGroup.  on Jellybean, `getContent` returns a normal `FrameLayout` containing my ViewGroup as its child.  it would seem that wrapping the `NineFrameLayout` inside the SlidingMenu view causes issues.

as for suggested fixes:
1.  the solution i mentioned above.
2.  another solution i found mentioned [here](http://androiddev.orkitra.com/?p=3520) is to just take an id for the parent layout from the user and use that.
3.  finally, according to [this stackoverflow question](http://stackoverflow.com/questions/13895149/sliding-menu-locks-touch-event-on-upper-view) one can avoid this problem by subclassing a `SlidingActivity` directly.

thanks!

**Comment by jfeinstein10** [comment]
Fixed as per your solution above. Thanks!
