### ISSUE TITLE
Non smooth menu scrolling on Galaxy Nexus

### ISSUE THREAD

**Issue by gshockv** [jfeinstein10/SlidingMenu#2]
Hi! Thanks for great lib! We're using SlidingMenu to build our complex app. When app runs on Galaxy Nexus (stock Android 4.0.4 ROM) menu scrolls very very slow. On other devices (Samsung Galaxy SII, HTC Sensation, LG Optimus One) and emulators with Android 2.2, 2.3.x, 4.1 menu works good. Only Galaxy Nexus has a menu scrolling problem

**Comment by jfeinstein10** [comment]
You're welcome! :)
That's very strange. I've run this on my 4.0.4 Galaxy Nexus and it has worked fine. Could you send me some more details about this? Are both the above and behind view scrolling slowly? The best thing would be to post a video. Hopefully we can iron this out soon.

**Comment by gshockv** [comment]
Could you give me you email or send me empty email to gshockv@gmail.com and I'll send screenshots of my layouts (above and behind views)

**Comment by jfeinstein10** [comment]
jfeinstein10@gmail.com
This is super strange because I'm using my Galaxy Nexus to debug, and the phone in the YouTube video demo is also a Galaxy Nexus 4.0.4

**Comment by jfeinstein10** [comment]
I think I've seen this before. What is your min and target sdk versions as declared in your Manifest?

**Comment by gshockv** [comment]
uses-sdk android:minSdkVersion="8" android:targetSdkVersion="16"

**Comment by jfeinstein10** [comment]
Try targeting 14 and tell me what happens

**Comment by jfeinstein10** [comment]
Also, try running the example app in the repo and let me know if that has the same problem.

**Comment by jfeinstein10** [comment]
Any results?

**Comment by gshockv** [comment]
Sample project works very fine.
Targeting to 14 API level doesn't solve the problem. Removing "targetSdkVersion" attribute doesn't help also

**Comment by jfeinstein10** [comment]
Hmmm...
So the sample doesn't have this problem. I don't know what to tell you at this point; I'll need to sit down and do some thinking. But I'll be refactoring the underworkings of the SlidingMenu pretty soon, so hopefully that will clear your issue up.

If you want you can send me the relevant source code or package up an apk and send it to me so I can visualize what's going on better.

**Comment by jfeinstein10** [comment]
Any progress on this front?

**Comment by gshockv** [comment]
Yes! When I restyled view's backgrounds with solid colors (without patterns) everything works fine!

**Comment by jfeinstein10** [comment]
Awesome! Strange, but awesome.

**Comment by davidecaroselli** [comment]
Hi!

I would like to add my experience: I had the same problem but my layout was a little bit more complex (listviews inside  ViewPager and no SherlockActionBar). I had a terrible glitch on the background of the ViewPagerIndicator, and changing the background color didn't work.

I resolved the bug by setting android:targetSdkVersion to "14" (it was 8 as the minSdkVersion). I really don't know why.. but.. it worked! :)

Hope this could help somebody, bye!

**Comment by MoonlightMultimedia** [comment]
Setting android:targetSdkVersion to 14 also helped me fix these lag issues.

**Comment by tokudu** [comment]
Same worked for me. Thanks!

**Comment by M4rs** [comment]
Hi, thanks for great work firstly!
There are some complicated reason I must set the targetVersion to 9, is there any tip to make it smooth on 4.x device? (I have do some test, it was work fine on 2.x device).
Thanks again!
