### ISSUE TITLE
AndroidManifest.xml  seems not up to date

### ISSUE THREAD

**Issue by djerom** [jfeinstein10/SlidingMenu#202]
Hi,

Is the Android manifest up to date?

SlidingMenu / library / AndroidManifest.xml

Shouldn't the property android:name of the <activity> elements be ".app.<Activity>" instead of ".<Activity>"?

Btw, SlidingMapActivity doesn't exist.

**Comment by jfeinstein10** [comment]
Cleaned up. None of it was actually necessary.
