### ISSUE TITLE
Sliding Left and Right

### ISSUE THREAD

**Issue by kongsonida** [jfeinstein10/SlidingMenu#206]
Dear sir,

I would like to create two buttons on actionbar, and the button right is for sliding menu right and the button left is for sliding menu left.

Could you tell me what should I do?

Thanks,

**Comment by agarwlGaurav** [comment]
This question is a better fit on Stackoverflow.

**Comment by jfeinstein10** [comment]
See that one ^ and ActionBar.setCustomView(...) or inflate an Menu into it

**Comment by kongsonida** [comment]
I known the customview actionbar, but I want to put two action to menu button, when I click on button left, it will show sliding menu left, if I click on button right, it will show menu right.

Please help me.

**Comment by jfeinstein10** [comment]
This really isn't the place to ask this question. Please go to StackOverflow. Thanks.
