### ISSUE TITLE
error: Error: No resource found that matches the given name: attr 'homeAsUpIndicator'.

### ISSUE THREAD

**Issue by sdmdev** [jfeinstein10/SlidingMenu#209]
I tried and import in eclipse the example provided in the folder named  SlidingMenu\example but I get the following error: error: Error: No resource found that matches the given name: attr 'homeAsUpIndicator'.

Please do you know how to solve it? 
Thanks in advance

**Comment by agarwlGaurav** [comment]
It works and it is an implementation error. Please ask your question on Stackoverflow or Android Users Group.

**Comment by sdmdev** [comment]
thanks for your reply; I really didnt do anything but importing the example so how can it be an implementation error?

**Comment by agarwlGaurav** [comment]
Because I know it works. I only asked you to shift the question to more
appropriate forum.

Did you import ActionbarSherlock?

**Comment by sdmdev** [comment]
no, it's not an ActionbarSherlock issue. I downloaded the zip file for slidingMenu project. There is a library folder and there is a folder called "example". I thought it is an example for seeing it in action, so I imported it in eclipse and reproduced this error.

**Comment by sdmdev** [comment]
I just asked in stackoverflow with this title: "SlidingMenu example: issue in import to eclipse" thanks

**Comment by jfeinstein10** [comment]
This is absolutely an ActionBarSherlock related error. If you don't have SlidingMenu set up for use with it, then the example will not work.

**Comment by mjkohoh** [comment]
you should add ActionBarSherlock Project as libary.
And there are other problems you will face.Here are some way to solve these issues(http://www.cnblogs.com/jason_chen/p/3251328.html).
