### ISSUE TITLE
Need to setBehindContentView(...) in the ExampleActivity2

### ISSUE THREAD

**Issue by jerrellmardis** [jfeinstein10/SlidingMenu#21]
The ExampleActivity2 sample crashes. You need to setBehindContentView(R.layout.list) in the onCreate(...) method.

**Comment by jfeinstein10** [comment]
Oops. It was only supposed to be a FragmentActivity, not a SlidingFragmentActivity. Sorry about that. The example app is more like a sandbox for me right now. It'll have to go through a huge makeover at some point so you can demo all the features.
