### ISSUE TITLE
Content not visible when using two menus and the flag SLIDING_CONTENT

### ISSUE THREAD

**Issue by laurencedawson** [jfeinstein10/SlidingMenu#210]
When using two SlidingMenus with the flag SLIDING_CONTENT, the "content" is no longer visible. Using the flag SLIDING_WINDOW does not have this problem.

Any ideas for a workaround?

```
SlidingMenu menu_comments = new SlidingMenu(this);
menu_comments.setMode(SlidingMenu.RIGHT);
menu_comments.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);

SlidingMenu menu = new SlidingMenu(this);
menu.setMode(SlidingMenu.LEFT);
menu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);
```

**Comment by jfeinstein10** [comment]
Use SlidingMenu.LEFT_RIGHT mode; it was made for exactly this purpose. Don't use two nested inside each other because then the View hierarchy becomes a mess

**Comment by laurencedawson** [comment]
Totally missed that, thanks for the heads up!

Just on a side note, your library is going to be added to the next release of "reddit sync" as it''s 100x better than my current Dialog implementation :)

https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync

**Comment by jfeinstein10** [comment]
Oh awesome! I must say it's pretty good looking already

**Comment by laurencedawson** [comment]
Thanks :) It's a little basic mind.

I might be missing something, but is there a way to call setBehindWidthRes on the menu and secondary menu when using LEFT_RIGHT?

**Comment by jfeinstein10** [comment]
No, right now they're symmetrical. I'll probably add it later today

**Comment by laurencedawson** [comment]
Nice, thanks very much.
