### ISSUE TITLE
Menu size is not correct when rotating and having android:configChangtiones="orientation|keyboardHidden|screenSize"

### ISSUE THREAD

**Issue by cnordvik** [jfeinstein10/SlidingMenu#215]
How to reproduce: 
1. Add to the activity 
   android:configChanges="orientation|keyboardHidden|screenSize"
2. Rotate the screen
3. Slide open the menu

Result: 
The menu has the same width as in the previous screen orientation and is positioned wrong. 

Workaround (a bit hacky): 

``` java
@Override
    public void onConfigurationChanged(Configuration newConfig) {   
        super.onConfigurationChanged(newConfig);        
        mSlidingMenu.toggle();
        mSlidingMenu.toggle();
    }
```

Is there a better way of solving this than calling toggle twice? I hope so :-)

**Comment by kozko2001** [comment]
I found a better way to handle this.

just set the `menu.setBehindWith(menu_width)` which does a setWidthOffset on CustomViewBehind and this recalculates all the layout.

**Comment by jfeinstein10** [comment]
Yep, do that ^ :+1:
