### ISSUE TITLE
Changing Fragments not working locally

### ISSUE THREAD

**Issue by fliese** [jfeinstein10/SlidingMenu#217]
Hey, thank you for the great library! I've got a problem with the "Changing Fragments" example.

I downloaded the project from github, imported it in eclipse and took the steps that are described on https://github.com/jfeinstein10/SlidingMenu to set up ActionBarSherlock

When I run the sample project, the behavior of "Changing Fragments" (ColorFragment class) is not the same as in the play store. Sliding is only working on the action bar. When I try to slide below the action bar, nothing happens.

I figured out that the problem might be that ColorFragment.java doesn't return a view with an adapter on CreateView() .

The "ResponsiveUI" is working fine, but when I remove the GridAdapter class (which contains a getView() method), I'm getting the same behavior as the "Changing Fragments" example.

Most confusing is that "Changing Fragments" is working fine with the GooglePlay App Version.

I spent a lot of time with this issue and I don't know what I can do to solve it. Please help me!

**Comment by grivos** [comment]
From what I experienced, in order for swiping to work, the view must be clickable.
The ColorFragment's view isn't clickable, so you can add a new line after line 32 in ColorFragment.java and write:
v.setClickable(true);

Or, you can uncomment line 438 in CustomViewAbove,java

**Comment by jfeinstein10** [comment]
This has been fixed.
