### ISSUE TITLE
SlidingActivity changes visibility of onCreate from protected to public.

### ISSUE THREAD

**Issue by milesegan** [jfeinstein10/SlidingMenu#218]
Thanks for sharing SlidingMenu. It's been a huge time-saver.

Is there a reason that SlidingActivity increases the visibility of the onCreate method? It created a bunch of extra integration work because I had to edit all my activities to also expose onCreate as a public method.

**Comment by jfeinstein10** [comment]
The Activities will be phased out soon, so this won't be an issue

**Comment by yccheok** [comment]
Hi Jeremy Feinstein,

Thanks for the sliding menu library. When this ticket is closed, I expect SlidingActivity's and SlidingFragmentActivity's onCreate will fall back to "protected"? However, when I download the latest code, I realize they are still in "public". Is there any reason to have their visibility as "public"? 

Thanks.
