### ISSUE TITLE
Extend SlidingFragmentActivity from SherlockFragmentActivity

### ISSUE THREAD

**Issue by gshockv** [jfeinstein10/SlidingMenu#22]

**Comment by jfeinstein10** [comment]
What exactly does this mean/entail?

**Comment by gshockv** [comment]
We use SlidingFragmentActivity and in current state of lib we can't get access to actionBar (getSupportActionBar() method not exists)

**Comment by jfeinstein10** [comment]
All you have to do is check out a clean version of ABS. Add it as a dependency to the library and then make SlidingFragmentActivity extend SherlockFragmentActivity instead. This is not something that will be in the repository, but rather something you must set up on your own. We moved the project away from forcing an ABS dependency, but you can still use ABS like this. I'm actually doing this same process for one of my apps.

**Comment by gshockv** [comment]
Thanks! Exactly the same we did it
