### ISSUE TITLE
Don't work TouchMode for me

### ISSUE THREAD

**Issue by LPFinch** [jfeinstein10/SlidingMenu#221]
Problem with TouchMode, don't work enums FULLSCREEN and MARGIN. Have only NONE. Try to define SlidingMenu in xml. I can't slide my AboveView from Layout zone, only TitleBar and small square on TitleBar bottom (~15-20dp). If i change WindowFeature to Window.FEATURE_NO_TITLE catch no slide in my activity (not exception).
In Activity class have the same problem. 
SlidingMenu menu = new SlidingMenu(this);
menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN); don't work for me.

LogCat:
Layout square only have - CustomViewAbove(24612): Received ACTION_DOWN
TitleBar square - CustomViewAbove(24612): onInterceptTouch moved to:(61.0, 37.0), diff:(2.0, 0.0), mLastMotionX:63.0

UPD: have slide only on widget square, don't have on empty layout zone

**Comment by irwinb** [comment]
Doesn't work for me either.  Going to try and figure out why today..

**Comment by irwinb** [comment]
Until I figure out a better solution, adding android:clickable="true" to your activity's layout seems to make it work.

Also, CustomViewAbove:438 is commented out for some reason but when it's uncommented, everything works fine..with one caveat.  The system obviously makes clicking sound effects whenever you click.

```
//      mContent.setClickable(true);
```

**Comment by pandes** [comment]
Yes, uncommented CustomViewAbove:438 and it work fine.

thanks.

**Comment by cesards** [comment]
Same here. I solved the problem uncommenting the same line as both of you. I tryied using ScrollView in a layout, and it worked... (before I viewed this post...)

**Comment by irwinb** [comment]
The onTouchIntercept/onTouchEvent behaviour with ViewGroups/Views and their children is very complicated; going  to take some time to get a hang of it.

**Comment by jfeinstein10** [comment]
This was fixed this morning.
