### ISSUE TITLE
Hardware Layer Type Causes Display Issue

### ISSUE THREAD

**Issue by SteveEdson** [jfeinstein10/SlidingMenu#223]
Since the commit fa64e7aa52f1be9d2e9e051396f90197f4da7639, when I slide the menu on a device that supports hardware layers, the content has some weird issues.

As I slide the menu closed on a Nexus 4, the content that was previously off the screen, does not slide back in. Instead, it is blank/white. When the menu is fully closed, the layertype is set to `hardware? false`, and the content appears again.

A similar issue occurs on a HTC One X, but my view appears to gain padding at the top. Once again, when the menu is fully closed, the content returns to normal.

Let me know if you need me to explain it further, or provide images / video.

Thanks.

**Comment by SteveEdson** [comment]
Also, tested on a HTC Desire, the menu works as expected

**Comment by jfeinstein10** [comment]
Can you send me some screenshots / video so I can see what's going on here?

**Comment by SteveEdson** [comment]
I've done another pull and I'm still getting the issue. I've attached a video of the issue, the main view is a webview, and there is a list in the behind view. The issue only seems to occur when the the menu is sliding to the closed position from being fully open. Once fully closed, it goes back to normal.

Video:
http://cl.ly/MGYn

Image:
![Screenshot_2013-01-18-12-24-59](https://f.cloud.github.com/assets/1201960/78053/d3ec4dc8-616b-11e2-8e8b-2569226bb6e8.png)

**Comment by TonicArtos** [comment]
Is this an issue with something other than a WebView?

**Comment by ghost** [comment]
I guarantee the problem lies within the WebView -- it's awful with rendering in so many situations it isn't even funny.

**Comment by SteveEdson** [comment]
I'll have to check and update you, it was working absolutely fine prior to the commit mentioned though.

**Comment by jfeinstein10** [comment]
I would just comment out the hardware acceleration in the manageLayers method of SlidingMenu.
