### ISSUE TITLE
Google Maps API v2 content lags showing a black space on sliding close

### ISSUE THREAD

**Issue by d4tum** [jfeinstein10/SlidingMenu#228]
When sliding closed the window with a Google Maps API v2 it appears the map lags leaving a black space. I have tried all the fixes suggested in https://github.com/jfeinstein10/SlidingMenu/issues/168 wirh no success and have observed this behaviour on a Nexus S and Transformer Prime using Android 4.2.1 (cm 10.1)

This behaviour was apparent in 2 projects, my own app and another set up as simple as possible (commonsware's omnibus MapsV2 Basic Demo) both using ActionBarSherlock.

It appears as a white space using `GoogleMapOptions().zOrderOnTop(true)` setting from https://github.com/jfeinstein10/SlidingMenu/issues/168 

I have tried using the new API with another github project https://github.com/StevenRudenko/ActionsContentView and found the same result. This seems to be a problem with the new maps API, I'm not sure what can be done from SlidingMenu's end to assist this problem.
![Screen Shot 2013-01-13 at 3 29 13 PM](https://f.cloud.github.com/assets/243678/62598/ace32b14-5d3a-11e2-95c0-7b33c55eb56d.png)

**Comment by jfeinstein10** [comment]
And you set the background of your SurfaceView to transparent?

**Comment by d4tum** [comment]
I think so. Using `setMapTransparent()` from https://github.com/jfeinstein10/SlidingMenu/issues/168 resulted in the pic above.

Using `GoogleMapOptions().zOrderOnTop(true)` from https://github.com/jfeinstein10/SlidingMenu/issues/168 with the other sliding menu project (https://github.com/StevenRudenko/ActionsContentView) produced a transparent background with the lag described.

I can send you the simple project if you'd like.

**Comment by jfeinstein10** [comment]
Sure that'd be great. You can send the code as a zip to (jfeinstein10 at gmail dot com)

**Comment by Spiderbezno** [comment]
I had the problem from #168 and I solved it use the map:zOrderOnTop="true", now in version of Android  < Jelly bean work fine, but now I can't se the overlay objects as zoombuttons and other, those are drawer rear the map, you can click but you can't see them

**Comment by d4tum** [comment]
Spiderbenzo, I just completed a bug report for that problem, please star it http://code.google.com/p/gmaps-api-issues/issues/detail?id=4812

**Comment by micHar** [comment]
I can confirm that problem on HTC One S. Strange thing though - the flickering of black background appears when I open the menu (with finger or with showMenu()), but when I close it, it's okay. I tried both zOrderOnTop and transparent background (and also a transparent foreground - http://stackoverflow.com/a/13993640/1118475). zOrderOnTop seems to work better, but it's probably because the flickering background is light instead of black (don't know why). But still, it's not very satisfactory and has the downside - you cannot overlay anything on the map.

You can see the issue on this video: http://youtu.be/qSBuFqMliJM

Also, I posted a stackoverflow question: http://stackoverflow.com/questions/14419521/moving-surfaceview-mapfragment-causes-black-background-flickering

**Comment by d4tum** [comment]
micHar, what you have in the YouTube video is exactly what I'm getting. I too am unable to compromise with zOrderOnTop(true) because I need the UI overlay elements as well as it doesn't alleviate the problem, but makes the black flicker a white one. 

In reply to your SO post idea (I've copied the rest of this paragraph there), the map will continue to process commands and animate as it is sliding. This is a good UX. Taking a screen shot to cover the map while it slides will detract from that UX and AFAIK, it's not possible, see http://stackoverflow.com/questions/13773658/capture-screen-shot-of-googlemap-android-api-v2

Jeremy, this may (or may not) be helpful http://stackoverflow.com/a/13840490/496625

**Comment by micHar** [comment]
I know that my idea was w terrible hack, but it sucks that it can't be done, anyway. I just hope that someone could take it from there and come up with something better.

I tried to refresh the visibility while the menu was sliding (based on the same SO post), but it didn't work for me. But maybe I've done it wrong, because it seems like it may work. Unfortunately I don't have the code, because I tried dozens of other solutions after that. And also the responder didn't mention if he only got rid of the black background or also the flickering/lag.

Btw, did you try to do it without actionbarsherlock and support library? I doubt it would change anything, but asking doesn't hurt ;)

**Comment by d4tum** [comment]
You know, trying without ABS is about the only thing I haven't tried. I'll give it a shot soon, let us know how you go if you beat me to it.

UPDATE: Just tried w/o ABS and the results were the same as with ABS. Note that android-support-v4.jar was still used.

**Comment by micHar** [comment]
It would probably be useful to make a sample project with normal MapFragment and a ViewPager instead of SlidingMenu. I'm pretty sure the lag would still be there. I have my finals this week, but after I finish them, I'll try to do it. Maybe someone will solve it till then

**Comment by micHar** [comment]
Just realised that if it was placed inside TextureView instead of SurfaceView, there would be no problem...

http://android-developers.blogspot.com/2011/11/android-40-graphics-and-animations.html

Maybe they'll change it.

**Comment by MSch** [comment]
Yeah we're having the same problem. Did anyone find a workaround that keeps the overlay objects visible?

**Comment by d4tum** [comment]
Hi MSch,
Looks like it just can't be done. See post number 3 here -
http://code.google.com/p/gmaps-api-issues/issues/detail?id=4812

**Comment by micHar** [comment]
And setZOrder doesn't really work too...

They really screwed it... I can think of hundreds of app where the map should be moved around, yet it's not possible with this implementation. All that should be done is to change it to use TextureView. I wonder what is the reason not to do it - performance?

**Comment by d4tum** [comment]
I really think Cyril Mottier nails it in the second last paragraph of this article of his http://android.cyrilmottier.com/?p=855
This version of the new maps really seems like a beta and quite rushed. I hope Google are listening to the monstrous amounts of negative feedback and as you suggest micHar, move to a TextureView implementation.

**Comment by MSch** [comment]
Would it be possible to take a screenshot of the view, then animate this, then replace the static image with the view again? That's how I'd do it on iOS.

@qubz Oh wow that sounds bad :/ I just started out switching from v1 to v2. Would you recommend against doing that? Based on the linked blog I should just keep v1.

**Comment by jendib** [comment]
@MSch You should stick to v1 for the moment, I've upgraded my app to v2, and I get tons of crash reports with out of memory error, because of a bad caching technique, only fixed in the next Maps version.

**Comment by MSch** [comment]
@benj69 Thanks! I'll just switch from v1+my custom hacks to v1+Polaris. Didn't even know that existed.

**Comment by micHar** [comment]
As to "Would it be possible to take a screenshot of the view, then animate this, then replace the static image with the view again? That's how I'd do it on iOS." - unfortunately not, see my stackoverflow question or read all comments here, I thought about it too.

As to TextureView - unfortunately it's not present in the Support Package, so no pre-ICS implementations would be possible. I think we just have to wait...

**Comment by chose007** [comment]
I would like to ask you jfeinstein10 if it would be somehow possible not to scroll the above view at all, but only let the behind view scroll "over" the above view when opening the menu (well, I understand that the behing view would have to be actually "above" the above view to do something like that). 

I know it would look a little weird (especially when combining the two approaches in a single app) but as far as I can see - there is no truly working workaround which would handle the problem with maps v2. So I would rather not move the map at all when opening/closing the menu to just completely avoid these problems.

**Comment by d4tum** [comment]
@chose007 If you're looking for something like that, perhaps try https://github.com/johnkil/SideNavigation I have it working as you described but won't use it in my product because I'd prefer to use SlidingMenu. I and many others are waiting to see what the update to maps v2 API brings in regard to a possible solution to using SlidingMenu.

**Comment by d4tum** [comment]
On a side note, anyone having issues with maps flickering with SlidingMenu needs to star this issue http://code.google.com/p/gmaps-api-issues/issues/detail?id=4659 to increase the chance of it being fixed.

I'm closing this issue as it seems the problem is really with Google Maps for Android v2 and not SlidingMenu. If anyone is able to prove otherwise, I'll re-open it.

**Comment by ghost** [comment]
The workaround that worked for me is to add a transparent view above the map in menu onOpen and then remove it in menu onClose.

getSlidingMenu().setOnOpenListener(new OnOpenListener() {
public void onOpen() {
View dummyView = (View)findViewById(R.id.dummy_view);
dummyView.setVisibility(View.VISIBLE);
}
});

```
getSlidingMenu().setOnCloseListener(new OnCloseListener() {
     public void onClose(){
         View dummyView = (View)findViewById(R.id.dummy_view);
         dummyView.setVisibility(View.GONE);
        }
});
```

**Comment by d4tum** [comment]
@jsbonin 
Thank you for the suggestion. I remember trying this as suggested from issues #168 when I first encountered this problem with no success. I just gave it another shot and it still does not solve this problem.

**Comment by veelck** [comment]
Thing with black space seems to be not only the problem with GMaps V2, but with Android's GLSurfaceView (and I suppose, that they are using it for maps, since they are drawn with native GL as far as I'm aware).

Anyway, using any GLSurfaceView and the drawer causes black border to appear during animation.
I was trying to figure out problem with maps, that I also had, so I put transparent GLSurfaceView on top of MapView (v2), something like that:

```
public class SurfacePanel extends GLSurfaceView {

    private class MyRenderer implements GLSurfaceView.Renderer {

        @Override
        public void onSurfaceCreated(GL10 gl, EGLConfig config) {
        }

        @Override
        public void onSurfaceChanged(GL10 gl, int width, int height) {
            gl.glViewport(0, 0, width, height);
        }

        @Override
        public void onDrawFrame(GL10 gl) {
            gl.glClearColor(1f, 1f, 1f, 0f);
            gl.glClear(GL10.GL_COLOR_BUFFER_BIT | GL10.GL_DEPTH_BUFFER_BIT);
            gl.glFlush();
        }
    }

    private Animation invisibleAnim;

    public SurfacePanel(Context ctx, AttributeSet attrSet) {
        super(ctx, attrSet);
        setEGLConfigChooser(8, 8, 8, 8, 16, 0);
        getHolder().setFormat(PixelFormat.TRANSLUCENT);
        setRenderer(new MyRenderer());
        invisibleAnim = AnimationUtils.loadAnimation(ctx, R.anim.set_invisible);
    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        startAnimation(invisibleAnim);
        super.surfaceCreated(holder);
    }
}
```

Animation res:

```
<?xml version="1.0" encoding="utf-8"?>
<alpha xmlns:android="http://schemas.android.com/apk/res/android"
    android:fromAlpha="0.0"
    android:toAlpha="0.0"
    android:duration="0"
    android:fillAfter="true"/>
```

The animation is there just to fix problem with setting alpha for the Window (it seems, that window object that is used for GLSurfaceView is black).

This hack makes the whole thing a bit better, but it's still not perfect, especially on older and slower devices.

**\* some totally random insights
From my perspective (I have no arguments for this, just my thoughts on the topic, so I might be totally off) the problem here is lack of sync between GL rendering thread and Android UI thread - due to some attempts on animation fixes, the window behind GLSurfaceView becomes visible.
If that's the case, there is no easy fix for the problem, so we will have to live with it... :(

@qubz thanks for the link to SideNavigation - I think I will use that instead, since having the map moving with black border etc. is unacceptable :(

**Comment by salmanansari** [comment]
Hey everyone, I found a solution. Check this out!

LinearLayout mView = (LinearLayout) findViewById(R.id.mapView); //MapContainer
        FragmentManager fm = getSupportFragmentManager();
        supportFragment = new MySupportMapFragment(); //or you can use 
        FragmentTransaction ftrans = fm.beginTransaction();
        ftrans.add(mView.getId(), supportFragment);
        ftrans.addToBackStack(null);
        ftrans.commit();

-----------------MySupportMapFragment class---------------------------

public class MySupportMapFragment extends SupportMapFragment 
{
    private View v;
    private LinearLayout ll;
    private TouchableWrapper mTouchView;

```
public MySupportMapFragment()
{
    // TODO Auto-generated constructor stub
    super();
}

@Override
public View onCreateView(LayoutInflater arg0, ViewGroup arg1, Bundle arg2)
{
    // Log.d(TAG, "In overridden onCreateView.");
    LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.WRAP_CONTENT, 550);
    params.setMargins(10, 10, 10, 0);
    ll = new LinearLayout(arg1.getContext());
    v = super.onCreateView(arg0, arg1, arg2);
    ll.addView(v, params);
    setMapTransparent((ViewGroup) v);
    initMap();
    return ll;
}

private void setMapTransparent(ViewGroup group) 
{
    int childCount = group.getChildCount();
    for (int i = 0; i < childCount; i++) 
    {
        View child = group.getChildAt(i);

        if (child instanceof ViewGroup)
        {
            setMapTransparent((ViewGroup) child);
        } 
        else if (child instanceof SurfaceView) 
        {
            child.setBackgroundColor(0x00000000);
            ((SurfaceView) child).setZOrderOnTop(true);
        }
    }
}

private void initMap() 
{
    UiSettings settings = getMap().getUiSettings();
    // settings.setAllGesturesEnabled(true);
    settings.setMyLocationButtonEnabled(true);
    LatLng latLong = new LatLng(22.320542, 114.185715);
    getMap().moveCamera(CameraUpdateFactory.newLatLngZoom(latLong, 11));
    Marker hamburg = getMap().addMarker(
            new MarkerOptions().position(RegionalActivity.HAMBURG).title(
                    "Hamburg"));

    // Move the camera instantly to hamburg with a zoom of 15.
    getMap().moveCamera(
            CameraUpdateFactory.newLatLngZoom(RegionalActivity.HAMBURG, 15));
}
```

**Comment by umertech** [comment]
Use SlidingMenu.setbackgroundResource it will cover the black space between views and use background as slidingmenu.set background

Remove background of your left and right menus. it will work like a charm

**Comment by drorg** [comment]
I don't have background in the manu layout...
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<include
    android:id="@+id/serach"
    layout="@layout/search_box" />

<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_below="@+id/serach"
    android:background="@color/menu_item_bg" >

    <ExpandableListView
        android:id="@+id/menu_list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentRight="true"
        android:childDivider="@color/black"
        android:childIndicator="@null"
        android:choiceMode="singleChoice"
        android:divider="@color/black"
        android:dividerHeight="1dp"
        android:groupIndicator="@null"
        android:listSelector="@drawable/menu_group_item_selected_gradient" >
    </ExpandableListView>

</RelativeLayout>
```

</RelativeLayout>

and i n the code:
                menu.setBehindOffset(menuOffset);
        menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_MARGIN);
        menu.setFadeEnabled(true);
        menu.setFadeDegree(0.5f);
        menu.attachToActivity(activity, SlidingMenu.SLIDING_CONTENT);
        menu.setBehindScrollScale(0);
        menu.setMenu(R.layout.menu_layout);

**Comment by jamescarter143** [comment]
That sounds like a really interesting episode! The science of cryptids always sparks curiosity, mysterious and legendary creatures have been part of human imagination for centuries. If you enjoy exploring curious topics and testing your skills online, you can check out https://testartecladoonline.com.br/ while listening to the episode.

**Comment by yao2923828** [comment]
收到

**Comment by john585491** [comment]
Angel’s Pizza features the latest pizzas, pasta, chicken, rice meals, desserts, beverages, and value deals at updated prices. Made fresh, baked to perfection, and affordably priced, every meal is crafted to satisfy every craving. Explore the complete **[Angel’s Pizza](https://angelspizzamenus.com/)** menu and enjoy your favorite flavors through dine-in, takeaway, or delivery anywhere in the Philippines.

**Comment by yao2923828** [comment]
收到

**Comment by john585491** [comment]
Amber Menu Golden Chain restaurant is located in the bustling streets of Malina. It offers an inviting charm to locals and travelers alike. Filipino dishes are prepared expertly in the bustling kitchen. [Amber](ambermenus.com) is known for its commitment to excellence in both food and service. Its dasma menu has earned a reputation as a great gem, where every meal is a delightful journey through the flavor of this vibrant archipelago.

**Comment by john585491** [comment]
Chowking Menu Philippines (Update 2026) is the most complete, verified, and regularly updated guide to Chowking’s latest  food offerings nationwide.This page covers official menu items, updated prices, meal sets, add ons, calories, allergens, and nutritional information based on the most recent available data from [Chowking Menu](chowkingmenus.com) With Price Philippines and in store listings.

**Comment by anime585** [comment]
[Study Point](https://www.studypoint.pk/) helps students across worldwide to prepare smarter with free short notes, guess papers, model papers, past papers, textbooks, and the latest board results, all matched to your board and syllabus.

**Comment by anime585** [comment]
An [area code](https://www.areascode.us/) is a three-digit number used in telephone systems to identify a specific geographic region. It is part of the North American Numbering Plan (NANP) and helps route phone calls to the correct destination.

**Comment by alexajames122** [comment]
Cyberify is an AI technology company that helps businesses improve their daily work through smart AI solutions. [Cyberify](https://www.cyberify.co/) provides AI tools for real estate, automation, customer support, and business operations to save time and improve efficiency.

**Comment by yao2923828** [comment]
收到
