### ISSUE TITLE
How to get Responsive UI example code?

### ISSUE THREAD

**Issue by LPFinch** [jfeinstein10/SlidingMenu#229]
I need to build my app with functionality like Responsive UI from SlidingMenu Demos in Google Play. 
When list item on behindview was clicked, aboveview must slide automatically with new adapter for my aboveview activity list.
Thanks.

**Comment by fliese** [comment]
just check it out via git. here you can see the class: https://github.com/jfeinstein10/SlidingMenu/blob/master/example/src/com/slidingmenu/example/fragments/ResponsiveUIActivity.java

**Comment by LPFinch** [comment]
Thanks,just my fault, I didn't see.
