### ISSUE TITLE
Error while adding Library to project

### ISSUE THREAD

**Issue by ManojMM026** [jfeinstein10/SlidingMenu#230]
![Error](https://f.cloud.github.com/assets/2713390/64425/508e5164-5e47-11e2-8061-4214c1e2ff42.png)

please show me  how to import this library into project?

**Comment by kenyee** [comment]
What's the error?

What I found is that you have to choose the Google APIs or it'd put up errors about not finding MapActivity.  You can't just select Android 4.1.2.  This probably belongs in the FAQ...
The "Is Library" Checkbox should also be checked...

**Comment by jwoolston** [comment]
If the properties window in the picture is for the project he is adding the library to then the checkbox should not be selected. I also need to use google api's, but I do that on the project I have the library in. Judging from what I see eclipse cannot find the project at the specified path, which means you have done something wrong in importing the library to eclipse.
