### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by NitinBathija** [jfeinstein10/SlidingMenu#232]
Getting the error at the time of launching the activity

02-05 14:12:50.024: E/AndroidRuntime(1072): FATAL EXCEPTION: main
02-05 14:12:50.024: E/AndroidRuntime(1072): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.slidingdrawerexample/com.example.slidingdrawerexample.MainActivity}: android.view.InflateException: Binary XML file line #14: Error inflating class com.slidingmenu.lib.SlidingMenu
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.ActivityThread.access$600(ActivityThread.java:123)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.os.Handler.dispatchMessage(Handler.java:99)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.os.Looper.loop(Looper.java:137)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.ActivityThread.main(ActivityThread.java:4424)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at java.lang.reflect.Method.invokeNative(Native Method)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at java.lang.reflect.Method.invoke(Method.java:511)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at dalvik.system.NativeStart.main(Native Method)
02-05 14:12:50.024: E/AndroidRuntime(1072): Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.slidingmenu.lib.SlidingMenu
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createView(LayoutInflater.java:606)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:268)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.Activity.setContentView(Activity.java:1835)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.example.slidingdrawerexample.MainActivity.onCreate(MainActivity.java:16)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.Activity.performCreate(Activity.java:4465)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
02-05 14:12:50.024: E/AndroidRuntime(1072):     ... 11 more
02-05 14:12:50.024: E/AndroidRuntime(1072): Caused by: java.lang.reflect.InvocationTargetException
02-05 14:12:50.024: E/AndroidRuntime(1072):     at java.lang.reflect.Constructor.constructNative(Native Method)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createView(LayoutInflater.java:586)
02-05 14:12:50.024: E/AndroidRuntime(1072):     ... 22 more
02-05 14:12:50.024: E/AndroidRuntime(1072): Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class <unknown>
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createView(LayoutInflater.java:606)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.slidingmenu.lib.SlidingMenu.setContent(SlidingMenu.java:342)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:235)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:190)
02-05 14:12:50.024: E/AndroidRuntime(1072):     ... 25 more
02-05 14:12:50.024: E/AndroidRuntime(1072): Caused by: java.lang.reflect.InvocationTargetException
02-05 14:12:50.024: E/AndroidRuntime(1072):     at java.lang.reflect.Constructor.constructNative(Native Method)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createView(LayoutInflater.java:586)
02-05 14:12:50.024: E/AndroidRuntime(1072):     ... 33 more
02-05 14:12:50.024: E/AndroidRuntime(1072): Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class <unknown>
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createView(LayoutInflater.java:606)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.slidingmenu.lib.SlidingMenu.setContent(SlidingMenu.java:342)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:235)
02-05 14:12:50.024: E/AndroidRuntime(1072):     at com.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:190)
02-05 14:12:50.024: E/AndroidRuntime(1072):     ... 36 more
02-05 14:12:50.024: E/AndroidRuntime(1072): Caused by: java.lang.reflect.InvocationTargetException
02-05 14:12:50.024: E/AndroidRuntime(1072):

**Comment by jfeinstein10** [comment]
From what it looks like, it's having trouble inflating on of your layouts. Specifically the one that you're using as the content
