### ISSUE TITLE
TOUCHMODE_FULLSCREEN is not really fullscreen

### ISSUE THREAD

**Issue by ababicheva** [jfeinstein10/SlidingMenu#233]
With TOUCHMODE_FULLSCREEN if I try to drag area that not an Action Bar and nothing happened. I research this issue and found that since this commit: https://github.com/jfeinstein10/SlidingMenu/commit/6ca0c5e1e5067a29aa64408bb2d6d62fe0a726bb strings:

if (!mIsBeingDragged && !thisTouchAllowed(ev))
return false;

replaced with:

if (!mIsBeingDragged && !mQuickReturn)
return false;

If I comment last two and uncomment first strings, area that is not an Action Bar, all works fine.

**Comment by jfeinstein10** [comment]
Thank you for finding this! I'll be working on it and should send out a fix later

**Comment by jfeinstein10** [comment]
Committed. Thanks a lot again.
