### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by jcar787** [jfeinstein10/SlidingMenu#234]
Is not an issue is only an advice. Will be nice if you made a step by step tutorial on this, Starting with something very simplistic. Thanks for the library though.

**Comment by jfeinstein10** [comment]
Do you think the README file not enough?

**Comment by jwoolston** [comment]
I would add that the only thing I find missing is that I have had some troubles importing the library as a library project in eclipse while preserving its GIT connection. The simple "add project from git" doesnt seem to load the correct info

**Comment by jfeinstein10** [comment]
Are you using the Git plugin? I would recommend against that. Doing a straight clone and then "import as existing project" works perfectly

**Comment by jcar787** [comment]
No. The README file is not enough.

**Comment by jwoolston** [comment]
No I have a fork of your library for our company and i tried importing from a git repository. I just had to replace all my java/eclipse stuff trying to fix a compile problem with GAE that isn't doing what the fixes say it should so I'll try doing it that way.

**Comment by jfeinstein10** [comment]
@blackone787 a little terse are we? If you'd like help, I'd be happy to help; you sound fairly frustrated.

**Comment by jwoolston** [comment]
When you say existing project, are you using the general, or the android?

**Comment by jfeinstein10** [comment]
The general one

**Comment by jcar787** [comment]
Im not terse lol. Somethings I do not understand. If I understand them I will be happy to wrote a tutorial.

**Comment by jwoolston** [comment]
Ok I got it. Im not sure if I had a bad file or something but the project wasnt showing up in library for me. Thanks, it works as I expected so Im sure it was something messed up on my computer.

**Comment by TonicArtos** [comment]
The example is quite illustrative.

**Comment by Quasaur** [comment]
not for a beginner like me.

**Comment by chamikarazin** [comment]
This will help for beginners 
http://stackoverflow.com/questions/14057367/exact-procedure-to-add-jfeinstein10-slidingmenu-in-android-project

**Comment by jcar787** [comment]
Good tutorial! Going to close this thread!
