### ISSUE TITLE
The second sliding menu, has the same layout as the first, and also, the buttons from the layout does not work.

### ISSUE THREAD

**Issue by RosuAlin** [jfeinstein10/SlidingMenu#236]
If i use only one slidingmenu, and from my button use menu.toggle(); the application works.
If i try to use 2 menus, with 2 buttons, it does not work, they both show me the first sliding menu, and neither have no response.
My first button does this: menu.showMenu();
second button:  menu.showSecondaryMenu();

This is my code:
FragmentTransaction t = this.getSupportFragmentManager().beginTransaction();
        menu = new SlidingMenu(this);
        menu.setMode(SlidingMenu.RIGHT);
        menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_NONE);
        menu.setShadowWidthRes(R.dimen.shadow_width);
        menu.setShadowDrawable(R.drawable.shadow);
        menu.setBehindOffsetRes(R.dimen.slidingmenu_offset);
        menu.setFadeDegree(0.35f);
        menu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);
        menu.setMenu(R.layout.tutorial_layout);
        rightSlide = new HelpFragment();
        t.replace(R.id.slidingList2, rightSlide);
        t.commit();
        t = this.getSupportFragmentManager().beginTransaction();
        menu.setSecondaryMenu(R.layout.log_history);
        leftSlide = new LogHistory();
        t.replace(R.id.loghistorycon, leftSlide);
        t.commit();

What am I missing over here?

**Comment by jfeinstein10** [comment]
You have to call set mode(SlidingMenu.LEFT_RIGHT) if you want both.
