### ISSUE TITLE
Latest updates break overlay actionbar

### ISSUE THREAD

**Issue by jwoolston** [jfeinstein10/SlidingMenu#239]
Somewhere from commit fa64e7aa52f1be9d2e9e051396f90197f4da7639 the overlay of action bars seems to have stopped working, going back to the behavior it had before. If the actionbar is set to overlay in the theme, even with using the new overlay attachToActivity the content is drawn over the actionbar.

**Comment by jwoolston** [comment]
Forgot to mention, this is for SLIDING_CONTENT

**Comment by jwoolston** [comment]
This is due to a change in attachToActivity(Activity, int, boolean) for the SLIDING_CONTENT case. The fix that was made for the overlay has been commented out. @jfeinstein10, I'm sure this was because of something you were working on, was this an unforseen side effect?

**Comment by jfeinstein10** [comment]
Fixed again. Sorry about that.

**Comment by jwoolston** [comment]
No worries. Thanks for keeping on things, its lets me focus on our app's features rather than UI details and I really appreciate it.

**Comment by doridori** [comment]
I am having this issue from a clone two weeks ago - has it crept back in?
