### ISSUE TITLE
View pager integration

### ISSUE THREAD

**Issue by jwoolston** [jfeinstein10/SlidingMenu#240]
I know I can use ViewPager and SlidingMenu together, but this imposes some view hierarchy that I would prefer to ignore, especially given the similarities in how ViewPager and SlidingMenu work, so I was considering trying to extend SlidingMenu for this purpose so I have two questions...
1. Is this something that it can already do and I am just missing it? Near as I can tell SlidingMenu expects no more than 3 children in the ViewGroup
2. Is this something you are already working on?

**Comment by jfeinstein10** [comment]
1. You are correct here, it will have at most 3 children.
2. Nope, I am not going to work on this because it is inconsistent with the UI pattern. See the ViewPager example activity

**Comment by jwoolston** [comment]
Got it.
