### ISSUE TITLE
(CustomViewAbove.java:811)java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by feng88724** [jfeinstein10/SlidingMenu#243]
01-17 10:16:23.381: E/AndroidRuntime(15904): FATAL EXCEPTION: main
01-17 10:16:23.381: E/AndroidRuntime(15904): java.lang.ArrayIndexOutOfBoundsException
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1385)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.drawChild(ViewGroup.java:1666)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1387)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.drawChild(ViewGroup.java:1666)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1387)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.drawChild(ViewGroup.java:1666)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1387)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.View.draw(View.java:6904)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.drawChild(ViewGroup.java:1668)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1387)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:811)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.View.draw(View.java:6904)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.drawChild(ViewGroup.java:1668)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1387)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.drawChild(ViewGroup.java:1666)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1387)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.View.draw(View.java:6904)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1967)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewRoot.draw(ViewRoot.java:1536)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewRoot.performTraversals(ViewRoot.java:1260)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1873)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.os.Handler.dispatchMessage(Handler.java:99)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.os.Looper.loop(Looper.java:130)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at android.app.ActivityThread.main(ActivityThread.java:3703)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at java.lang.reflect.Method.invokeNative(Native Method)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at java.lang.reflect.Method.invoke(Method.java:507)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
01-17 10:16:23.381: E/AndroidRuntime(15904):    at dalvik.system.NativeStart.main(Native Method)

**Comment by jfeinstein10** [comment]
I'm 90% sure this has something to do with one of your views nested inside the SlidingMenu and not the SlidingMenu itself.
