### ISSUE TITLE
using  toggle()

### ISSUE THREAD

**Issue by akkawi** [jfeinstein10/SlidingMenu#245]
hi there, Im using the slidingmenu with  getSlidingMenu().setMode(SlidingMenu.LEFT_RIGHT);

i can drag per Finger lfet and right which is working perfect,

now here comes my problem .. im using this to toggle the menu when clicking on the home button :
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
        case android.R.id.home:
            if(getSlidingMenu().isMenuShowing())  
                getSlidingMenu().toggle();
            else
                getSlidingMenu().toggle();
        }
        return true;
    }

as known toggle will show and hide the menu, BUT only the left side ..
now i would like to use another button i added on the top right of the actionbar to toggle the right side of the menu. i thought maybe toggle(left) toggle(right) would be a solution but it is not implemented, so how to make the right menu appear when clicking on a XXX button.

thanks alo, a great menu.

**Comment by jfeinstein10** [comment]
showSecondaryMenu()

**Comment by akkawi** [comment]
thank you. i dunno how i missed that !.

**Comment by ghost** [comment]
Thank you **Jeremy Feinstein** , You have made my app development easier :smile:

**Comment by Bhavdip** [comment]
Thank you for the help.
