### ISSUE TITLE
mContent.getActivity().findViewById returns null

### ISSUE THREAD

**Issue by bmarwa** [jfeinstein10/SlidingMenu#247]
I am trying to get a ListView from a view switched in the Fragment.

After switching the content in R.id.content_frame, I cannot access the controls in the view.

I have tried the :
1. ListView selectListView = (ListView) findViewById(R.id.SelectllistView);  
2.  ListView selectListView = (ListView) mContent.getView().findViewById(R.id.SelectllistView);  

public void switchContent(final Fragment fragment) {
        mContent = fragment;
        getSupportFragmentManager()
        .beginTransaction()
        .replace(R.id.content_frame, fragment)
        .commit();
        Handler h = new Handler();
        h.postDelayed(new Runnable() {
            public void run() {
                getSlidingMenu().showContent();
            }
        }, 50);
    }

**Comment by jfeinstein10** [comment]
Why don't you call fragment.getView()...?
