### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in MotionEvent.getX

### ISSUE THREAD

**Issue by alexzaitsev** [jfeinstein10/SlidingMenu#248]
I just have several fragments and after a couple fragment replacing and screen rotations I get:

01-19 10:41:49.431: E/AndroidRuntime(6329): FATAL EXCEPTION: main
01-19 10:41:49.431: E/AndroidRuntime(6329): java.lang.ArrayIndexOutOfBoundsException
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.view.MotionEvent.getX(MotionEvent.java:972)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at com.slidingmenu.lib.CustomViewAbove.onInterceptTouchEvent(CustomViewAbove.java:640)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:960)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1820)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1176)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.app.Activity.dispatchTouchEvent(Activity.java:2198)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1795)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2336)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1976)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.os.Looper.loop(Looper.java:150)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at android.app.ActivityThread.main(ActivityThread.java:4277)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at java.lang.reflect.Method.invokeNative(Native Method)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at java.lang.reflect.Method.invoke(Method.java:507)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
01-19 10:41:49.431: E/AndroidRuntime(6329):     at dalvik.system.NativeStart.main(Native Method)

Any idea how to solve?

**Comment by jfeinstein10** [comment]
Fix for this rolling out soon.
