### ISSUE TITLE
Robo compatibility

### ISSUE THREAD

**Issue by pauldatta** [jfeinstein10/SlidingMenu#249]
I came across https://github.com/jfeinstein10/SlidingMenu/pull/33 which includes [this](https://github.com/oliver-snowden-hpa/SlidingMenu/blob/0d275694195ab94406e3378f9e0fdd63926ef4df/library/src/com/slidingmenu/lib/app/RoboSlidingFragmentActivity.java) RoboSlidingFragmentActivity.
Any plans of making SlidingMenu Robo compatible?

**Comment by aldoborrero** [comment]
I would like to see this implemented too!

**Comment by jondwillis** [comment]
+1

**Comment by jfeinstein10** [comment]
I don't use Robo so it's not something that I can do and it's pretty low down on the list in terms of my priorities. If somebody wants to take it up themselves, I'd be happy to merge it. I wouldn't start for a while because I'll be rolling out major changes soon.
