### ISSUE TITLE
Lib compatible with v4?

### ISSUE THREAD

**Issue by ehrior** [jfeinstein10/SlidingMenu#25]
Last version of this lib is compatible with lib v13 of Android, but not with v4. So, does it mean that I can't use it for Android 2.2 and 2.3.x? 
How can I fix it? I tried to import v4, but I can't delete v13, so I still have some problems with getSupportActionBar()

**Comment by jfeinstein10** [comment]
v13 contains v4. All of your imports should be fine, you just can't have both at the same time.

**Comment by ehrior** [comment]
Thank you.
