### ISSUE TITLE
Easy Noon Prob Importing Mavenized ABS

### ISSUE THREAD

**Issue by Quasaur** [jfeinstein10/SlidingMenu#251]
I'm running NetBeans 7.2.1.
I successfully built com.slidingmenu.lib.
I successfully built ABS.
NetBeans won't let me add ABS as a dependency to com.slidingmenu.example because NetBeans doesn't recognize ABS as an Android library.
Please help...I'll be your friend!

**Comment by jfeinstein10** [comment]
This is not the right place for this. Go a ask this on StackOverflow. Sorry.
