### ISSUE TITLE
touchModeBehind with Fullscreen is unusable.

### ISSUE THREAD

**Issue by viveksoneja28** [jfeinstein10/SlidingMenu#254]
If you set touchModeBehind as FullScreen, it works on full screen but all other buttons or clickable views on menu becomes unusable ie it cant be clicked. This does not seems to be the desired behavior.

Kindly help with how to resolve the same.

**Comment by jfeinstein10** [comment]
Don't use it for now. It doesn't work.

**Comment by singggum3b** [comment]
The touch event need to be dispatch from top layer down.Just delegate it.I forgot which class :|
