### ISSUE TITLE
Question: Sliding Menu won't click

### ISSUE THREAD

**Issue by devslash-paul** [jfeinstein10/SlidingMenu#255]
Hi, 
When i implement the example with the code:
                SlidingMenu slide = new SlidingMenu(this, SlidingMenu.SLIDING_CONTENT);

```
    slide.setMode(SlidingMenu.LEFT);
    slide.setTouchModeAbove(SlidingMenu.TOUCHMODE_MARGIN);
    slide.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
    slide.setBehindOffset(150);
    slide.setFadeDegree(0.3f);
    slide.setShadowWidth(5);
    slide.setOnClickListener(this);




    slide.setMenu(R.layout.simpleframelayout);


    getSupportActionBar().setDisplayHomeAsUpEnabled(true);

    getSupportFragmentManager()
    .beginTransaction()
    .replace(R.id.simpleframelayoutID, new SampleListFragment())
    .commit();
```

Where this is in a SherlockFragmentActivity. Unfortunately though, the menu will slide across but it is impossible to click any item. The fragment looks like this:

```
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.ListFragment;
import android.widget.ArrayAdapter;

public class SampleListFragment extends ListFragment {

@Override
public void onCreate(Bundle savedInstanceState) {
    // TODO Auto-generated method stub
    super.onCreate(savedInstanceState);
    ArrayAdapter<String> titles = new ArrayAdapter<String>(getActivity(), 
            android.R.layout.simple_list_item_1, new String[]{"test","test2"});
    setListAdapter(titles);
}

}
```

So, am i missing something or is this some bug i'm not aware of?

**Comment by princeobi007** [comment]
have you tried overriding onActivity created in your sample list fragment.. you should read more articles on fragments and listviews

**Comment by JesseFarebro** [comment]
Same problem here, doesn't matter what I do the ListView items cannot be clicked! Tried reading up on this for two whole days. Its not a focusability issue I can deny focus to all children of the ListView and the row still won't respond to any click events.

**Comment by laaptu** [comment]
The main reason behind this is due to 
 slide.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
 and if you do
 slide.setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);
  it works.
But I think there is better workaround for it

**Comment by voltazor** [comment]
I have the same problem.

I set the "BehindOffset" parameter like that:
   <code>slide.setBehindOffset(0);</code>
So my sliding menu fill the entire screen. 

When "TouchModeBehind" parameter setted like this:
   <code>slide.setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);</code>
my sliding menu don't want to slide.

But, when "TouchModeBehind" parameter setted like this:
   <code>slide.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);</code>
sliding menu is sliding, but content won't click.

In original I want sliding menu is sliding, and content is listening my clicking.

P.S. Sorry for my English.

**Comment by almozavr** [comment]
The problem is deep inside CustomViewAbove's onInterceptTouchEvent and onTouchEvent. TOUCHMODE_FULLSCREEN allows to intercept all child events (see onTouchEvent always returns true for FULLSCREEN from inside thisTouchAllowed(ev) for opened menus).

**Comment by jfeinstein10** [comment]
Yes, TOUCHMODE_FULLSCREEN on the behind view does not work

**Comment by guiled** [comment]
Is there any news about this?
Thank you!
