### ISSUE TITLE
Strange behaviour with android:windowSoftInputMode

### ISSUE THREAD

**Issue by ehrior** [jfeinstein10/SlidingMenu#26]
I have a ListView in the SlidingMenu layout and I want to use android:windowSoftInputMode to hide the keyboard when the main activity starts because I have three AutoCompleteTextView and one of them always gains focus. 
But, it seems android:windowSoftInputMode interferes with my list, so only first item is well displayed. In spite of this strange behaviour, the list works and when I click on an item, it opens a new activity. 
Am I doing something wrong? Is there any other way to hide the keyboard when an activity starts? Is there any workaround to avoid this strange behaviour?

**Comment by jfeinstein10** [comment]
This should do the job:

``` java
InputMethodManager imm = (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);
imm.hideSoftInputFromWindow(v.getWindowToken(), 0);
```

**Comment by jfeinstein10** [comment]
Come back and close the issue if this works for you.

**Comment by ehrior** [comment]
Thank you.
