### ISSUE TITLE
Height of the view doesn't account for status bar

### ISSUE THREAD

**Issue by l-barbosa** [jfeinstein10/SlidingMenu#263]
It seems like a duplicate of #114 but that was closed without any additional comment so I don't know what caused it/fixed it.

The height of the behind view is the full height of the display so the first few pixels are hidden behind the status bar.

Tested on a Samsung Galaxy S (2.3.1) and on a 4.1.1 emulator with the same results.

I don't know if it's relevant, but I'm creating the SlidingMenu long after the activity has started, after downloading some content required to create it:

``` java
public void turnSideBarOn(){

    menu = new SlidingMenu(this);
    menu.setMode(SlidingMenu.LEFT);
    menu.setShadowWidthRes(R.dimen.sidebarDropShadowWidth);
    menu.setShadowDrawable(R.drawable.sidebar_drop_shadow);
    menu.setBehindOffsetRes(R.dimen.sidebarOffsetWidth);
    menu.setFadeDegree(0.30f);
    menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
    menu.attachToActivity(this, SlidingMenu.SLIDING_WINDOW);
    menu.setMenu(new Sidebar(this));

}

```

Sorry if it's not a bug. I appreciate any comment.

Thanks!

**Comment by l-barbosa** [comment]
I've worked around it using a dirty hack:

``` java

//When the view is initialized
DisplayMetrics dm = new DisplayMetrics();
getWindowManager().getDefaultDisplay().getMetrics(dm);


public int getStatusBarHeight(){
    if(statusHeight != -1) return statusHeight; //return cached value

    Rect rectangle= new Rect();
    Window window= getWindow();
    window.getDecorView().getWindowVisibleDisplayFrame(rectangle);

    statusHeight = rectangle.top; //store value

    return statusHeight;

}

@Override
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
    super.onMeasure(widthMeasureSpec, heightMeasureSpec);

    /*
    fl is a framelayout which is the only direct child of the sidebar view
    if the sidebar framelayout is the same height as the screen, then add 
    padding to account for the status bar
    */

    if(dm.heightPixels == fl.getHeight()){ 
      fl.setPadding(0, getStatusBarHeight(), 0, 0);
    }

}


```

It's very hacky, but it's been working so far. Would love to have a better solution if anyone can recommend one.

**Comment by honjian5231** [comment]
Its happen to my tablet also , i started some other activity first too

**Comment by honjian5231** [comment]
the problem solved after i comment on these two line , it's used to call before sliding menu

requestWindowFeature(Window.FEATURE_NO_TITLE);
//getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
//WindowManager.LayoutParams.FLAG_FULLSCREEN);
