### ISSUE TITLE
BUG? onCreateOptionsMenu not work on Fragment Content

### ISSUE THREAD

**Issue by cliu903** [jfeinstein10/SlidingMenu#267]
I try to add new menu in Class ColorFragment.java on example project. However, the method onCreateOptionsMenu does not called. Is it BUG ?  

I also create a normal fragment to test this case, it's work. 

My implement code: 

public class ColorFragment extends Fragment {

private int mColorRes = -1;

public ColorFragment() {
    this(R.color.white);
}

public ColorFragment(int colorRes) {
    mColorRes = colorRes;
    setRetainInstance(true);

}

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setHasOptionsMenu(true);
}
 .. // omitted other method
 .. 
 ..
    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {

```
super.onCreateOptionsMenu(menu, inflater);

inflater.inflate(R.menu.menu_cust, menu);
}   

} 
```

**Comment by qLag** [comment]
Same problem for me.

**Comment by jfeinstein10** [comment]
You have to add an onOpenedListener and invalidate your menu yourself

**Comment by cliu903** [comment]
I have try to put that code to FragmentChangeActivity.java and or BaseActivity.
But it's also not work. 
getSlidingMenu().setOnOpenedListener(new OnOpenedListener() {
              public void onOpened() {
                getSlidingMenu().invalidate();
              }
            });

**Comment by vinothbabu** [comment]
getSlidingMenu().setOnOpenedListener(new OnOpenedListener() {
        @Override
        public void onOpened() {
            supportInvalidateOptionsMenu();
            Log.d("SLIDING DRAWER","OPENED");
        }
    });

Called this inside the BaseActivity onCreate() method. The Fragment class onCreate() method has setHasOptionsMenu(true); called.

I don't see the Fragment class onCreateOptionsMenu() method being triggered.
