### ISSUE TITLE
Default selection state

### ISSUE THREAD

**Issue by mrityunjay-kant** [jfeinstein10/SlidingMenu#268]
I see that there are methods to set the selection state when an menu item is clicked, but I see no way to set the default selection state when the sliding menu opens up for the first time. I tried a couple of things trying to set the set the selection state when the menu opens the first time but none of them work (setting selection state when the menu item is clicked works fine). 

Am I missing something?

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please move you questions to StackOverflow.
