### ISSUE TITLE
Crash in ExampleActivity

### ISSUE THREAD

**Issue by Scott1234Abc** [jfeinstein10/SlidingMenu#27]
On Xoom with JellyBean 4.1.1

It appears that the activePointerIndex on line 1239 of CustromViewAbove class is invalid.  

To reproduce, slide the menu open, then start to close it with a drag (press and drag left).  
Stop dragging and continue to hold it.  Press the content on the right with another finger. Let go, this seems to lock the content in place (menu remains open).
Swipe the content on the right a few times left and right and the crash below occurs consistently.

07-25 18:13:17.330: E/InputEventReceiver(6453): Exception dispatching input event.
07-25 18:13:17.330: E/MessageQueue-JNI(6453): Exception in MessageQueue callback: handleReceiveCallback
07-25 18:13:17.330: E/MessageQueue-JNI(6453): java.lang.IllegalArgumentException: pointerIndex out of range
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.MotionEvent.nativeGetAxisValue(Native Method)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.MotionEvent.getX(MotionEvent.java:1981)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:86)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:210)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at com.slidingmenu.lib.CustomViewAbove.onTouchEvent(CustomViewAbove.java:1239)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.View.dispatchTouchEvent(View.java:7127)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2170)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1905)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1925)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1379)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1873)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.View.dispatchPointerEvent(View.java:7307)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3172)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3117)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4153)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4132)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4224)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.os.MessageQueue.nativePollOnce(Native Method)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.os.MessageQueue.next(MessageQueue.java:125)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.os.Looper.loop(Looper.java:124)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at android.app.ActivityThread.main(ActivityThread.java:4745)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at java.lang.reflect.Method.invokeNative(Native Method)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at java.lang.reflect.Method.invoke(Method.java:511)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
07-25 18:13:17.330: E/MessageQueue-JNI(6453):   at dalvik.system.NativeStart.main(Native Method)

**Comment by Tombarr** [comment]
This happens for me too! It seems the CustomViewAbove.onTouchEvent does something complicated with pointer indices to handle multi-touch, but there is a bug asking for the X coordinate of a non-existent pointer. It could be that a finger is lifted up or something.

**Comment by jfeinstein10** [comment]
I just fixed multi finger support for the most part. I tested on the two devices I have here and I haven't been able to reproduce this (the SlidingMenu is never left half open). It definitely needs more testing on other devices, etc. Please pull the latest changes and let me know how it goes!

I'm going to close this for now and open up another issue about starting a drag with multiple fingers (you'll see it's a little bit weird right now).

**Comment by Scott1234Abc** [comment]
Just grabbed the change and it looks fixed.  

Thanks for creating this library!
