### ISSUE TITLE
SlidingMenu from bottom to top

### ISSUE THREAD

**Issue by p6majo** [jfeinstein10/SlidingMenu#271]
I want to use the slidingMenu for a calculator, to move in and out the keypad. What modifications are required to adjust the sliding Menu going up and down instead of going sideways,

thanks,
Johannes.

**Comment by hwrdprkns** [comment]
Look at SlidingDrawer. https://developer.android.com/reference/android/widget/SlidingDrawer.html

This library isn't really for what you described.

**Comment by jfeinstein10** [comment]
Actually a top/bottom mode is coming very very soon, but I think a SlidingDrawer makes more sense for you application

**Comment by RoelRoel** [comment]
@ hwrdprkns But it's deprecated...

**Comment by hwrdprkns** [comment]
https://github.com/SimonVT/android-menudrawer

**Comment by purepure** [comment]
waiting for top/bottom mode from you. I addicted by your libs. special thank

**Comment by jfeinstein10** [comment]
Check out the all-sides branch

**Comment by mruijzendaal** [comment]
The all-sides branch isn't working for me. I've imported both the library and the example and there were errors already (e.g. SlidingMenu.LEFT  - which isn't there anymore - instead of SlidingMode.LEFT). After I've replaced them the app simply crashed...

**Comment by jfeinstein10** [comment]
There's a big difference in the API between the two. It'll take some investigating to get used to

**Comment by purepure** [comment]
I checkout this branch but It not work:
I try this:
        SlidingMenu sl = (SlidingMenu) findViewById(R.id.slmenu);
        sl.setSlidingEnabled(true);
        sl.setMode(SlidingMode.LEFT);
        sl.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
        sl.setBehindOffsetRes(R.dimen.slidingmenu_offset);
        sl.setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);
        sl.setShadowWidthRes(R.dimen.shadow_width);
        sl.setFadeDegree(0.25f);
        sl.setBehindScrollScale(.25f);
        sl.setContent(R.layout.dashboard_main);
        sl.setMenu(R.layout.dashboard_left);
        sl.setShadowDrawable(R.drawable.slidingmenu_left_shadow, SlidingMode.LEFT);
        sl.setMenu(R.layout.dashboard_right, SlidingMode.RIGHT);
        sl.setShadowDrawable(R.drawable.slidingmenu_right_shadow, SlidingMode.RIGHT);
        sl.setMenu(R.layout.dashboard_top, SlidingMode.TOP);
        sl.setShadowDrawable(R.drawable.slidingmenu_left_shadow, SlidingMode.TOP);
        sl.setMenu(R.layout.dashboard_bottom, SlidingMode.BOTTOM);
        sl.setShadowDrawable(R.drawable.slidingmenu_left_shadow, SlidingMode.BOTTOM);

But nothing happen. I even cannot slide to LEFT/RIGHT
Please take a look

**Comment by CodeCombiner** [comment]
Great library! this is what I was looking for!
Waiting for official top-bottom release with pushing the action bar down to the middle of the page!
Keep going and good luck!

**Comment by sergiiz** [comment]
'all-sides' branch still can't be compiled due to errors in code
