### ISSUE TITLE
above view is visible sometime when sliding menu is open like it is transparent on Amazon Kindle Fire

### ISSUE THREAD

**Issue by dereky7** [jfeinstein10/SlidingMenu#273]
Hi,
I develop an app with sliding menu lib,but I encounter a strange problem only on Amazon Kindle Fire device.

when the app is open and leave it alone for a while,then click the top left button to open the sliding menu,but the sliding menu look like transparent since the previous above view is visible even if it is dim.

I try a lot of solutions but it is still there,please give any suggestion,thx.

**Comment by IPL** [comment]
I also see the exact issue on Kindle Fire, and so far I can only see it on Kindle Fire. If the above view is shown for some minutes, then even showing the sliding menu, the content view's content still is visible in the screen.

Another similar problem is that the behind view is visible when sliding menu is not showing. It looks that kindle fire has some kind of "Visual staying phenomenon"?

I have no Kindle Fire G2, so cannot verify whether it still exists with new Kindle Fire.

**Comment by jfeinstein10** [comment]
I don't have a Kindle Fire to debug with, so I can't really do anything for you guys :\
