### ISSUE TITLE
Behind view does not refresh changes in HoneyComb 3.1 and 3.2

### ISSUE THREAD

**Issue by mengon05** [jfeinstein10/SlidingMenu#274]
I dont know why, but if you change some element from the SlidingMenu, like a TextView and Listview, it would change only after you close the menu and open it again.

For example, If i use a ListView as SlidingMenu and i add a OnClickListener that change the text of the selected Item for something like "Text Changed" but do not close the menu after the click. The text is never updated while the menu is open, but if you close and open it again the text changes. I tested this in a Galalxy Tab 10.1 with android 3.2 and in a AVD with 3.1 and 3.2 and on all of them is happening but i tried too in a Nexus 4 it worked correctly.

If you want to test it, you can use the SlidingMenu example project, add this lines after the switch in the method onListItemClick in ColorMenuFragment

``` java
@Override
    public void onListItemClick(ListView lv, View v, int position, long id) {
        Fragment newContent = null;
        switch (position) {
        case 0:
            newContent = new ColorFragment(R.color.red);
            break;
        case 1:
            newContent = new ColorFragment(R.color.green);
            break;
        case 2:
            newContent = new ColorFragment(R.color.blue);
            break;
        case 3:
            newContent = new ColorFragment(android.R.color.white);
            break;
        case 4:
            newContent = new ColorFragment(android.R.color.black);
            break;
        }
        //Change the text of the item
        TextView textView = ((TextView)v.findViewById(android.R.id.text1));
        textView.setText("Text Changed");
        //
        if (newContent != null)
            switchFragment(newContent);
    }
```

And comment this line in the switchContent method in FragmentChangeActivity:

``` java
 public void switchContent(Fragment fragment) {
        mContent = fragment;
        getSupportFragmentManager()
        .beginTransaction()
        .replace(R.id.content_frame, fragment)
        .commit();
//              Comment this
//      getSlidingMenu().showContent();
    }
```

With this, the menu does not close when you click on an item and the text should change to "Text changed" but does not do it

**Sorry for my bad english

**Comment by haythemmm** [comment]
Hello,
i got a similar issue:
https://github.com/jfeinstein10/SlidingMenu/issues/277

**Comment by vanleeuwenbram** [comment]
I've had the same problem but I've managed to solve this:
the actual problem lies in a defect in android 3.2 regarding hardware acceleration so if you put in your AndroidManifest that your application is hardwareAccelerated="true" your problem will be solved.

**Comment by haythemmm** [comment]
Thanks vanleeuwenbram. that solve my problem. if you have a stackoverflow account, please post this answer in this link: http://stackoverflow.com/questions/14644517/xml-background-dont-change-when-i-use-tablet#comment20729457_14644517

So you get the 200 points :)
Thanks again

**Comment by jfeinstein10** [comment]
Wonderful fix!
