### ISSUE TITLE
Drop Shadow Issue

### ISSUE THREAD

**Issue by asolis90** [jfeinstein10/SlidingMenu#276]
How to achieve a drop shadow like this:

![Screenshot_2013-02-07-02-33-03](https://f.cloud.github.com/assets/1640596/134806/d44a026e-70f8-11e2-97bd-90f4f9ce3369.png)

**Comment by mengon05** [comment]
I don't know if the library do it itself, but I did it by my own, you need to make a new drawable xml with this:

``` xml
 <?xml version="1.0" encoding="UTF-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item >
       <shape android:shape="rectangle">
          <solid android:color="#10000000"/>
       </shape>
    </item>
    <item>
       <shape android:shape="rectangle" >
           <gradient android:startColor="@android:color/transparent"
               android:centerColor="@android:color/transparent"
               android:endColor="#30000000"
               android:centerX="95%p" />
       </shape>
    </item>
</layer-list>
```

Then set it as background to the behind view

**Comment by jfeinstein10** [comment]
Yes, you have to define it yourself as a drawable and then call setShadowDrawable and the rest will be handled by the library
