### ISSUE TITLE
Toggle method for right to left slide

### ISSUE THREAD

**Issue by nilkashid** [jfeinstein10/SlidingMenu#279]
Hi, very nice and excellent work... its working fine on both way.. I just want to ask whether there is any toggle function for right to left slide as like for left to right.my toggle() working fine for left to right. now i want to build it for right left.
Need help.. Thank you...

**Comment by nilkashid** [comment]
Hye hi implemented this toggle from right to left .. Any one need help feel free to ask.. thank you..
And also thank you for such a good help...

**Comment by crazyrcm** [comment]
How did you do that,? need the same

thanks

**Comment by nilkashid** [comment]
Try to implement another toggle to method  similar to toggle define inside library .... Check it.. And let me know if you need more help. Have a nice day
