### ISSUE TITLE
Transparente Layout

### ISSUE THREAD

**Issue by mengon05** [jfeinstein10/SlidingMenu#28]
First, very nice work dude

Second, i think i found something weird, it happen when the main layout has trasnparent background and the behind layout is too large, the behind layout overlap the main layout and it looks weird.

For example set android:background="@android:color/transparent" to the main layout, and for behind layout use this:

<code>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

```
<Button
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="button1" />

<Button
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="button2" />

<Button
    android:id="@+id/behindbutton"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="button3" />

<Button
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="This is a laaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarge button" />
```

</LinearLayout>

</code>
To fix it, you just need to set a non-transparent background to the main layout.

I think it how the library works and is not a bug, but i had to say it hehe

**Comment by jfeinstein10** [comment]
Thanks :)
Yup, that's exactly how it is supposed to work. I think I just found a nifty way of stopping it too.

**Comment by jfeinstein10** [comment]
Alright just fixed it. Now it'll take the window background by default when you use a sliding ActionBar.

**Comment by mengon05** [comment]
Wow!, that was fast, thank a lot! it's working like a charm

**Comment by jfeinstein10** [comment]
No problem :)
