### ISSUE TITLE
Behind Menu disable sliding and always show

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#280]
I like to suggest a feature to always show behind menu. Reason why is when application in tablet devices, it has enough screen space to always show behind menu.

**Comment by ranhaveshush** [comment]
I think you already have this option.
Look at the sample project at the responsive UI activity.

When in landscape handset the menu hide but on tablet the menu is exposed.

**Comment by ghost** [comment]
It works. Thanks for point it out.

One issue: 
In exposed mode, the shadow I set doesn't get displayed. 
        slidingMenu.setShadowWidthRes(R.dimen.shadow_width);
        slidingMenu.setShadowDrawable(R.drawable.shadow);

**Comment by ranhaveshush** [comment]
Hi again,

I personally didn't played with it yet,  but in a couple of days I will.
If I'll experience different behavior I'll let you know.

Good luck...

If you'll find a solution or mistake you have made please let me know.

Thanks.

**Comment by ghost** [comment]
Please find attached screenshot describe the problem. 

For Tablet with "Exposed" behind menu (left menu), there are no shadow (problem)

Same code on Phone, behind menu (left menu), there is shadow (work fine)

my Code snippet which  follows example ResponsiveUIActivity.java

```
    if (findViewById(R.id.left_menu_frame) == null) {
        setBehindContentView(R.layout.left_menu_frame);
        slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
        slidingMenu.setSlidingEnabled(true);
        setSlidingActionBarEnabled(true);
        slidingMenu.setMode(SlidingMenu.LEFT);
        slidingMenu.setBehindScrollScale(0.0f);
        slidingMenu.setFadeEnabled(false);
        slidingMenu.setFadeDegree(0.8f);
        slidingMenu.setOnClosedListener(onClosedListener);
        slidingMenu.setOnOpenedListener(onOpenedListener);
        slidingMenu.setOnOpenListener(onOpenListener);
        actionBar.setDisplayHomeAsUpEnabled(true);
        actionBar.setHomeButtonEnabled(true);
    } else {
        View v = new View(this);
        setBehindContentView(v);
        slidingMenu.setSlidingEnabled(false);
        slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_NONE);
        setSlidingActionBarEnabled(false);
        actionBar.setDisplayHomeAsUpEnabled(false);
        actionBar.setHomeButtonEnabled(false);
    }
```

![Screenshot_2013-02-10-17-20-25](https://f.cloud.github.com/assets/970456/143879/bfffcec6-73d0-11e2-851c-8aaad267883e.png)
![export_01](https://f.cloud.github.com/assets/970456/143880/c019c63c-73d0-11e2-95c7-e2e9191888ee.png)

**Comment by jfeinstein10** [comment]
You would have to add the shadow yourself (as a simple ImageView in your xml layou) because now the menu is not controlled by the SlidingMenu class and therefore it can't draw a shadow over it.
