### ISSUE TITLE
Dark background behind menu open, white color displayed short amount of time

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#281]
i am using slidingmenu with a dark theme. I found, when open behind menu(left menu), at the beginning of open, white color is show for short amonnt of time. Cause screen to flicker. Attached are four images of screenshot take at very moment screen being opened. you could see two of the image has white on the left. and the the other two is normal. 

Please let me know if you need more details. Thanks for great library
![Screenshot_2013-02-10-16-59-19](https://f.cloud.github.com/assets/970456/143847/e11b0ee8-73cd-11e2-807e-44385b0372f1.png)
![Screenshot_2013-02-10-16-59-42](https://f.cloud.github.com/assets/970456/143848/e123b7be-73cd-11e2-879a-50911b5ddd6b.png)
![Screenshot_2013-02-10-16-59-55](https://f.cloud.github.com/assets/970456/143849/e12c5176-73cd-11e2-80db-a1ab75c0f7bc.png)
![Screenshot_2013-02-10-16-58-44](https://f.cloud.github.com/assets/970456/143850/e14a33b2-73cd-11e2-8cc7-bf4082c4d729.png)

**Comment by ghost** [comment]
One more detail, when hand swipe to open left menu, it appears fine (not white flicker).

but when user click on back soft button to invoke showMenu(), white flicker appears everytime.

following is code snippet 

```
@Override
public boolean onKeyUp(int keyCode, KeyEvent event) {
    if (!getResources().getBoolean(R.bool.has_two_panes)) {

        FragmentManager fragmentManager = getSupportFragmentManager();
        if (keyCode == KeyEvent.KEYCODE_BACK && fragmentManager.getBackStackEntryCount() == 0) {
            if (getSlidingMenu().isMenuShowing()) {
                finish();
            } else {
                getSlidingMenu().showMenu();
            }
            return true;
        }
    }
    return super.onKeyUp(keyCode, event);
}
```

**Comment by jfeinstein10** [comment]
I would advise you set the background color of your app to that dark color to reduce overdraw anyway.

**Comment by Den-Rimus** [comment]
What's a 'background color of your app'? Where should I set this color exactly?

**Comment by DroidLove** [comment]
<item name="android:windowBackground">@color/drawer_background</item>

Use in styles.xml theme
