### ISSUE TITLE
PointerIndex out of range

### ISSUE THREAD

**Issue by meilers** [jfeinstein10/SlidingMenu#282]
Sorry to say this, but I'm still getting the "pointerindex out of range exception" on the latest build: 
![error](https://f.cloud.github.com/assets/2792041/144172/73e641fe-73f9-11e2-8b2f-3b5ddbd9b385.jpg)

**Comment by jfeinstein10** [comment]
I'm going to need something more helpful than this. What touches or actions were you performing while this happened? What is in your SlidingMenu? A simple "this doesn't work" doesn't do me or you any good

**Comment by meilers** [comment]
It usually happens when the fragment jitters, like when I put two fingers on the screen.
