### ISSUE TITLE
How is the best way to use Preferences

### ISSUE THREAD

**Issue by ganchix** [jfeinstein10/SlidingMenu#283]
Hi,

I have implemented the SlidingMenu with ActionBarSherlock, I use `SlidingFragmentActivity` like the root Activity, and for childs I use `ListFragment`, `SherlockFragments`... but is `PreferencesFragment` added to support libraries?
How is the best way to use `Preferences` in my case?

Thanks for all,
Rafa

**Comment by Prototik** [comment]
@ganchix This question is not refers to the library. Try StackOvertflow or other QA resource. 

But you can use HoloEverywhere - where necessary libraries will be attached by a addons system. Not need wild combinations, allegedly RoboguiceSlidingPreferenceSherlockActivity ;)

**Comment by ganchix** [comment]
Sorry, thanks for your help.
I close the issue.
