### ISSUE TITLE
library folder contains errors when downloading the zip file

### ISSUE THREAD

**Issue by davidsvilem** [jfeinstein10/SlidingMenu#287]

**Comment by jfeinstein10** [comment]
Go on...?

**Comment by davidsvilem** [comment]
After importing the Library into the eclipse there are some errors:
1. SlidingMenu.java: lines: 971, 976.
2. SlidingMapActivity: lines: 9

Solving this problems is only if targeting the library to google api level 11. but its use less i need it the minimum of api level 10.

Thanks

**Comment by jfeinstein10** [comment]
Targeting and minimum are two very different things.
