### ISSUE TITLE
Errors when importing library to the eclipse

### ISSUE THREAD

**Issue by davidsvilem** [jfeinstein10/SlidingMenu#289]
I download the zip file, after open it imported the library to the eclipse and i got few errors.
For example, the library is pointing to 2.2 Android version, so there is an error in SlidingMenu.java in line @TargetApi(Build.VERSION_CODES.HONEYCOMB)

And there is also error in SlidingMapActivity on extending MapActivity

Thank you for the helpers

**Comment by drakestone** [comment]
Try to change the library to 4.2 version (Google APIs). 
There are two reasons that I recommend 4.2 version (Google APIs)
One is If you use 2.2 SDK, the SDK doesn't know what Build.VERSION_CODES.HONEYCOMB is about. you should use over 3.x SDK. but I strongly recommend to use 4.2. and also don't worry about backward compatibility it can run on Android 2.2. and even Android 2.1 (API level 5).
the second is SlidingMapActivity is derived from MapActivity. The MapActivity needs Google APIs library. you have to install Google APIs SDK (API level 17)

**Comment by arslan-anwar** [comment]
I am still getting this error even I have make current version to 4.2. Error is getSupportActionBar().setDisplayHomeAsUpEnabled(true); 

this line is red along with onOptionsItemSelected(MenuItem item) {

I have already added SherlockActionBar lib into base path.

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please move you questions to StackOverflow.
