### ISSUE TITLE
Font drawing issue

### ISSUE THREAD

**Issue by Redth** [jfeinstein10/SlidingMenu#291]
I'm having an issue where after I change fragments in my activity's content view, the fonts become all weird.  It looks like the view is not being cleared before the fonts are being drawn again.  Have you seen this before?

![Weird Fonts](https://dl.dropbox.com/u/56106/Screenshot_2013-02-15-15-49-12.png)

**Comment by jfeinstein10** [comment]
I don't think this is an issue with the library, so I would advise you ask this on StackOverflow.
