### ISSUE TITLE
i often get a ava.lang.IllegalArgumentException runtime exception~

### ISSUE THREAD

**Issue by 6a209** [jfeinstein10/SlidingMenu#296]
/AndroidRuntime(10946): FATAL EXCEPTION: main
E/AndroidRuntime(10946): java.lang.IllegalArgumentException: pointerIndex out of range
E/AndroidRuntime(10946):    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
E/AndroidRuntime(10946):    at android.view.MotionEvent.getX(MotionEvent.java:1974)
E/AndroidRuntime(10946):    at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
E/AndroidRuntime(10946):    at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:86)
E/AndroidRuntime(10946):    at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:184)
E/AndroidRuntime(10946):    at com.slidingmenu.lib.CustomViewAbove.onInterceptTouchEvent(CustomViewAbove.java:637)
E/AndroidRuntime(10946):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1629)
E/AndroidRuntime(10946):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
E/AndroidRuntime(10946):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
E/AndroidRuntime(10946):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)

**Comment by habecht** [comment]
You may need to update this library. I think that issue got fixed.

**Comment by jfeinstein10** [comment]
Duplicate
