### ISSUE TITLE
Blank fragment when orientation change

### ISSUE THREAD

**Issue by fabiencheret** [jfeinstein10/SlidingMenu#299]
I noticed that on the demo App (and in mine by the way), when I turn the screen on a phone running Android 4.2 or 2.2, the above view is totally blank.

If you want to reproduce this case :
Run SlidingMenuDemo app in any emulator.
Go to ResponsiveUI 
![device-2013-02-21-115625](https://f.cloud.github.com/assets/1781762/179902/ba9da910-7c15-11e2-9f52-21c131166480.png)
Turn the screen (ctrl+F11)
![device-2013-02-21-115709](https://f.cloud.github.com/assets/1781762/179903/bfe4575c-7c15-11e2-9474-e45a93fa27b5.png)

Here you go...
I don't really know how to solve this.
If you have any idea...

**Comment by denevell** [comment]
I had this issue because I wasn't setting the setMenu() method again after an orientation change.

Put it through the debugger and ensure setMenu is set on the SlidingMenu object after the orientation change.

**Comment by fabiencheret** [comment]
I finally fixed this, calling setRetainInstance on Fragment, but the main problem was due to the use of 

``` java
if (savedInstanceState != null)
    mContent = getSupportFragmentManager().getFragment(savedInstanceState, "mContent");
```

Just don't call it !
Even if you save it with 

``` java
getSupportFragmentManager().putFragment(outState, "mContent", mContent);
```

it does not work...
So let Android do the job and it will be fine.

I think it needs to be done on the demo app, because this error is everywhere.

**Comment by jaredsburrows** [comment]
Hello,

Is it possible for you to post your working code? I have tried your solution in your comments and it still does not work for me.

Regards,

**Comment by fabiencheret** [comment]
Yep !
So it should be :

``` java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTitle(R.string.responsive_ui);
        setContentView(R.layout.responsive_content_frame);

        // check if the content frame contains the menu frame
        if (findViewById(R.id.menu_frame) == null) {
            setBehindContentView(R.layout.menu_frame);
            getSlidingMenu().setSlidingEnabled(true);
            getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
            // show home as up so we can toggle
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        } else {
            // add a dummy view
            View v = new View(this);
            setBehindContentView(v);
            getSlidingMenu().setSlidingEnabled(false);
            getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_NONE);
        }

        // set the Above View Fragment
        if (mContent == null)
            mContent = new BirdGridFragment(0); 

                mContent.setRetainInstance(true);

        getSupportFragmentManager()
        .beginTransaction()
        .replace(R.id.content_frame, mContent)
        .commit();

        // set the Behind View Fragment
        getSupportFragmentManager()
        .beginTransaction()
        .replace(R.id.menu_frame, new BirdMenuFragment())
        .commit();

        // customize the SlidingMenu
        SlidingMenu sm = getSlidingMenu();
        sm.setBehindOffsetRes(R.dimen.slidingmenu_offset);
        sm.setShadowWidthRes(R.dimen.shadow_width);
        sm.setShadowDrawable(R.drawable.shadow);
        sm.setBehindScrollScale(0.25f);
        sm.setFadeDegree(0.25f);

        // show the explanation dialog
        if (savedInstanceState == null)
            new AlertDialog.Builder(this)
            .setTitle(R.string.what_is_this)
            .setMessage(R.string.responsive_explanation)
            .show();
    }
```

**Comment by jaredsburrows** [comment]
Hello,

The method "setRetainInstance(true)" is from Fragment: http://developer.android.com/reference/android/app/Fragment.html#setRetainInstance(boolean).

How did you use it in your FragmentActivity, "public class ResponsiveUIActivity extends SlidingFragmentActivity {"?

Regards,

**Comment by fabiencheret** [comment]
Oh sorry. You should call it on the attached fragment, my code was untested.
I updated it, now it should work...

Sincerly

**Comment by jaredsburrows** [comment]
I solved my issue my simply adding :

android:configChanges="orientation|screenSize|screenLayout" 

in the "AndroidManifest.xml". But this will cause the layout width to be the same onOrientationChanged, so in order to sove that, add this to your main SlidingActivity:

```
@Override
public void onConfigurationChanged(Configuration newConfig) 
{
    super.onConfigurationChanged(newConfig);

    // make sure the menu offset is correct
    sm.setBehindOffsetRes(R.dimen.slidingmenu_offset);
}
```

My code has been tested.

**Comment by fabiencheret** [comment]
Ok, thanks for your code.
Anyway, orientation change is a bitch.
