### ISSUE TITLE
'Enable/Disable' menu sliding feature

### ISSUE THREAD

**Issue by gshockv** [jfeinstein10/SlidingMenu#3]
It is a very usefull to have a feature that allow to disabling or enabling sliding menu in touch mode

**Comment by jfeinstein10** [comment]
Done in the latest push. The SlidingMenu class now has setSlidingEnabled and isSlidingEnabled methods. Sorry for leaving this out up until now!

**Comment by gshockv** [comment]
Thanks!

**Comment by gshockv** [comment]
Did you push actual version of CustomViewAbove? 
I have a build problem: can't find methods 
mViewAbove.setSlidingEnabled(b) 
and 
mViewAbove.isSlidingEnabled()

**Comment by jfeinstein10** [comment]
Ah so sorry about that! Should be in there now.

**Comment by gshockv** [comment]
I think in this line of code
<Sliding>Activity#onPostCreate() {
  // . . .
  mSlidingMenu.setStatic(isStatic());
}
you should write
mSlidingMenu.setStatic(!mSlidingMenu.isSlidingEnabled());

**Comment by jfeinstein10** [comment]
Static and enabled are two different things. Static was something that I was playing around with for tablets. Basically, if you have enough space, it should show both the behind and the above views at the same time. In doing this, the SlidingMenu should be disabled in the process of marking it as static. Does that make sense?
