### ISSUE TITLE
setSlidingActionBarEnabled(false) causes the Action Bar (Sherlock) to disappear.

### ISSUE THREAD

**Issue by iPaulPro** [jfeinstein10/SlidingMenu#30]
When using ActionBarSherlock, setting setSlidingActionBarEnabled(false) causes the Action Bar to disappear completely on devices running Honeycomb and below.

This can be tested with demo that I created, based on your original "example" found [here](https://github.com/iPaulPro/SlidingMenu/tree/master/example-abs). Simple change the boolean on line 40 of ExampleSherlockActivity.java.

**Comment by jfeinstein10** [comment]
Done and done :)

**Comment by iPaulPro** [comment]
Awesome. Thanks!

**Comment by jfeinstein10** [comment]
No problem. Was quite an embarrassing bug haha. Let me know if there are still problems with this.

**Comment by iPaulPro** [comment]
There may still be an issue with ViewPagerIndicator but I'm not sure yet. It's working fine with ABS and the built-in ActionBarSherlock tabs.

BTW - The project.properties file in /library was somehow deleted along the way. I just made a commit with it restored. It's included with the pull request for the example with ABS integration.
