### ISSUE TITLE
Set touch mode on few elements

### ISSUE THREAD

**Issue by dmitrikudrenko** [jfeinstein10/SlidingMenu#300]
I have layout with two linearLayout and one viewpager between them. How to make - TouchModeAbove on my linearLayout is working, and sliding on viewpager don't view slidingmenu?

**Comment by jfeinstein10** [comment]
Add it to the ignored views!

**Comment by letroll** [comment]
can you add in wiki how to do? for those who do not seek the command to use is addIgnoredView (View v);
