### ISSUE TITLE
wrong transparent

### ISSUE THREAD

**Issue by purepure** [jfeinstein10/SlidingMenu#301]
Hi!
I integrate this library into my app but I got a problem with transparent. I use its as LEFT_RIGHT mode and setup the layout: left - content - right
When I drag the content view to see left(right) view, the content of left(right) visible wrong way. Please refer to my attached file to see the problem.
![left](https://f.cloud.github.com/assets/3175469/189671/c391968e-7ea0-11e2-9730-f4686725aa5e.png)

The same with the right view

The content view not cover all of the side view when slide !
Please tell my how to fix its
Here is my code:

```
            SlidingMenu sl = (SlidingMenu) findViewById(R.id.sliding_menu);
    sl.setMode(SlidingMenu.LEFT_RIGHT);
    sl.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
    sl.setBehindOffsetRes(R.dimen.slidingmenu_offset);
    sl.setShadowWidthRes(R.dimen.shadow_width);
    sl.setShadowDrawable(R.drawable.shadow);
    sl.setBehindScrollScale(0.25f);
    sl.setFadeDegree(0.25f);
    sl.setContent(R.layout.content);
    sl.setMenu(R.layout.left_side); 
    sl.setSecondaryMenu (R.layout.right_side);
    sl.setSecondaryShadowDrawable(R.drawable.slidingmenu_shadow);
```

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please move you questions to StackOverflow.
