### ISSUE TITLE
Where am I going wrong.

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#305]
I am attempting to use the library in a test project. I use the example code 

```
    SlidingMenu menu = new SlidingMenu(this);
    menu.setMode(SlidingMenu.LEFT);
    menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
    menu.setShadowWidthRes(R.dimen.shadow_width);
    menu.setShadowDrawable(R.drawable.shadow);
    menu.setBehindOffsetRes(R.dimen.slidingmenu_offset);
    menu.setFadeDegree(0.35f);
    menu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);
    menu.setMenu(R.layout.menu);
```

my menu layout is as follows 

<?xml version="1.0" encoding="utf-8"?>
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/menu"
    android:name="com.example.testmenu.SampleListFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

</fragment>

I have copied the SampleListFragment.java file to my project, as is from the example project.

When I run the app, it fails when displaying the menu with a trace of the following 

02-26 23:01:10.593: E/AndroidRuntime(18100): FATAL EXCEPTION: main
02-26 23:01:10.593: E/AndroidRuntime(18100): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testmenu/com.example.testmenu.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class fragment
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.ActivityThread.access$600(ActivityThread.java:130)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.os.Looper.loop(Looper.java:137)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.ActivityThread.main(ActivityThread.java:4745)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at java.lang.reflect.Method.invokeNative(Native Method)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at java.lang.reflect.Method.invoke(Method.java:511)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at dalvik.system.NativeStart.main(Native Method)
02-26 23:01:10.593: E/AndroidRuntime(18100): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class fragment
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at com.slidingmenu.lib.SlidingMenu.setMenu(SlidingMenu.java:370)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at com.example.testmenu.MainActivity.onCreate(MainActivity.java:24)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.Activity.performCreate(Activity.java:5008)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
02-26 23:01:10.593: E/AndroidRuntime(18100):    ... 11 more
02-26 23:01:10.593: E/AndroidRuntime(18100): Caused by: java.lang.ClassCastException: com.example.testmenu.SampleListFragment cannot be cast to android.app.Fragment
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.Fragment.instantiate(Fragment.java:577)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.Fragment.instantiate(Fragment.java:552)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.app.Activity.onCreateView(Activity.java:4656)
02-26 23:01:10.593: E/AndroidRuntime(18100):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
02-26 23:01:10.593: E/AndroidRuntime(18100):    ... 19 more

Where am I going wrong?

**Comment by pestrada** [comment]
If that is all you have in your Layout, that may be the problem. You are missing the Android XML Namespace declaration. You should have something like this:
< ?xml version="1.0" encoding="utf-8"?>
< LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal" >
< /LinearLayout>

Then, you can use SlidingMenu inside that. Also, make sure to take a look at the README.md (section XML usage).

**Comment by ghost** [comment]
Found the issue, it was because I was using an Activity class rather than a FragmentActivity class, and as the menu was defined as a fragment it clearly was never going to work.

Changed base class of the activity to "fragmentActivity" and it worked straight away.

**Comment by sseidenthal** [comment]
I had the exact same problem, thank you for your comment it helped me a lot

**Comment by ghost** [comment]
I am having same problem, and i have used FragmentActivity, but still getting this error

**Comment by sshahidaslamm** [comment]
Open the `gradle.properties` and add this:
`android.enableAapt2=false`
This resolved my issue.
