### ISSUE TITLE
NPE  at com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:833)

### ISSUE THREAD

**Issue by bakomchik** [jfeinstein10/SlidingMenu#307]
I've changed the com.slidingmenu.example.AttachExample.class 
I added menu.setStatic(true) and got an error

02-27 17:22:01.780: E/AndroidRuntime(1123): java.lang.NullPointerException
02-27 17:22:01.780: E/AndroidRuntime(1123):     at com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:833)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.View.draw(View.java:13461)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.View.draw(View.java:13342)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.View.draw(View.java:13340)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.View.draw(View.java:13461)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.widget.FrameLayout.draw(FrameLayout.java:467)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.View.draw(View.java:13342)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.View.draw(View.java:13340)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.View.draw(View.java:13461)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.widget.FrameLayout.draw(FrameLayout.java:467)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2183)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2258)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2153)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2021)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1832)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.Choreographer.doCallbacks(Choreographer.java:555)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.Choreographer.doFrame(Choreographer.java:525)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.os.Handler.handleCallback(Handler.java:615)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.os.Handler.dispatchMessage(Handler.java:92)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.os.Looper.loop(Looper.java:137)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at android.app.ActivityThread.main(ActivityThread.java:4745)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at java.lang.reflect.Method.invokeNative(Native Method)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at java.lang.reflect.Method.invoke(Method.java:511)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-27 17:22:01.780: E/AndroidRuntime(1123):     at dalvik.system.NativeStart.main(Native Method)

**Comment by mykola-dev** [comment]
i have exactly same issue :(

**Comment by qichuan** [comment]
I have encountered the same problem as well.

I saw this issue is closed, may I know whether this issue is already resolved or won't fix? @jfeinstein10 Thanks.
