### ISSUE TITLE
SlidingMenu + AndroidAnnotations conflict

### ISSUE THREAD

**Issue by raphaeloliveira** [jfeinstein10/SlidingMenu#308]
Hi, I'm getting a conflict using these two libraries together. Android annotations has an annotations called @AfterView to annotate a method (https://github.com/excilys/androidannotations/wiki/Injecting-Views). The problem is the annotated method is in fact called inside setContentView but SlidingMenu calls setContentView three times which jeopardizes the logic inside the annotated method. Any solutions to this conflict?

This issue has been closed in AndroidAnnotations since they cannot be responsible for other libs calling setContentView more then once
https://github.com/excilys/androidannotations/issues/449

**Comment by pyricau** [comment]
Before going any further, I would really like to understand why SlidingMenu calls `setContentView()` three times.

**Comment by raphaeloliveira** [comment]
My SlidingMenu codes are:

public class RealEstateCustomerLeadsListActivity extends
    SlidingFragmentActivity implements FilterResponseHandler

and

```
@Override
public void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);

if (leads == null) {
    leads = new ArrayList<RealEstateCustomerLead>(0);
}

setBehindContentView(R.layout.left_menu);
leftMenu = getSlidingMenu();
leftMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
leftMenu.setBehindOffsetRes(R.dimen.slide_menu_offset);

actionBar = getSupportActionBar();
actionBar.setSubtitle("Saldo disponível: R$: -");
actionBar.setDisplayHomeAsUpEnabled(true);
actionBar.setIcon(R.drawable.ic_left_menu);


}
```

**Comment by jwoolston** [comment]
Do you mean that it has 3 implementations of setcontentview?

**Comment by raphaeloliveira** [comment]
Android annotations overrides all the 3 signatures of setContentView to guarantee that @afterViews annotated method will be called in afterSetContentView.

```
@Override
public void setContentView(int layoutResID) {
    super.setContentView(layoutResID);
    afterSetContentView_();
}

@Override
public void setContentView(View view, LayoutParams params) {
    super.setContentView(view, params);
    afterSetContentView_();
}

@Override
public void setContentView(View view) {
    super.setContentView(view);
    afterSetContentView_();
}
```

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please move you questions to StackOverflow.
