### ISSUE TITLE
How to dynamically modify the Slidingmenu View?

### ISSUE THREAD

**Issue by sachingit** [jfeinstein10/SlidingMenu#309]
I have a SlidingMenu layout, where I have 2 linear layout defined. By default, one layout remains hidden but other is visible. The behavior is - onClick() of first layout, the hidden layout visibility should be toggled i.e. if it is hidden, it should become visible, and vice versa. 

To achieve this, I am doing something like this in my activity:

ImageView shareIcon = (ImageView)menu.findViewById(R.id.shareicon);
shareIcon.setOnClickListener(new OnClickListener() {  
            public void onClick(View v) {  
                final View shareOptionsView =  
                                (View)menu.findViewById(R.id.shareoptions);

```
                            if(shareOptionsView.getVisibility() == View.GONE) {                         
                shareOptionsView.setVisibility(View.VISIBLE);                   
            } 
                            else {                  
                shareOptionsView.setVisibility(View.GONE);              
            }
        }
```

});

What I don't see the SlidingMenu UI getting updated as soon as shareIcon gets clicked. But yes, when I hide the sliding menu and bring it back, its when I can see the change on SlidingMenu's UI. Is this behavior is because the SlidingMenu UI is displayed by some other thread? What is that I am missing?

**Comment by MoonlightMultimedia** [comment]
What I did was put all slidingmenu functions in a void, including setMenu() then I use a broadcast to notify changes then call the void, using setMenu() it automatically updates it. I do the rest in the adapter.

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please move you questions to StackOverflow.
