### ISSUE TITLE
Default value of behindScrollScale

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#31]
Thanks for your fantastic library! 
Into the readme you specify that the default value of behind scroll scale il 0, but it is 0.25f :)

Bye

**Comment by chrisjenx** [comment]
Ahh I didn't check this, but I didn't think it was 0f this makes more sense

**Comment by jfeinstein10** [comment]
Yeah, 0.25f was what I found looked the nicest; and why not make people use the nicest by default? :P
I'll change the ReadMe.
