### ISSUE TITLE
Suggested technique to maintain SlidingMenu's width under different screen configuration

### ISSUE THREAD

**Issue by yccheok** [jfeinstein10/SlidingMenu#316]
I realize SlidingMenu's examples does come with different values folders (values-land, values-large, ...). Each dimes.xml, does comes with different value for

```
<dimen name="slidingmenu_offset">?dp</dimen>
```

I was wondering, instead of maintaining a bunches of different dimes.xml for so many folders, is the following technique recommended? Will we face any unexpected side effect?

The technique merely get the screen current width in pixel, minus with our desired sliding menu width. The resultant value will be used for setBehindOffset.

The code is as follow

```
@SuppressWarnings("deprecation")
@SuppressLint("NewApi")
private int getScreenWidthInPixel() {
    Display display = getWindowManager().getDefaultDisplay();

    if (android.os.Build.VERSION.SDK_INT >= 13) {
        Point size = new Point();
        display.getSize(size);
        int width = size.x;
        return width;       
    } else {
        return display.getWidth();
    }
}

final int slidingmenuWidth = getResources().getDimensionPixelSize(R.dimen.slidingmenu_width);
final int screenWidth = getScreenWidthInPixel();
final int offset = Math.max(0, screenWidth - slidingmenuWidth);
sm.setBehindOffset(offset);
```

Thanks.

**Comment by jfeinstein10** [comment]
That should work just fine! :+1:
