### ISSUE TITLE
Disable gestures, show menu after button press?

### ISSUE THREAD

**Issue by tajchert** [jfeinstein10/SlidingMenu#319]
Hi, as my app is based on receiving onTouch events, and somehow SlidingMenu is disrupting this, I would like to know is it possible (and how) to disable showing menu by gesture (slide to right) and just leave button to do so?
Regards,

**Comment by JesseFarebro** [comment]
``` java
@Override
public void onCreate(Bundle savedInstanceState) {
       SlidingMenu menu = new SlidingMenu(this);
       menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_NONE);
}


@Override
public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
    case android.R.id.home:
        toggle();
    }
    return super.onOptionsItemSelected(item);
}
```

Set the TouchMode to none and have your activity override OnOptionsItemSelected to have your actionbar icon trigger the menu. As well please refer to the documentation as this is well documented. Thanks.
