### ISSUE TITLE
NPE when setting mode to LEFT_RIGHT

### ISSUE THREAD

**Issue by rage28** [jfeinstein10/SlidingMenu#321]
Hi,

 I just used the SimpleExample in my own activity attached on the wiki page and just changed the mode to LEFT_RIGHT and I got the below exception:

(Note: But it works when I set the mode to either LEFT or RIGHT, but crashes on LEFT_RIGHT mode)

03-07 10:44:04.351: E/AndroidRuntime(1851): FATAL EXCEPTION: main
03-07 10:44:04.351: E/AndroidRuntime(1851): java.lang.NullPointerException
03-07 10:44:04.351: E/AndroidRuntime(1851):     at com.slidingmenu.lib.CustomViewBehind.scrollBehindTo(CustomViewBehind.java:218)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at com.slidingmenu.lib.CustomViewAbove.scrollTo(CustomViewAbove.java:807)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at com.slidingmenu.lib.CustomViewAbove.onSizeChanged(CustomViewAbove.java:468)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.View.setFrame(View.java:13840)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.View.layout(View.java:13752)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.ViewGroup.layout(ViewGroup.java:4362)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.View.layout(View.java:13754)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.ViewGroup.layout(ViewGroup.java:4362)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.View.layout(View.java:13754)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.ViewGroup.layout(ViewGroup.java:4362)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.Choreographer.doCallbacks(Choreographer.java:555)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.Choreographer.doFrame(Choreographer.java:525)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.os.Handler.handleCallback(Handler.java:615)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.os.Handler.dispatchMessage(Handler.java:92)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.os.Looper.loop(Looper.java:137)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at android.app.ActivityThread.main(ActivityThread.java:4745)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at java.lang.reflect.Method.invokeNative(Native Method)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at java.lang.reflect.Method.invoke(Method.java:511)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
03-07 10:44:04.351: E/AndroidRuntime(1851):     at dalvik.system.NativeStart.main(Native Method)

**Comment by winterDroid** [comment]
Same issue here.. Think it is because there is no secondary menu set. Would it be possible to have got same view as left and right menu?

**Comment by jfeinstein10** [comment]
^ what he said!

**Comment by gitjhb** [comment]
Thanks! OMG this problem confused me about 1 hour, and I just can't find what is the issue!
