### ISSUE TITLE
Two level sliding menu

### ISSUE THREAD

**Issue by sureshcheemalamudi** [jfeinstein10/SlidingMenu#322]
I wanted my app to have a 2 level sliding menu like the zomato app. Here is my question on SO : http://stackoverflow.com/questions/15264567/android-sliding-menu-with-sub-menu . Can i achieve this using this library? i tried using secondary menu, but it is inflated on top of the first menu which makes both of the menus look as single one (overlapping). Where am i going wrong?

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please move you questions to StackOverflow.
