### ISSUE TITLE
addIgnoredView doesn't work for MapView widgets

### ISSUE THREAD

**Issue by KubebatHaMachatz** [jfeinstein10/SlidingMenu#327]
Hi,

I tried working with addIgnoredView after adding a MapView widget to one of my activities. scrolling left on the map would cause the SlidingMenu to slide out. Trying to add the MapView to the Ignored Views collection didn't work (the rect object would have relative values for top, left, right & bottom while the X and Y of the MotionEvent are probably absolute).

After looking into the addIgnoredView source code - I managed to find a solution - 
This function calculates weather the x-y coordinate of the MotionEvent object are in one of the views in the ignored views collection:

/**
     \* Determines if given points are inside view
     \* @param x - x coordinate of point
     \* @param y - y coordinate of point
     \* @param view - view object to compare
     \* @return true if the points are within view bounds, false otherwise
     */
    private boolean isPointInsideView(float x, float y, View view){
        int location[] = new int[2];
        view.getLocationOnScreen(location);
        int viewX = location[0];
        int viewY = location[1];

```
    //point is inside view bounds
    if(( x > viewX && x < (viewX + view.getWidth())) &&
            ( y > viewY && y < (viewY + view.getHeight()))){
        return true;
    } else {
        return false;
    }
}
```

I found this function here - https://www.google.co.il/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CC4QFjAA&url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F4165765%2Fhow-to-get-a-view-from-an-event-coordinates-in-android&ei=5qBAUav1GMbKtQadr4DoDQ&usg=AFQjCNE-Ssp3XcfekTDsM7gIFQno9iNCzQ&bvm=bv.43287494,d.Yms

it works properly for me (tested on api level 8 -> 16).
Regards,
Dan

**Comment by jfeinstein10** [comment]
#326  Linking these!
