### ISSUE TITLE
Webview Not Response to Click

### ISSUE THREAD

**Issue by nwlawrence** [jfeinstein10/SlidingMenu#329]
HI, my name is Lawrence.
We are using the slidingmenu and love it.

However, we get a very big trouble.
We put the sliding menu with a list of webview, however, the link or photo on the webview
not response to click event (sometimes).

It only display 
"
03-14 11:42:23.280: V/CustomViewAbove(6993): Received ACTION_DOWN
03-14 11:42:23.500: V/CustomViewAbove(6993): onInterceptTouch moved to:(349.25952, 265.8327), diff:(3.2404785, 1.2569275), mLastMotionX:352.5
"
etc. And Nothing Happen ....

We already set the webviewclient to listen to the url click event.

Thanks in advance,
Lawrence

**Comment by jfeinstein10** [comment]
Maybe don't use fullscreen touch mode?
