### ISSUE TITLE
The sliding menu is freezing the custom view above on Honeycomb

### ISSUE THREAD

**Issue by romainpiel** [jfeinstein10/SlidingMenu#330]
I'm currently building an app using latest version of SlidingMenu [a1710a7038c17f37c6dfb31cd626dd484f5ecf16](https://github.com/jfeinstein10/SlidingMenu/commit/a1710a7038c17f37c6dfb31cd626dd484f5ecf16) and the menu is failing on Honeycomb while it's working as expected on other versions.

Basically, any interaction with the sliding menu freezes the custom view above. Prior versions of the sliding menu may work as I couldn't reproduce the bug on the demo.

**Comment by romainpiel** [comment]
I confirm that the issue came with the latest commits. I just updated to the version used in the demo [cdef60e5f2663d4e14bce92221ddb866154114b8](https://github.com/jfeinstein10/SlidingMenu/commit/cdef60e5f2663d4e14bce92221ddb866154114b8) and it's working fine.

**Comment by jfeinstein10** [comment]
Duplicate #274
