### ISSUE TITLE
Unable to change Sliding Menu Theme Runtime

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#333]
Hi,
i'd like to change Sliding menu runtime but i don't know how ...
This is what i've done on onCreate(...)
...
...
    setTheme(current_theme);
    setContentView(R.layout.activityXYZ);

```
    // configure the SlidingMenu
SlidingMenu menu = new SlidingMenu(context);
    menu.setMode(SlidingMenu.LEFT);
    menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
    menu.setShadowWidthRes(R.dimen.shadow_width);
    menu.setShadowDrawable(R.drawable.shadow);
    menu.setBehindOffsetRes(R.dimen.slidingmenu_offset);
    menu.setFadeDegree(0.35f);
    menu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);
    menu.setMenu(R.layout.config_sliding_menu);
```

...
...

current_theme var is changed runtime but on R.layout.activityXYZ all works fine,  on R.layout.config_sliding theme don't change ...

There is a way to change menu theme? i've try with menu.getContext().setStyle(....) but it doesn't work -.-

AleXD

**Comment by jfeinstein10** [comment]
This doesn't have to do with this library. Please refer to StackOverflow.
