### ISSUE TITLE
Change BehindOffsetRes affect instantly

### ISSUE THREAD

**Issue by SeeYaApp** [jfeinstein10/SlidingMenu#337]
Hello, 

First, let me thank you for the great library!

second, I'm initializing slidermenu object with:
sliderReference.setBehindOffsetRes(R.dimen.actionbar_home_width);   

after toggling, I need to set the behind view to full screen (after user pressed a text view located in the behind view). this is my code:

public void onClick(View v) {
                    getSlidingMenu().setBehindOffsetRes(R.dimen.actionbar_home_width_less); 
menuLayout.setVisibility(INVISIBLE);
...
}

thing is - it changes the offset only after I toggle the menu.
any chance I can achieve that instantly?

Thanks,

**Comment by reshmy** [comment]
Looking for the same thing. Currently it updates the behind offset only after a toggle of the menu. Thanks for any pointers.

**Comment by jeromevdl** [comment]
I think this is the same question i've just asked #368, but with the behindWidth method. So I'm interested in too.

**Comment by jfeinstein10** [comment]
You must invalidate the View and request a layout. Try doing that and get back to me.
