### ISSUE TITLE
Sliding menu with ActionBarSherlock tabListener

### ISSUE THREAD

**Issue by arnobo** [jfeinstein10/SlidingMenu#339]
Hi

I have a problem when I use the sliding menu with the ActionBar.TabListener (from ActionBarSherlock).

Everything works fine when I navigate in my tabs without opening the sliding menu.
But when I show the sliding menu then I hide it, if I switch from tab1 to tab2, the fragment displays nothing (see screenshot below).

![Screenshot_2013-03-19-14-00-16](https://f.cloud.github.com/assets/3909777/275668/40deccf4-9096-11e2-8c21-5b6101eb025a.png)

After that, nothing appears into the tabs. I have to finish the activity and recreate it. I don't know if it is an anormal behavior or if I do something wrong.

I followed this tuto for tabs:
http://arvid-g.de/12/android-4-actionbar-with-tabs-example

**Comment by jfeinstein10** [comment]
The issues section is not for questions and how-to's. I'd like to refer you to StackOverflow for this. Thanks for understanding!
