### ISSUE TITLE
SlidingMenu#setFitsSystemWindows problem

### ISSUE THREAD

**Issue by sshogunn** [jfeinstein10/SlidingMenu#34]
Hello. I have downloaded and opened your application with the your library. But Eclipse shows me following error: "Description  Resource    Path    Location    Type
The method setFitsSystemWindows(boolean) is undefined for the type RelativeLayout   SlidingMenu.java    /com.slidingmenu.lib.SlidingMenuActivity/src/com/slidingmenu/lib    line 340    Java Problem".
This method appeared to version 14 API, but your library has target=android-8 in project properties.
What to do in this situation?

**Comment by jfeinstein10** [comment]
Try it again with the new changes

**Comment by sshogunn** [comment]
Thanks, it works.

**Comment by majinboo** [comment]
What changes did fix this error? I downloaded your library today and still got that error sadly. Only works if i use it with API 14 or higher sadly

thx in advance

**Comment by sshogunn** [comment]
I changed version to API 14. It's ok, if the library will be built with a version higher than your project.

**Comment by majinboo** [comment]
Ah ok, that did the trick. Thanks a lot, sorry for the rather stupid question then. Did not know that this was possible :)
