### ISSUE TITLE
Is there a way to avoid sliding the main view when menu is opening?

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#342]
Hi,
I'm trying to overlay menu with main activity view but all attempts are unsuccessful. Is there a way to enable only the scroll menu and maintain main activity view attached stops?

Thanks in advance

**Comment by mruijzendaal** [comment]
Not with this api, I believe.
What you could do is create a frane layout, one for the view and one for the overlay.

**Comment by jfeinstein10** [comment]
^ What he said!
