### ISSUE TITLE
Avoid slidingmenu hide menu when click a view of mainframe

### ISSUE THREAD

**Issue by marcelpinto** [jfeinstein10/SlidingMenu#346]
The situation is the following:

I have a main view, when the user clicks a button the right menu is shown with a padding of the main view, so the buttons in the main view should be clickable yet. but instead when you click on it the menu is hidden.

Can I solve this somehow?

**Comment by jfeinstein10** [comment]
You would have to go in to CustomViewAbove and change the onInterceptTouchEvent method to remove the default behavior of the SlidingMenu
