### ISSUE TITLE
How to implement both right and left side sliding ?

### ISSUE THREAD

**Issue by alicanbatur** [jfeinstein10/SlidingMenu#349]
I can use the library for one side.
Looking for this for a long time. I need to use android 2.3.3 and i want to implement both two side slide effects. Are there any tutorial about it that anyone knows ??
Any help will be appreciated .

Thanks by now.

**Comment by ghost** [comment]
Hi,

I don't know it supports 2.3.3 but there is a good tutorial you can find on youtube : http://www.youtube.com/watch?v=rs9mSnWDlZo

And also example posted on the page has implementation for left and right sliding option.

**Comment by vinothbabu** [comment]
you can look at the code example project for this class "LeftAndRightActivity.java" which has the implementation for left and right sliding.

**Comment by alicanbatur** [comment]
finally i did it.
First, i changed my  target to 4.x and my min to 2.3.3 gingerbread.
After, i can use actionbarsherlock, then, i made it. 

My fault was setting target to 2.3.3 and while its like that, android dont let me to use actionbarsherlock. It is fixed when change target to 4.x.

Thanks.
