### ISSUE TITLE
Problem with menu/behind view width

### ISSUE THREAD

**Issue by betomaluje** [jfeinstein10/SlidingMenu#351]
Hi, first of all: this library rocks! It's very useful!

I'm using this library in my project and everything is great:
the behind view width is as entered in setBehindWidth(350) or setBehindWidthRes(R.dimen.menu_width) when i use setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN).

but when I use setTouchModeAbove(SlidingMenu.TOUCHMODE_MARGIN) the width of the behind view is fulls screen instead of the 350 pixels I entered.

Is there a way to have TOUCHMODE_MARGIN and have the behind view in 350 pixels?

Here's my code:

private void setupSlidingMenu() {  
    sm = new SlidingMenu(this);

```
sm.setBehindWidth(350);

sm.setMode(SlidingMenu.LEFT);
sm.setTouchModeAbove(SlidingMenu.TOUCHMODE_MARGIN);
sm.setShadowWidthRes(R.dimen.shadow_width);
sm.setShadowDrawable(R.drawable.drop_shadow);
sm.setBehindOffsetRes(R.dimen.slidingmenu_offset);
sm.setFadeDegree(0.35f);        
sm.attachToActivity(this, SlidingMenu.SLIDING_WINDOW);
sm.setMenu(R.layout.menu);                  
```

}

I don't have SlideMenu in my xml file.

Thanks.

**Comment by jfeinstein10** [comment]
The issues section is not for questions and how-to's. I'd like to refer you to StackOverflow for this. Thanks for understanding!
