### ISSUE TITLE
Start visibility is wrong

### ISSUE THREAD

**Issue by friedit** [jfeinstein10/SlidingMenu#354]
I'm extending SlidingFragmentActivity. I set normal android contentView (setContentView), then the behind view (setBehindContentView). Then I adjust a few settings (shadowDrawable, width..).

The problem is that the menu is shown behind my view - meaning it is visible. Now this isn't obvious because it's behind the normal content view but once you activate gpu overdrawing in the phones developer settings you can see that its visible and causes a lot of overdrawing. Once you open it and close it again everything is fine.

My dirty fix is a "mViewBehind.setVisibility(View.INVISIBLE);" as the last line of the SlidingMenu constructor.

**Comment by purepure** [comment]
I get the same error and still have no idea to fix its. So, I remove the view(layout.xml) and re-create them. Fortunately, it works

**Comment by jfeinstein10** [comment]
You need to have a background on your main layout
