### ISSUE TITLE
StackOverflowError when run on android 2.3.3 emulator

### ISSUE THREAD

**Issue by hlongvu** [jfeinstein10/SlidingMenu#357]
I used slidingmenu in my application and hit this crash when running in android 2.3.3 emulator on application startup. As can be seen in the stack traces below, the crash happened in "com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:831)".
I have no idea how to solve this!
Can you take a look and help me with this?

Thank you :)

04-01 23:43:58.028: E/AndroidRuntime(371): FATAL EXCEPTION: main
04-01 23:43:58.028: E/AndroidRuntime(371): java.lang.StackOverflowError
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.graphics.Canvas.quickReject(Canvas.java:684)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1557)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.FrameLayout.draw(FrameLayout.java:357)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6986)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.FrameLayout.draw(FrameLayout.java:357)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.ScrollView.draw(ScrollView.java:1409)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6986)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.FrameLayout.draw(FrameLayout.java:357)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.ScrollView.draw(ScrollView.java:1409)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.FrameLayout.draw(FrameLayout.java:357)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.FrameLayout.draw(FrameLayout.java:357)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.FrameLayout.draw(FrameLayout.java:357)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:831)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.View.draw(View.java:6883)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.widget.FrameLayout.draw(FrameLayout.java:357)
04-01 23:43:58.028: E/AndroidRuntime(371):  at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1862)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewRoot.draw(ViewRoot.java:1522)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewRoot.performTraversals(ViewRoot.java:1258)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
04-01 23:43:58.028: E/AndroidRuntime(371):  at android.os.Handler

**Comment by hlongvu** [comment]
I found out this was due to too many nested views in layout!

**Comment by rahulupadhyay** [comment]
@hlongvu , I'm facing the same error, did you found any solution for this?
Please help me out.
