### ISSUE TITLE
How to close sliding-menu on List Activity Click

### ISSUE THREAD

**Issue by okfriansyah** [jfeinstein10/SlidingMenu#358]
I have an app that implement this sliding menu. all my apps are not using fragment. so i change the list of fragment into list activity. when i click that list, it start another activity. But the sliding menu didn't close. it still in slide mode. i just want to "when i click item in list activity, it closes slide menu and start an activity." i have tried like this. 

```
@Override
public void onListItemClick(ListView lv, View v, int position, long id) {
    Fragment newContent = null;
    Fragment Intent = null;
    switch (position) {
    case 0:
        Intent intent2 = new Intent();
        intent2.setClass(getActivity(), tab.class);
        intent2.putExtra("index", position);
        startActivity(intent2);
        break;
    case 1:
        Intent intent = new Intent();
        intent.setClass(getActivity(), about.class);
        intent.putExtra("index", position);
        startActivity(intent);
        break;
    case 2:
        Intent intent3 = new Intent();
        intent3.setClass(getActivity(), tab1.class);
        intent3.putExtra("index", position);
        startActivity(intent3);
        break;
    case 3:
        Intent intent4 = new Intent();
        intent4.setClass(getActivity(), latin.class);
        intent4.putExtra("index", position);
        startActivity(intent4);
        break;
    case 4:
        newContent = new ColorFragment(android.R.color.black);
        break;
    }
    if (newContent != null)
        switchFragment(newContent);
    if (Intent != null)
        switchFragment(Intent);

}
```

I know its dumb to use `Fragment Intent = null;` And `If (Intent != Null) switchFragment(Intent);`. I know its just for fragment only, but is there another way to switch it like that? So that when click, the slide menu closed and start the activity. Thanks

**Comment by okfriansyah** [comment]
can someone give me a hint?

**Comment by hwrdprkns** [comment]
This is not an issue with the library, so you really shouldn't be posting you question here. If you want the sliding menu to be closed, I suggest you close it in the onResume method of your activity or using some other manual method.

**Comment by okfriansyah** [comment]
sorry. 
by manual method, can you give a little detail about it?

**Comment by jfeinstein10** [comment]
The issues section is not for questions and how-to's. I'd like to refer you to StackOverflow for this. Thanks for understanding!
