### ISSUE TITLE
Extending to SlidingFragmentActivity showing build error with AndroidAnnotations in maven android project

### ISSUE THREAD

**Issue by aswathy-p-krishnan** [jfeinstein10/SlidingMenu#359]
I am new to maven architecture and I am currently working in one. In my project I have included AA library and now I am working on including SlidingMenu library. I have followed the steps and I got a sample sliding menu using the [Simple Example](https://github.com/jfeinstein10/SlidingMenu#simple-example) and it is working fine. 

But in my project I need to implement it like in [ViewPagerActivity](https://github.com/jfeinstein10/SlidingMenu/blob/master/example/src/com/slidingmenu/example/ViewPagerActivity.java) together with [ResposiveUI](https://github.com/jfeinstein10/SlidingMenu/blob/master/example/src/com/slidingmenu/example/fragments/ResponsiveUIActivity.java)

I already have a BaseActivity which extends SherlockFragmentActivity which in changing to SlidingFragmentActivity showed the following error on building. 

**BaseActivity.java:[44,0] @EActivity can only be used on an element that extends
android.app.Activity**

It is true that my eclipse IDE is behaving weirdly most of the time.. :(

**Comment by jfeinstein10** [comment]
The issues section is not for questions and how-to's. I'd like to refer you to StackOverflow for this. Thanks for understanding!
