### ISSUE TITLE
the current zip download doesnt work in eclipse

### ISSUE THREAD

**Issue by amigax** [jfeinstein10/SlidingMenu#360]
I grabbed the zip imported into eclipse but its full of compile errors. Then whe nyou go to properties and try right click on android it brings up an error about invalid values. Im thinking there is an issue with the manifest, trying to check out the git one now. Edit: unfortunately checking out from git is also the same, this means the lib wont compile for some reason.

**Comment by alxjrvs** [comment]
I am experiencing this as well.

**Comment by emauro** [comment]
Me too.

**Comment by jmmcreynolds** [comment]
I got it to work in Eclipse. I pulled it down yesterday and had to set the Project Build Target to use Google APIs instead of Android (because of the map activity).

**Comment by guicunha** [comment]
Me too my lib don't import correctly and haven't the import com.slidingmenu.example.R;

**Comment by amigax** [comment]
actually I think half of the problem is that you have to do "import existing code" then select the "library" directory, although Im sure even this had issues for me

**Comment by jfeinstein10** [comment]
I don't know how GitHub works with zips, but I do know that using git to get the most up-to-date source works. Nothing I can really do. Sorry.
