### ISSUE TITLE
How to slide in menu onClick 

### ISSUE THREAD

**Issue by readthemanual** [jfeinstein10/SlidingMenu#362]
I am following AttachExample for sliding menu. I want to simulate the same behavior onclick of a button. Currently, the code fires a dummy activity which shows blank screen. I want the menu to slide in with out having to fire an activity. Do not want to use animation either.
Not an issue per say, looking for help.

**Comment by ChristopheCVB** [comment]
I think that StackOverflow would be the place to ask such a question...

**Comment by readthemanual** [comment]
thanks, will do so

**Comment by jfeinstein10** [comment]
The issues section is not for questions and how-to's. Please go to StackOverflow for help. Thanks.
