### ISSUE TITLE
Can I set different width to left and right menu?

### ISSUE THREAD

**Issue by gdacarv** [jfeinstein10/SlidingMenu#366]
Hello, I'm new using SlidingMenu and I'm trying to figure out how to set different width to my left and right menu. What I want to accomplish is the left menu with "normal" size (offset 60dp) and my right menu with 60dp width (like a small column).

There is any way to do it? I didn't find setSecondaryBehindWidthRes, and this would be perfect.

Thank you so much!

**Comment by jfeinstein10** [comment]
Duplicate
