### ISSUE TITLE
mapview fragment 

### ISSUE THREAD

**Issue by hannesa2** [jfeinstein10/SlidingMenu#367]
Hi,
I added SlidingMapActivity (extends from SherlockMapActivity) to my mainlibrary. This works.

When I use my slidemenu in an SherlockFragmentActivity is works perfectly, but when I use same menu in an extended Activity from SlidingMapActivity I get 
SampleFragment cannot be cast to android.support.v4.app.Fragment

The same happens when I use android.app.Fragment, but I've to use android.support.v4.app.Fragment.

Any clue what is going wrong here ?

**Comment by yao2923828** [comment]
收到
