### ISSUE TITLE
Is it possible to change width with setBehindWidth while the menu is open ?

### ISSUE THREAD

**Issue by jeromevdl** [jfeinstein10/SlidingMenu#368]
I want to change the width of the menu while it is open. I try to change the width with setBehindWidth method but it does not change. 

It works perfectly in the onCreate method but later, nothing happens. I tried to invalidate the menu but it is not working. 

Or maybe is it possible to set the menu width to WRAP_CONTENT ?

**Comment by jfeinstein10** [comment]
No, this won't work on the fly.

**Comment by jeromevdl** [comment]
What is actually the constraint ? Maybe we could help you if you want, since we need something like wrap_content or modification of the width on the fly for our project...

Thanks & regards
