### ISSUE TITLE
Can't make slidingmenu do anything.

### ISSUE THREAD

**Issue by koren-eli** [jfeinstein10/SlidingMenu#369]
First of all, I'd like to thank you for your hard work.

I was able of making my activity sliding left and open a layout.
I am able to dynamically add views to my "behind content view" xml layout too.
everything works perfectly except, whenever I slide left, the layout opens but I cannot do anything with it. doesn't matter where I click, the layout disappear to the left and I'm back to the activity that extends SlidingActivity.

how can I open a new activity when sliding left, or setting listeners on buttons I dynamically add to the "behind content view" xml layout"?

I know this is a silly  question, but I really can't figure it out.
Thanks in advance!

**Comment by koren-eli** [comment]
Ok, if insted of writing:
getSlidingMenu().setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN | SlidingMenu.TOUCHMODE_MARGIN);

I write:
getSlidingMenu().setTouchModeBehind( SlidingMenu.TOUCHMODE_MARGIN);

everything works, except I can only close the "behind" layout from outside the layout (I have very little space there)
*I mean between the slide that opened, and the activity that implements SlidingActivity
is there a way to make things work without changing that line?

**Comment by jfeinstein10** [comment]
The issues section is not for questions and how-to's. Please go to StackOverflow for help. Thanks.
