### ISSUE TITLE
Selection Arrow pointing to menu item

### ISSUE THREAD

**Issue by ydinath** [jfeinstein10/SlidingMenu#380]
Hi Jeremy,

Can you please add the ability to have selection arrows. That way it makes it easier for the user to know which menu item is currently being represented. See the link and attached picture for a better description. Thanks.

See: http://cyrilmottier.com/2012/06/08/the-making-of-prixing-3-polishing-the-sliding-app-menu/

![selection_arrow](https://f.cloud.github.com/assets/4193331/397689/aa1e1718-a844-11e2-9a2c-90cafdc5c91e.png)

**Comment by trietbui85** [comment]
+1 for this improvement.

**Comment by ghost** [comment]
+1

**Comment by elirama** [comment]
+1

**Comment by koded101** [comment]
+1

**Comment by elirama** [comment]
BTW U can do it with selectorEnabled=true, selectorDrawable="@drawable/YOUR_SELECTOR", SlidingMenu.setSelectedView(View v),
but only if your menu layout is -not- a list.

**Comment by jfeinstein10** [comment]
What he said^ 
If it's a listview you have to manually invalidate on scrolling.

**Comment by elirama** [comment]
What do you mean by invalidate on scrolling?
Can i still use the drawSelector method?

The problem with list is that android recycle the list views, and when i get to drawSelector, the mSelectedView is null.

Where can i update this mSelectedView so it won't be null?

**Comment by mJROUNDI** [comment]
+1 elirama , +1 for arrow
