### ISSUE TITLE
How to remove TitleBar?

### ISSUE THREAD

**Issue by CallMeJason** [jfeinstein10/SlidingMenu#383]
Hi, all! Good afternoon. What should I do to remove TitalBar from SlidingMenu?  But if I put codes like "NoTitleBar"  into "AndroidManifest" file, it errors. And I do not know how to do about it. Thanks !

**Comment by androidder** [comment]
This worked for me:

```
    getWindow().requestFeature(Window.FEATURE_ACTION_BAR);
    getActionBar().hide();
```

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
