### ISSUE TITLE
Without using fragment,how to use ".java" to change the layout(like left menu),Thank you.

### ISSUE THREAD

**Issue by cymcsg** [jfeinstein10/SlidingMenu#384]
Without using fragment,how to use ".java" to change the layout(like left menu),Thank you.
.(See the demo,I know a way like "
getSupportFragmentManager().beginTransaction()  .replace(R.id.content_frame, new SampleListFragment()).commit();").But in fact ,it gets the opposite way.Could you tell me a better way like the types of sample activity?
I want to use the left or right menu like an activity.

Other problem:I want to use a button to take this effect,but i don't want to use actionbar because actionbar is difficult to make a good performance.And in demo,I can hardly find how to do this.
 Thanks you very much.

**Comment by sweggersen** [comment]
Change layout:

```
menu.setMode(SlidingMenu.LEFT); // or SlidingMenu.RIGHT
menu.setMenu(R.layout.menu_frame); // just a layout to switch out with your fragment
getSupportFragmentManager().beginTransaction().replace(R.id.menu_frame, YOUR_FRAGMENT).commit();
```

On click:

```
YOUR_VIEW.setOnClickListener(new View.OnClickListener() {
    @Override
        public void onClick(View v) {
            menu.toggle();
        }
    });
```
