### ISSUE TITLE
Disable slideMenu slide on swipe due to tabs

### ISSUE THREAD

**Issue by mozi22** [jfeinstein10/SlidingMenu#386]
SlidingMenu is a great library I loved it.

The problem I am having is that I am using this library to implement slideMenu in a tabs fragment activity . Now when I swipe from left to right instead of going to the previous tab it shows me the slideMenu how can I solve this problem ? Another problem is that my SlideMenu which slides in is appearing at the bottom of the Tabs can I do something to make it cover the whole height from top to bottom ?

**Comment by jfeinstein10** [comment]
TOUCHMODE_NONE
