### ISSUE TITLE
Black box covers sliding menu contents when I have MapView in my Fragment

### ISSUE THREAD

**Issue by Hesamedin** [jfeinstein10/SlidingMenu#389]
Hey Jeremy,

First of all, you work is awesome. I love it.

I have a Fragment Activity that hosts so many fragments. I have divided this activity to three parts of header, body and footer. All of fragments will be put inside body area (wii be replaced by each other).

Sliding menu is working fine and it's functionality is correct. However, one of my Fargments hosts a MapView. just in this screen, there is a black box covers menu contents when I open sliding menu. I have no idea it comes from where and how to remove it.

Any suggestion would be appreciated. there is an image in following link:
http://stackoverflow.com/q/16173075/513413

Thanks again ;)

**Comment by Laur3nt1u** [comment]
set the MapView background transparent - android:background="#00000000"

**Comment by Hesamedin** [comment]
I added map:zOrderOnTop="true" to my XML and seems it's okay but my overlays disappeared :(
