### ISSUE TITLE
Cant import library to Eclipse

### ISSUE THREAD

**Issue by okdreamy** [jfeinstein10/SlidingMenu#391]
Hi,

I can't import your library to Eclipse. I have downloaded as a ZIP file, then extract it.
Then, tried to import from an existing Android project.
When I select your folder (SlidingMenu-master), I am enable to only select the example project with ExampleListActivity name.
The second project from the list is not clickable (grey) and has for project name "library"...
What is the problem? ADT is up to date, and I have the newest Google API versions for 2.2+

**Comment by TomTasche** [comment]
You have to import the library folder first, then you can import the example folder.

**Comment by ppxpp** [comment]
maybe you had already import an Android project named "library". Rename it , and then try again

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
