### ISSUE TITLE
onOptionsItemSelected toggle() not working

### ISSUE THREAD

**Issue by androidder** [jfeinstein10/SlidingMenu#394]
```
public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
    case android.R.id.home:
        toggle();
        return true;
    }
    return super.onOptionsItemSelected((android.view.MenuItem) item);
}
```

this code only working when the slide menu is visible. when it is not, then not calling it.

Tested on a Note2

**Comment by donnfelker** [comment]
Can you provide a sample project of this behavior?

**Comment by givsta** [comment]
Hey there, also had the same issue, I solved it by:

Declaring this globally - private SlidingMenu menu;

Initialize - menu = new SlidingMenu(this);

And in your onOptionsItemSelected method - menu.toggle();

Hope this helps.
