### ISSUE TITLE
Way to permanently have the sliding menu in view

### ISSUE THREAD

**Issue by EurigJones** [jfeinstein10/SlidingMenu#395]
I am writing an app which supports multiple screen sizes. The smaller mobile devices will make use of SlidingMenu, but the larger 10" and also 7" devices will show the menu on the screen permanently as there is enough room on the screen.

So the contents will not be pushed to the side like it does when you open the sliding menu, it will be fully visible and the SlidingMenu will not close.

My question is, is this currently possible with a configuration change? If not, what is the easiest way to achieve this? I would rather not have two implementations for two devices, so if I can tweak the SlidingMenu system to do both then this is what I'm after.

**Comment by donnfelker** [comment]
Check out the "Responsive" demo on the demo app: https://play.google.com/store/apps/details?id=com.slidingmenu.example&hl=en   which is located here: https://github.com/jfeinstein10/SlidingMenu/blob/master/example/src/com/slidingmenu/example/fragments/ResponsiveUIActivity.java

**Comment by EurigJones** [comment]
Exactly what I needed. Thanks!
