### ISSUE TITLE
setOnCheckedChangeListener has no effect on android.widget.Switch in BehindContentView when inflating from xml

### ISSUE THREAD

**Issue by MichalZajac** [jfeinstein10/SlidingMenu#398]
Hi,
Maby I am missing something here.
When I am using:

```
Switch cameraViewSwitch = (Switch) rootView.findViewById(R.id.cameraViewSwitch);
        cameraViewSwitch.setOnCheckedChangeListener(new OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                mSettingsBarListener.onCameraViewSwitched(isChecked);
            }
        });
```

the onCheckedChanged() method has no effect on the Swtich control.

But if i use this:

```
Switch cameraViewSwitch = new Switch(getActivity());
        cameraViewSwitch.setOnCheckedChangeListener(new OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                mSettingsBarListener.onCameraViewSwitched(isChecked);
            }
        });
```

the control works.

I am able to assign onClick event using xml but if I slide change the switch control it will not be triggered so this it not an option.

If I am using regural FragmentActivity instead of SlidingFragmentActivity the first case works fine. 

Do you know how to explain this behaviour?

Thank you for your time.

**Comment by MichalZajac** [comment]
I have found out that my private variable LinearLayout was somehow effected after onCreateView.
This is my code in onCreateView - the rootView is global private variable for the fragment

```
rootView = (LinearLayout) inflater.inflate(R.layout.from_camera_settings_bar, container, false);
```

Now when I reinitialize rootView, everything works ok (in onStart()):

```
LinearLayout rootView = (LinearLayout) getActivity().findViewById(R.id.frontBackCameraSwitchHolder);

Switch cameraViewSwitch = (Switch) rootView.findViewById(R.id.cameraViewSwitch);
        cameraViewSwitch.setOnCheckedChangeListener(new OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                mSettingsBarListener.onCameraViewSwitched(isChecked);
            }
        });
```

I still don't know how is that possible.

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
