### ISSUE TITLE
SlidingMenu and ViewPager with API13 (Honeycomb)

### ISSUE THREAD

**Issue by regisoliveira** [jfeinstein10/SlidingMenu#399]
I´m experiencing a weird problem with SlidingMenu Library and ViewPager when they are running on devices with Android 3.2 (Honeycomb).

The problem appears when we "toggle" the SlidingMenu to show the Menu that is hidden on the left of the app. When we do this, both ContentView and BehingContentView stops responding to touch events.

Thinking that this was a problem related to my application, I downloaded the last version of ABS and SlidingMenu library and configured a new project using the built-in example that comes with the SlidingMenu and, for my surprise, the same behavior occurred with the ViewPager example.

These are the steps that I did:
1. Configure an Emulator using API Level 13 and 7" WSVGA (Tablet);
2. Download ABS and SlidingMenu from GIT;
3. Setup a new Project, using the compatibility library android-support-v41 (Also tested with android-support-v4);
4. Solved the problem 'getSupportActionBar() is undefined' as described here: https://github.com/jfeinstein10/SlidingMenu/issues/145;
5. Run the 'Example Application' and choose 'ViewPager' example;
6. Swipe pages to the right and to the left, without opening the menu;
7. Open the menu. See that the lists don´t scroll as expected;
8. Close the menu. See that the viewpager doesn´t responds to touch events anymore;

Notice that this behavior was reported only on Android 3.2 devices. We have the same application running on 2.x and on 4.x devices, without this problem.

Also, noticed that the Example Application that was downloaded from Google Play doesn´t have this problem.

**Comment by regisoliveira** [comment]
See http://stackoverflow.com/questions/16351148/slidingmenu-and-viewpager-with-api13-honeycomb

**Comment by f9021003** [comment]
Cool, it solved the problem. Thanks~~~
