### ISSUE TITLE
setup slidingMenu without sherlock

### ISSUE THREAD

**Issue by seluriseluri** [jfeinstein10/SlidingMenu#4]
Hi!

Thanks for the great job!

But I have to say that I don't really understand how I am supposed to use it...
I don't need the action bar... don't need sherlock either.
it is written that you can add it to your xml directly so that you can layout as you want but...
how do you do so?

**Comment by seluriseluri** [comment]
ok, I've got it working by putting a SlidingMenu in an xml and doing like so:

``` java
public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);

        SlidingMenu menu = (SlidingMenu)findViewById(R.id.slidingmenulayout);

        menu.setAboveView(getLayoutInflater().inflate(R.layout.main3, null));
        menu.setBehindView(getLayoutInflater().inflate(R.layout.main2, null));
        menu.setAboveTouchMode(SlidingMenu.TOUCHMODE_FULLSCREEN);
        menu.setBehindScrollScale(0.5f);
        menu.setBehindOffsetRes(R.dimen.actionbar_home_width);
    }
```

But I don't really understand the following methods:
- setBehindScrollScale
- setBehindOffsetRes
- setBehindOffset

the setBehindOffsetRes seems to be the number of pds(pxs) visible of the above view once slided out.

But the other one, no clue... some lights please!

**Comment by jfeinstein10** [comment]
BehindScrollScale relates the parallax scrolling effect. If it is set to 0.5f, then the behind view will scroll half the number of pixels as the above view. If it is set to 1.0f, then it will scroll the same number of pixels as the above view (i.e. there will be no parallax effect). If it is set to 0.0f, then it will scroll 0 pixels to come in to view. You can play around with it to get different effects.
BehindOffset is exactly what you describe; it's the number of pixels of the above view that will be showing when the behind view is visible. BehindOffsetRes should be passed something of the form R.dimen.OFFSET (a resource).
I'll put this all in the ReadMe / Wiki later. Sorry I haven't had time to up until now! :(

**Comment by seluriseluri** [comment]
Thank you for your quick reply!
I'll play around and see what I can do with it!

**Comment by jfeinstein10** [comment]
No problem :)
If you have any more questions, don't hesitate to ask!

**Comment by seluriseluri** [comment]
hi!

I've been using your library and it works great.
I've just noticed that view behinds does receive click events...
This is a weird android system but a view on top of an other one, will let
events go through if it does not have one set onto itself.

so to remedy this problem, i've put a dummy click event listener (just set
it and does nothing) on the above view(does it work with other events?not
sure).
with that click events don't go through to the view behind.

2012/7/10 Jeremy Feinstein <
reply@reply.github.com

**Comment by jfeinstein10** [comment]
This bug should be resolved in the latest code. There have been a lot of bug fixes as of late. Please make sure you're using the most recent code :)

**Comment by seluriseluri** [comment]
I'll look into downloading the latest version then!
Thank your for the quick reply!

2012/8/21 Jeremy Feinstein notifications@github.com
