### ISSUE TITLE
Incorrect Scrolling List Rendering in Example

### ISSUE THREAD

**Issue by oliver-snowden-phe** [jfeinstein10/SlidingMenu#40]
1. Expand the menu,
2. Change orientation,
3. Expanding the menu again
4. Scroll

Result: does not draw as expected - see the following screenshots.

http://twitpic.com/adf3u5
http://twitpic.com/adf44k

**Comment by oliver-snowden-phe** [comment]
Had a look at the memory usage...the example definitely heads north with rotations

**Comment by oliver-snowden-phe** [comment]
Within ExampleActivity, the following should resolve the issue:

```
    // set the Behind View
    setBehindContentView(R.layout.frame);
           ...new code below...

    // Check to see if existing fragment there
    FragmentManager fragmentManager = getFragmentManager();
    SampleListFragment fragment = (SampleListFragment)fragmentManager.findFragmentById(R.id.frame);
    if (fragment == null) {
        FragmentTransaction fragmentTransaction = this.getFragmentManager().beginTransaction();
        fragmentTransaction.add(R.id.frame, new SampleListFragment(), "menuItems");
        fragmentTransaction.commit();           
    }

            ...old code below....
    // customize the SlidingMenu
    this.setSlidingActionBarEnabled(true);
```

**Comment by oliver-snowden-phe** [comment]
See: https://github.com/oliver-snowden-hpa/SlidingMenu/commit/05cda302e7b0756c10f039e21d6c2d4c50c60e8b

**Comment by jfeinstein10** [comment]
Yes, I know all this already. It has nothing to do with SlidingMenu. Just me trying to put an example up quickly. It has also been reported before. Thanks.

**Comment by oliver-snowden-phe** [comment]
Cool - welcome to pull changes...including the Roboguice ones :D
