### ISSUE TITLE
Slider transition is not smooth.

### ISSUE THREAD

**Issue by pRatikSathaye** [jfeinstein10/SlidingMenu#401]
Hi,

I am using this lib and its really very cool.
I have integrated it into my project by using following code.

slidingMenu = new SlidingMenu(this);
slidingMenu.setMode(SlidingMenu.RIGHT);
slidingMenu.setShadowDrawable(R.drawable.shadowright);
slidingMenu.setShadowWidth(80);
slidingMenu.setBehindScrollScale(0);
slidingMenu.setBehindOffsetRes(R.dimen.behind_offset);
slidingMenu.setFadeDegree(0);
slidingMenu.attachToActivity(this, SlidingMenu.SLIDING_WINDOW);
slidingMenu.setMenu(R.layout.popupmenu);

But issue is when I click on right most button to slide the activity It slide as I want but the transition is not smooth. It start to slide stuck for fraction of seconds and again continue to slide.

So how can I use it to slide smoothly.

**Comment by okaa-pi** [comment]
I had the same issue, the answer was to enable hardware acceleration.

**Comment by pRatikSathaye** [comment]
Thanks.

It worked...
