### ISSUE TITLE
disable swipe events on some cases

### ISSUE THREAD

**Issue by chitgoks** [jfeinstein10/SlidingMenu#402]
hi. there are cases where i am dragging components from within the view. if i move it left or right, the swipe gesture activates and shows the menu

is there a method to enable disable the swipe gesture listener when there is a drag event occurring? that way, if it's just a normal swipe, the sliding menu activates. but if it is a dragging event in the view, i could just call the method to disable/enable the left and right dragging movement as a swipe gesture.

**Comment by marknutter** [comment]
+1

**Comment by jfeinstein10** [comment]
See TOUCHMODE_NONE
