### ISSUE TITLE
white blinking

### ISSUE THREAD

**Issue by gbrbks** [jfeinstein10/SlidingMenu#406]
Hello!

i'm using your library and it is great! I have an issue that maybe you can resolve. When i'm using the toggle function with the home button (the menu and the main view is dark) it blinks in white color, just for a moment. The interesting part is if i'm performing the drag gesture, it 
didn't happening.

i'm extending the SlidingFragmentActivity and the setup code is the following:

if (findViewById(R.id.menu_frame) == null) {
            setBehindContentView(R.layout.menu_frame);
            getSlidingMenu().setSlidingEnabled(true);
            getSlidingMenu()
                    .setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        } else {
            View v = new View(this);
            setBehindContentView(v);
            getSlidingMenu().setSlidingEnabled(false);
            getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_NONE);
        }

```
    MenuFragment menu = new MenuFragment();
    DataServiceHandler.getInstance().addObserver(menu);

    getSupportFragmentManager().beginTransaction()
            .replace(R.id.menu_frame, menu).commit();

    getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
    getSlidingMenu().setShadowWidthRes(R.dimen.shadow_width);
    getSlidingMenu().setShadowDrawable(R.drawable.shadow);
    getSlidingMenu().setBehindOffsetRes(R.dimen.slidingmenu_offset);
    getSlidingMenu().setFadeDegree(0.35f);
    getSlidingMenu().setBehindScrollScale(0.25f);
```

any idea. (i tried it in your example code with black list background and happened the same)

Thanks in advance!

**Comment by gbrbks** [comment]
it was the slidingmenumain.xml whit background, with proper recolor this bug gone away

**Comment by D1kz** [comment]
@hamutarto sorry, but what do you mean by proper recolor? I have the same issue
