### ISSUE TITLE
Common Slidemenu for Whole Application

### ISSUE THREAD

**Issue by pratikbutani** [jfeinstein10/SlidingMenu#408]
How to create and use common slidemenu for whole application,

I want to create List in Slide menu and use in all activity, how?

Please help...

**Comment by BradleyRL** [comment]
create a base activity with the sliding menu and extend you activities with this base activity, the example source code has this

**Comment by pratikbutani** [comment]
How to change Theme of Main Activity other than BaseActivity.

I can't able to apply different theme on Sliding Menu and Main Activity. is there any solution?

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
