### ISSUE TITLE
behindView intercepts events from aboveView when hidden and acts accordingly

### ISSUE THREAD

**Issue by derekbrameyer** [jfeinstein10/SlidingMenu#41]
Hi, if I have a scrollable or clickable container in my behindView, it intercepts events from my aboveView even when the behindView is hidden.

I am able to tap and scroll the behindView container by pressing "through" my aboveView container, if that makes sense.

**Comment by derekbrameyer** [comment]
Note: Adding these two lines _seems_ to fix the issue:

```
    getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
    getSlidingMenu().setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);
```

This makes sense but it is still a bit worrisome that the defaults allow touch interception even when the aboveView encompasses the whole screen.  I'm fine with it, but maybe it should be documented?  If I'm not understanding something, please let me know!

**Comment by jfeinstein10** [comment]
This is a preeeetty bad bug haha. I'll see if I can deal with this later. Thanks for putting it on my radar.

**Comment by jfeinstein10** [comment]
I just committed something that handles this for my use case. I'll close it for now. Let me know if you run into it again.
