### ISSUE TITLE
Latest 'master' release seems buggy

### ISSUE THREAD

**Issue by rtsukada** [jfeinstein10/SlidingMenu#410]
Tried to use the lib in the latest release without success. Even with the example, after doing all the required changes, code compile and run fine. However, touch is messed up as soon as we do the first slide to show the panel. (touch stops to update views working on both side (inside the drawer and in the main view). 

Changed to an older sherlock version didn't work. 
Changing to an older SlidingMenu version fixed the problem. (Don't know exactly where the bug happened, but I rolled back to the last Google Play update (Dec. 4)

**Comment by rtsukada** [comment]
Adding more info..
I got this problem in a galaxy tab 7.7 with android 3.2, not sure if this is an isolated issue.

Looking further seems something related to this fix: 

commit 3d5e962d121b31f988cde116664e5e264175453a
    Explicit use of hardware layers for smoother scrolling
Date:   Mon Feb 18 11:19:14 2013 -0500

```
Update README.md
```

**Comment by MoizAli** [comment]
Hello Jeremy,

I am facing the same problem on Galaxy Nexus 7 inch tablet. Has a solution for this been found?

Thanks,
Moiz

**Comment by MoizAli** [comment]
Sorry this solution for this is mentioned in issue 261.
"Comment out the hardware acceleration in the manageLayers method of SlidingMenu. This seems to be the only solution since SurfaceViews don't work."
