### ISSUE TITLE
A Vertical SlidingMenu

### ISSUE THREAD

**Issue by EurigJones** [jfeinstein10/SlidingMenu#412]
I've found SlidingMenu incredibly useful, but I've now come across a use case where I need to "push up" a view to reveal another view underneath.

Just so as you know, it's a chat feature so when the user wants to chat they can click on the chat button and it pushes up the view to reveal the last few chat messages and a chat message prompt.

I would personally love to see this.

**Comment by jfeinstein10** [comment]
See the all sides branch.
