### ISSUE TITLE
Missing R

### ISSUE THREAD

**Issue by jjhesk** [jfeinstein10/SlidingMenu#414]
From the location: package com.jeremyfeinstein.slidingmenu.lib;

Where is the R??
I found that the R is missing from the import.. 
Please help

**Comment by jjhesk** [comment]
Description Resource    Path    Location    Type
R cannot be resolved to a variable  CustomViewBehind.java   /HelloHesk/src/com/jeremyfeinstein/slidingmenu/lib  line 391    Java Problem

**Comment by jjhesk** [comment]
Problem solved

**Comment by pauloandreget** [comment]
How you solved this issue? I tried to clean the project to generate the R.java but that did not work.

**Comment by jjhesk** [comment]
The R problem was resolved by the having the project to be added as a library. First you import the folder as [existing code into the workplace] then you need to choose the library folder from the downloaded zip master file. (you can rename of the project by directly editing the xml file at the .project) Go to your current working project, right click and select properties, at the left side choose android, there is a section where you can add libraries into the your project as a reference. Choose the existing folder from the slidingmenu. Done

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
