### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by jjhesk** [jfeinstein10/SlidingMenu#417]
I have followed the manual for setting up the library and it doesnt work
![errorcode](https://f.cloud.github.com/assets/629338/500071/6d1f8176-bc67-11e2-8f78-fb5f99e582f3.png)
.
Here is the screen cap of my progress.. any one that can help with this?

I have first created a new project and marked it as a library. Then I dragged the library files into the folder system. I only added the additional files in the folder and finally found that

**Comment by justinmc** [comment]
I'm also having problems setting up, so consider that I don't know exactly what I'm talking about while reading this...

My impression on how to set up this project is this: 

File -> Import -> Existing Android Code into Workspace.
Select the "library" folder in the SlidingMenu project.
Project -> Clean and clean the new "library" project
In the newly imported "lbrary" project in Eclipse, copy the library.jar file in the /bin directory into your own project's /libs directory
Add this library.jar file to your build path, which you can do by right clicking the library.jar file in your project, and selecting Build Path -> Add to Build Path

Then you should be ready to start using the project.

This works for me and my project compiles, but unfortunately I'm getting a NoClassDefFoundError when I try to open an activity that uses SlidingMenu in the app.

Maybe you'll have more luck than me if you try setting up like this.  If not, let me know what you think the correct setup procedure is.

**Comment by jjhesk** [comment]
I have no clue. When I only import the projec -library folder and the IDE tells me that there are no project can be found..

**Comment by jjhesk** [comment]
Actually i got this kind of file system when I imported the project file at the workplace.

![ddd](https://f.cloud.github.com/assets/629338/504947/3528e75a-bd05-11e2-9141-6f6b8b7abfae.png)

Please take a look.

**Comment by jjhesk** [comment]
Okay. I finally got it done. I believed that jfeinstein10 has missed a .project file at the library folder. Now you can simply add a file and rename it to .project. Inside to file you can copy and paste code from below and it will be able to import the project at the workplace.

```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
    <name>jfeinstein10slidingmenu</name>
    <comment></comment>
    <projects>
    </projects>
    <buildSpec>
        <buildCommand>
            <name>com.android.ide.eclipse.adt.ResourceManagerBuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
        <buildCommand>
            <name>com.android.ide.eclipse.adt.PreCompilerBuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
        <buildCommand>
            <name>org.eclipse.jdt.core.javabuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
        <buildCommand>
            <name>com.android.ide.eclipse.adt.ApkBuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
    </buildSpec>
    <natures>
        <nature>com.android.ide.eclipse.adt.AndroidNature</nature>
        <nature>org.eclipse.jdt.core.javanature</nature>
    </natures>
</projectDescription>
```

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
