### ISSUE TITLE
default title bar shows on behindview when using ABS

### ISSUE THREAD

**Issue by patjackson52** [jfeinstein10/SlidingMenu#42]
My behind view has a strip at the top of the screen that appears to be the default system title bar.  This is only visible on honeycomb(have yet to test on ICS).  I am using this with ABS and I am enabling the sliding actionbar.  I don't have a fix for this right now...

**Comment by jfeinstein10** [comment]
Could you send a picture of this?

**Comment by jfeinstein10** [comment]
Ping! Again, could I see a picture of it? For me it's kind of hard to picture this
