### ISSUE TITLE
Menu open on KEYCODE_DPAD_LEFT

### ISSUE THREAD

**Issue by marcelpinto** [jfeinstein10/SlidingMenu#423]
Hello, 

My situation is the following:

I have a gridlayout with several views, this views are focusable, my device is controlled using a Pad (Remote control) so arrow left,right,down,up everything works good except when the view focused on the gridlayout is the first one, then if I press the left button, the Sliding menu opens, and I don't want this, I should avoid.

I've try several things, as get the key event and return true but I could not solve it.
Maybe there is a bug or a simple way to solve this,

Can anyone help me?

Thanks,

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
