### ISSUE TITLE
Problems building sinds latest Android SDK update

### ISSUE THREAD

**Issue by marcelhoffs** [jfeinstein10/SlidingMenu#426]
Hi,

I have problems with my projects after updating to the latest Android SDK. It builds fine, but on runtime I get this, anyone have a clue?:

05-19 09:37:51.361: E/AndroidRuntime(23071): FATAL EXCEPTION: main
05-19 09:37:51.361: E/AndroidRuntime(23071): java.lang.NoClassDefFoundError: android.support.v4.view.ViewConfigurationCompat
05-19 09:37:51.361: E/AndroidRuntime(23071):    at com.slidingmenu.lib.CustomViewAbove.initCustomViewAbove(CustomViewAbove.java:167)
05-19 09:37:51.361: E/AndroidRuntime(23071):    at com.slidingmenu.lib.CustomViewAbove.<init>(CustomViewAbove.java:157)
05-19 09:37:51.361: E/AndroidRuntime(23071):    at com.slidingmenu.lib.CustomViewAbove.<init>(CustomViewAbove.java:152)
05-19 09:37:51.361: E/AndroidRuntime(23071):    at com.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:207)
05-19 09:37:51.361: E/AndroidRuntime(23071):    at com.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:190)
05-19 09:37:51.361: E/AndroidRuntime(23071):    at com.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:169)
05-19 09:37:51.361: E/AndroidRuntime(23071):    at com.mhoffs.filemanagerplus.AMain.getInterfaceObjects(AMain.java:1770)

**Comment by tjwink** [comment]
I have the same problem!

**Comment by tjwink** [comment]
Right click the libs folder,choose "Build Path" -> "Use as Source Folder".

**Comment by crossle** [comment]
Right click the project, "Build Path" check the Private library.

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
