### ISSUE TITLE
How to use SlidingMapActivity with SupportMapFragment

### ISSUE THREAD

**Issue by bastienbeurier** [jfeinstein10/SlidingMenu#429]
Hello,

I'm trying to use SlidingMapActivity with SupportMapFragment and for this I need my activity to extend FragmentActivity, but SlidingMapActivity extends MapActivity which extends Activity. 

Anybody encountered this problem and found a solution?

Thanks!

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please ask questions on StackOverflow or elsewhere. Thanks!
