### ISSUE TITLE
ActionBar not go with the aboveview when sliding when using SlidingMenu as a view (XML)

### ISSUE THREAD

**Issue by zhuoqiang** [jfeinstein10/SlidingMenu#43]
ActionBar not go with the aboveview when sliding when using SlidingMenu as a view (XML)

Is there any way that ActionBar could move alone with the aboveView when sliding ?

**Comment by ashokgelal** [comment]
Have you checked out the included examples? The default activity 'Example' shows how to do this. Just follow the example and you should be good.

**Comment by jfeinstein10** [comment]
The only way to do this is to use my Sliding*Activities. It would be near impossible to rearrange the view hierarchy safely with a SlidingMenu at an arbitrary point in it (i.e. defined in xml and inflated somewhere).
