### ISSUE TITLE
setSlidingActionBarEnabled(false) issue

### ISSUE THREAD

**Issue by traveltoaiur** [jfeinstein10/SlidingMenu#431]
I'm working on a project using SlidingMenu and it works perfectly. However, just by adding

this.setSlidingActionBarEnabled(false);

on the onCreate() of my main activity, it will prevent the sliding menu from working whenever I call

this.setContentView(any layout);

As soon as I change the content view of my main activity it's like the sliding menu doesn't exist anymore. This happens even when I re-apply the original contentview to the activity.

If I set .setSlidingActionBarEnabled(true) everything starts working with no problem.

**Comment by jfeinstein10** [comment]
No, all it will do is prevent the ActionBar from sliding
