### ISSUE TITLE
setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN) issue

### ISSUE THREAD

**Issue by longerian** [jfeinstein10/SlidingMenu#432]
I import jeremyfeinstein's SlidingMenu project into my app project, this is how I configure the sliding menu and it works fine except that the menu is not touchable to slide to close itself.

```
sm = getSlidingMenu();
sm.setShadowWidthRes(R.dimen.shadow_width);
sm.setShadowDrawable(R.drawable.shadow);
sm.setBehindOffsetRes(R.dimen.slidingmenu_offset);
sm.setFadeDegree(0.35f);
sm.setTouchModeAbove(SlidingMenu.TOUCHMODE_MARGIN);
sm.setMode(SlidingMenu.LEFT_RIGHT);
```

When I want to make it touchable, I added the following code `sm.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);`, which makes the menu touchable. The only problem is that I found the menu is not clickable now, the menu items are unable to receive click events to response it.

Did I do anything wrong?

**Comment by jfeinstein10** [comment]
This is known to not work. Please look at previous issues before posting a new one.

**Comment by longerian** [comment]
OK, I see.

**Comment by rekire** [comment]
I wrote a fix for that see #446.

**Comment by longerian** [comment]
aha, thank you very much~

**Comment by gtchjc** [comment]
Hi, longerian, I follow your changes, but found that the left can slide off, but can not slide off the right side.
Please help.
Thank you very much!

**Comment by gtchjc** [comment]
Hi, longerian, I follow your changes, but found that the left can slide off, but can not slide off the right side.
Please help.
Thank you very much!

**Comment by gtchjc** [comment]
There is no one way, please help

**Comment by gtchjc** [comment]
This issue has been resolved, then this I thank rekire, because before I did not view it leads to the right side of the slide can not add the View view after the OK 
Specific solutions, please refer to # 466 
Thank you very much
