### ISSUE TITLE
Have a full screen image to cover sliding menu as well

### ISSUE THREAD

**Issue by yccheok** [jfeinstein10/SlidingMenu#435]
Previously, I can have a full screen image during runtime by executing

```
public class MyFragmentActivity extends FragmentActivity {
    private void showFullScreenImage() {
        this.findViewById(R.id.content).setVisibility(View.INVISIBLE);
        // Hopefully display a full screen image.
        this.findViewById(R.id.screen_wait).setVisibility(View.VISIBLE);
```

---

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <ImageView android:src="@drawable/question" android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:id="@+id/screen_wait" android:layout_gravity="center" android:visibility="gone" />

    <FrameLayout 
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="match_parent" >
    </FrameLayout>

</FrameLayout>
```

---

However, thing doesn't work quite well if I were using `SlidingFragmentActivity`. When I slide open the menu, and execute `showFullScreenImage`, `ImageView` will only occupy right half of the screen. This is because left half of the screen is occupying by sliding menu.

How can I make sure the `ImageView` will cover the entire `id.content`, and the left sliding menu too?

**Comment by jfeinstein10** [comment]
Why does it matter what is under a splash screen? The user can't see or interact with it, so it shouldn't matter.

**Comment by yccheok** [comment]
Nope. User can see and touch the sliding menu, if the sliding menu is opened before showing up the splash screen. Programmatic-ally closing the sliding menu before showing up the splash screen won't work, as closing animation seems "too slow" for user.
