### ISSUE TITLE
ADT 22+

### ISSUE THREAD

**Issue by ftgoncalves** [jfeinstein10/SlidingMenu#441]
After I upgraded the ADT to new version 22, my project doesn't works! below the errors:

05-30 20:08:07.057: E/AndroidRuntime(3811): FATAL EXCEPTION: main
05-30 20:08:07.057: E/AndroidRuntime(3811): java.lang.NoClassDefFoundError: android.support.v4.view.ViewConfigurationCompat
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.initCustomViewAbove(CustomViewAbove.java:167)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.<init>(CustomViewAbove.java:157)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.<init>(CustomViewAbove.java:152)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:207)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:190)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:169)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.moneytreeapplication.MainActivity.addSlidingMenu(MainActivity.java:152)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.moneytreeapplication.MainActivity.onCreate(MainActivity.java:29)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.app.Activity.performCreate(Activity.java:5104)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.app.ActivityThread.access$600(ActivityThread.java:141)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.os.Handler.dispatchMessage(Handler.java:99)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.os.Looper.loop(Looper.java:137)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at android.app.ActivityThread.main(ActivityThread.java:5041)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at java.lang.reflect.Method.invokeNative(Native Method)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at java.lang.reflect.Method.invoke(Method.java:511)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
05-30 20:08:07.057: E/AndroidRuntime(3811):     at dalvik.system.NativeStart.main(Native Method)

**Comment by acedanger** [comment]
http://stackoverflow.com/a/16595708/183231
