### ISSUE TITLE
No up button. Can I still activate the slide on button press?

### ISSUE THREAD

**Issue by ErnestG** [jfeinstein10/SlidingMenu#45]
I'm having an issue implementing this into my application. I'm using ActionBarSherlock, but I'm using a custom layout inside of the actionbar. I have a three line image (similar to FB app) that I want to use to activate the slide. Any easy way to do this?

**Comment by jfeinstein10** [comment]
Yes, you would have to set an onclicklistener on the button to call the toggle method

**Comment by jfeinstein10** [comment]
Yes, you would have to set an onclicklistener on the button to call the toggle method

**Comment by ErnestG** [comment]
Yeah, I figured you would have given the ability for this. If it's not too much of a bother, where is the toggle method?

**Comment by ErnestG** [comment]
For instance I found:

``` java
public void toggle() {
        mHelper.toggle();
    }
```

In SlidingActivity.java, but how do I call it in my application main activity?

**Comment by jfeinstein10** [comment]
You can directly call public or protected methods of the super class in any sub class in Java
