### ISSUE TITLE
disable slidingmenu in landscape mode

### ISSUE THREAD

**Issue by blacky94** [jfeinstein10/SlidingMenu#458]
hi,

is there a way to disable the slidingmenu in the landscape mode. I tried it with mMenu.setSlidingEnabled(false); but my main view was moved a bit(size of the slidingmenu) left. I want to show the slidingmenu and resize my main layout only in the landscape mode.

a picture to better understand:
http://s1.directupload.net/images/130620/vfb89nxa.jpg

**Comment by jfeinstein10** [comment]
See ResponsiveUIActivity in the example
