### ISSUE TITLE
Is it possible to set the slideStyle to SlidingMenu.SLIDING_CONTENT when extending SlidingActivity?

### ISSUE THREAD

**Issue by nico3865** [jfeinstein10/SlidingMenu#459]
Hi,

Is it possible to set the slideStyle to SlidingMenu.SLIDING_CONTENT when extending SlidingActivity?

Or is it only possible to set that value when attaching the SlidingMenu to an activity?

Thanks,

Nick

**Comment by jfeinstein10** [comment]
setSlidingActionBarEnabled

**Comment by nico3865** [comment]
awesome, working.

Thanks Jeremy, great work btw.
