### ISSUE TITLE
Trying to toggle onClick

### ISSUE THREAD

**Issue by ErnestG** [jfeinstein10/SlidingMenu#46]
I have a button set onClick to execute "settings" in my xml. I get a crash when I attempt to toggle the sliding menu.

Before my oncreate

``` java
SlidingActivity slider;
```

Then I added a new method.

``` java
public void settings(View view) {
        slider.toggle();
    }
```

But I get an illegal state exception when the button is hit. Am I going about this the wrong way? Thanks

**Comment by jfeinstein10** [comment]
What is the message?

**Comment by ErnestG** [comment]
What is the error message?

It's "08-12 17:39:58.239: E/AndroidRuntime(6331): java.lang.IllegalStateException: Could not execute method of the activity"

The only other thing I could find was "08-12 17:39:58.239: E/AndroidRuntime(6331): Caused by: java.lang.NullPointerException"

**Comment by jfeinstein10** [comment]
Okay. Scroll down a little farther. It should say "Caused by ..." and give you what caused this exception.

**Comment by ErnestG** [comment]
"08-12 17:39:58.239: E/AndroidRuntime(6331): Caused by: java.lang.NullPointerException"
When I double click, it takes me to this line in the editor.

``` java
slider.toggle();
```

**Comment by jfeinstein10** [comment]
So your activity is null. Must be something with the lifecycle. Nothing to do with the library itself

**Comment by ErnestG** [comment]
Am I calling it correctly? I can get the slider to work (it works perfectly if I swipe in from the side) just the button doesn't work. It's a simple one page test application I have, I don't think it's a problem on my end (hopefully)

**Comment by ErnestG** [comment]
Yeah, I wasn't doing it correctly.

I stated in my first question what I was doing, and my answer was much simpler.

This works:

Before my oncreate

``` java
//Do nothing
```

Then I added a new method.

``` java
public void settings(View view) {
        toggle();
    }
```
