### ISSUE TITLE
Setting width of menu instead of offset

### ISSUE THREAD

**Issue by kasperholtze** [jfeinstein10/SlidingMenu#47]
Hello,

It would be very nice if it was possible to set the width of the menu. On tablets (and landscape), it does not make sense to make the menu fill the entire screen horizontally.  If the app is always landscape OR portrait, that could be easily done by measuring the display, but tablet apps often need to be able to rotate.

Thanks :)

**Comment by iPaulPro** [comment]
+1

**Comment by jfeinstein10** [comment]
Ask and ye shall receive :)

**Comment by iPaulPro** [comment]
Awesome.

**Comment by kasperholtze** [comment]
Thank you so much! :-)

**Comment by jfeinstein10** [comment]
No problemo guys. Sorry it took so long actually

**Comment by drinu** [comment]
I am trying to use setBehindWidth, however nothing changes

**Comment by jfeinstein10** [comment]
If you are using a resource you have to call setMenuWidthRes

**Comment by acedanger** [comment]
I'm trying to use `setMenuWidthRes` but I don't see it as being available. I downloaded the library approximately a week ago. In my activity where I'm utilizing the library, I've modified it to extend `SlidingFragmentActivity`. Have I missed something when I set up my project to use the library?
![Screen Shot 2013-03-04 at 4 32 16 PM](https://f.cloud.github.com/assets/1345540/218740/36c753f0-8513-11e2-8724-a68fafbad032.png)

Edit: You can disregard this question. I found the method I was looking for - `setBehindWidthRes()`
