### ISSUE TITLE
Two Sliding Menu, one right, one left

### ISSUE THREAD

**Issue by quentin23soleil** [jfeinstein10/SlidingMenu#477]
Hey, 

I'm not even sure if it's possible, but if it is, I have no idea how to do it. 
The SlidingMenu.RIGHT seems not to make the menu slide from the right, to the left.

Right now, what I've implemented is two sliding menu. One is LEFT, the other is RIGHT. But the problem is, both comes from left. :(

**Comment by hikobayashi** [comment]
I think you can use http://stackoverflow.com/questions/16059069/slider-menu-both-sideright-left-in-single-activity to achieve.

**Comment by quentin23soleil** [comment]
Damn I'm such an idiot. Was confusing setMode and setTouchModeAbove. :( 
Thanks!
