### ISSUE TITLE
Fragment issue?

### ISSUE THREAD

**Issue by radzio** [jfeinstein10/SlidingMenu#48]
Is it posible to use Sliding menu in activity that is created from fragment? Check this sample from ACS:

https://github.com/JakeWharton/ActionBarSherlock/blob/master/samples/fragments/src/com/actionbarsherlock/sample/fragments/FragmentLayoutSupport.java

I can't use setBehindView in this Activity so how can I use Slidingmenu?

``` java
    /**
* This is a secondary activity, to show what the user has selected
* when the screen is not large enough to show it all in one activity.
*/

    public static class DetailsActivity extends SherlockFragmentActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            setTheme(SampleList.THEME); //Used for theme switching in samples
            super.onCreate(savedInstanceState);

            if (getResources().getConfiguration().orientation
                    == Configuration.ORIENTATION_LANDSCAPE) {
                // If the screen is now in landscape mode, we can show the
                // dialog in-line with the list so we don't need this activity.
                finish();
                return;
            }

            if (savedInstanceState == null) {
                // During initial setup, plug in the details fragment.
                DetailsFragment details = new DetailsFragment();
                details.setArguments(getIntent().getExtras());
                getSupportFragmentManager().beginTransaction().add(
                        android.R.id.content, details).commit();
            }
        }
    }
```

**Comment by jfeinstein10** [comment]
From looking at the posted code it looks like you don't have a SlidingMenu anywhere in your activity. This would explain why you can't call that method

**Comment by radzio** [comment]
Hi,

I've simply used ABS example to ilustrate this. See this tutorial from official Android site: http://developer.android.com/training/basics/fragments/fragment-ui.html

If I'm using fragments in my activity and in portrait orientation I want to open new activity with single fragment I'm not using setContentView because I'm getSupportFragmentManager().beginTransaction().add(
                        android.R.id.content, details).commit();

Any ideas :>? Or shoud create xml layout and do something like this:

setContentView(R.layout.custom_layout_with_fragment_container);

and later:

```
            getSupportFragmentManager().beginTransaction().add(
                    R.id.my_fragment_container, details).commit();
```

BTW.

I've another question. Is it possible to hide SlidingMenu without animation? When I'm starting new activity with SlidingMenu visible and then return it is still visible.

**Comment by jfeinstein10** [comment]
I would use the second approach as it's the one that I know definitely works.

Right now, the SlidingMenu maintains its state. Although you may be able to get away with calling it somewhere that the user won't see it yet.

**Comment by radzio** [comment]
Everything is woking correctly now. Thanks and sorry for bothering you!

**Comment by jfeinstein10** [comment]
No worries! Glad I could clear things up :)
