### ISSUE TITLE
SampleListFragment Question

### ISSUE THREAD

**Issue by staber** [jfeinstein10/SlidingMenu#49]
How do I get these strings and icons to display instead of the hard coded "Medium Text" and app icon from the row.xml layout?

This is the only part that's edited in the file. I'm showing two list items but not what I'm expecting. 

public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        SampleAdapter adapter = new SampleAdapter(getActivity());
        //for (int i = 0; i < 20; i++) {
            adapter.add(new SampleItem(new Fragment(), "Sample List", android.R.drawable.btn_star));
            adapter.add(new SampleItem(new Fragment(), "Sample List 2", android.R.drawable.btn_plus));
        //}
        setListAdapter(adapter);
    }

**Comment by ErnestG** [comment]
For my application, I just erased the fragment code, and I edited the frame.xml file to have like 5 menu options.

**Comment by staber** [comment]
I followed this tutorial and made my own custom layout inside of the ListView. Similar concept but the step by step made it easier to modify the things I needed. 

http://codehenge.net/blog/2011/05/customizing-android-listview-item-layout/
