### ISSUE TITLE
jar mismatch! Fix your dependencies

### ISSUE THREAD

**Issue by almasmaris** [jfeinstein10/SlidingMenu#499]
I'm import "example" project to my eclipse and also the libraries (action bar sherlock and slidingmenu library). 

But, i get error "jar mismatch! Fix your dependencies" . I know the problem is the project consist 2 android support v4 jar from slidingmenu library's and also from actionbarsherlock library's. 

Pity, i cannot solve this problem. People said that to solve this is  "delete android support v4 jar from libraries (both of them)" but when i did that, i got error in libraries. Another people said to copy android v4 jar from actionbarsherlock and replace android v4 jar in slidingmenu library's. Still,  that's not solve my problem. 

i'm really need to solve this problem for my project. If you know how to solve this, please let me know how to do it. thank you

**Comment by riyazMuhammad** [comment]
Do the following,
Copy the jar from your project and paste it into actionbar libs then try cleaning and refreshing the project.
Tell us what happens now.

**Comment by riyazMuhammad** [comment]
To be more clear you need one version of support v4 jar across your project and libraries. So copy the one which you feel the latest version of support v4 and replace paste and replace on others. This worked for me. 
Do not forget to clean and refresh the project.

**Comment by almasmaris** [comment]
unfortunately, there is no v4 jar in my project. i don't know why this happen? any clue? maybe, my project's setting? or just copy the latest in "libs" folder of my project manually?

**Comment by almasmaris** [comment]
i'm copied v4 jar from actionbarsherlock library and replace v4 jar on slidingmenu library. Also, i'm tried copy v4 jar on libs folder manually. I got errors:

BaseActivity.java:
"the method getSupportActionBar() is undefined for the type of baseactivity"
"the method onOptionsItemSelected(MenuItem) of type baseactivity must override or implement a supertype method"
"the method onCreateOptionMenu(Menu) of type baseactivity must override or implement a supertype method"
"the method getSupportMenuInflater() is undefined for the type of baseactivity"

ResponsiveUIActivity.java:
"the method getSupportActionBar() is undefined for the type of ResponsiveUIActivity"
"the method onOptionsItemSelected(MenuItem) of type ResponsiveUIActivity must override or implement a supertype method"

**Comment by almasmaris** [comment]
Finally i solve this issue! 
Like riyazMuhammed said, i i must replace v4 jar so ABS library and SlidingMenu library's have same v4 support jar. 

And also...

I need to change the class  "SlidingFragmentActivity.java" on SlidingMenu library's to extend SherlockFragmentActivity (change "FragmentActivity" to "SherlockFragmentActivity") and add ABS library to SlidingMenu library depedencies. 
I know this from youtube :dancer: 

Thank you.

**Comment by keertig** [comment]
Facing same issue

**Comment by Thuseeman25** [comment]
@almasmaris, I did not solve yet regarding you last comment, Can you please explain me to solve this same issue?

**Comment by arslanali222** [comment]
right click on your project and then go to Android tools and click on Android support libraray...
this method worked for me....

**Comment by tlightsky** [comment]
almasmaris's post helps a lot,after change SlidingFragmentActivity extends SherlockFragmentActivity and import SherlockFragmentActivity , the example works finally
