### ISSUE TITLE
Basic question about setViewAbove

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#50]
Thanks for making slidemenu library. ^^

User Schenario
 : User click behine view lise --> Above View is changed.

If I see detail about setViewAbove() function.
This method accept only 2 type. int res and View v

However I want to use Activity.
If I use Intent I can make it. But sliding menu is not exist.
Intent intent = new Intent();

Is there any way to change Above View by using Activity?

Thanks for reading.

**Comment by jfeinstein10** [comment]
You can't put an Activity into the above view. That doesn't really make sense when you think about what an Activity is. What you CAN do however is change the View that is held in the above view OR manually put a fragment in the above view and switch it.

**Comment by ghost** [comment]
If I see ExampleActivity2 that use Fragment.
However AboveView only has action bar, Behind View does not has it.
If I see ExampleActivity, above and behind view has common action bar.

Is that possible at ExampleActivity2 use common action bar like ExampleActivity?

**Comment by jfeinstein10** [comment]
No, in order to get the ActionBar to slide, you need to have your activity extend Sliding*Activity. You cannot get this behavior through an xml defined layout using a SlidingMenu.
