### ISSUE TITLE
I cant download the zip file. Please help !!!! 

### ISSUE THREAD

**Issue by jackmedrano** [jfeinstein10/SlidingMenu#503]
When I try download the zip file, the file begin to download, but the download stops and I get a message in crome: network error. Anybody has this same problem ?. Please help

**Comment by jfeinstein10** [comment]
GitHub may be down. Please just use git, you should never rely on a zip for an open source project

**Comment by jackmedrano** [comment]
I'm sorry. I am a  beginner programmer java. I don't know what is git. Now I am going to investigate. At moment of use a library o proyect, I always download a jar o zip file, I never have had a problem. I imagine that git is a software.

thank for your help. I need download the project immediatly

**Comment by dodola** [comment]
@jackmedrano 
hello ,you can install this software ,[http://windows.github.com/](http://windows.github.com/)
and then click the "Clone in Desktop" button

**Comment by jackmedrano** [comment]
dodola thank very much. I have been trying download this project all day and I didn't find way do it until I read your email. Thank because I could download it very very fast. Thank for help me and for give me a solution as good. 

Thank you !!!! I have just downloaded the proyect !!!
