### ISSUE TITLE
I can import the project to eclipse. But then I get this message:Project build error: Non-resolvable parent POM: Could not find artifact   com.jeremyfeinstein.slidingmenu:parent:pom:1.3-SNAPSHOT and 'parent.relativePath' points at   wrong local POM

### ISSUE THREAD

**Issue by jackmedrano** [jfeinstein10/SlidingMenu#510]
![image](https://f.cloud.github.com/assets/5121936/912358/69d7b540-fdff-11e2-93d9-e2c8ba8b5ea2.png)
I have just installed maven and the plugin android to maven in eclipse. and I get this message

**Comment by VenomVendor** [comment]
delete **pom.xml**
