### ISSUE TITLE
Adding dynamic content whenever user opens  the menu.

### ISSUE THREAD

**Issue by shadabunique** [jfeinstein10/SlidingMenu#511]
Hi,
I have implemented the SlidingMenu successfully. 
What my requirement is that I have a menu in the form of listview .
Now few of the list items have one more component (e.g. status) which needs to be updated dynamically everytime the user opens the menu. 
I'm not able to achieve this.
Please help me .

**Comment by leonardoxh** [comment]
If you perform a findViewById on the view thats contain the SlidingMenu the view will be founded doesn't matter if is visible or not, (since the view is never removed just stay invisible) and always you can work with the onOpenListener, onOpenedListener and the onCloseListener.

**Comment by shadabunique** [comment]
Exactly how I achieved before reading your answer.
Anyways, Thank you very much.

**Comment by shadabunique** [comment]
Hi,
Can you please help me with the below question :+1: 

https://github.com/jfeinstein10/SlidingMenu/issues/512

everything is working fine except this issue .
Please help.
