### ISSUE TITLE
Can I add addToBackStack to SlidingMenu ?

### ISSUE THREAD

**Issue by ozdemir** [jfeinstein10/SlidingMenu#518]
I'm adding sliding menu like this, and I want to add backstack(null) but I can't add this. How can I add, addtobackstack(null) JeremySliding Menu? 

menu = new SlidingMenu(this);
menu.setMode(SlidingMenu.LEFT);
menu.setTouchModeAbove(SlidingMenu.TOUCHMODE_MARGIN);
menu.setFadeDegree(0.35f);
menu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);
menu.setMenu(R.layout.left_side);
menu.setBehindOffset(250);

Best Regards,

**Comment by sockeqwe** [comment]
People please stop using githubs issues section as help forum. This section is reserved, like the name suggest to report issues and not to ask for trivial help!

However, what you are looking for is something like this in your activity:

``` java
public void onBackPressed(){

    if (slidingMenu.isMenuShowing())
        slidingMenu.toggle();
   else  
        super.onBackPressed();
}

```

Please use for future questions stackoverflow

**Comment by ozdemir** [comment]
I'm sorry wrote there.. I will use future questions stackoverflow.. Thank you so much for your answer..
