### ISSUE TITLE
Transparent Background with Sherlock

### ISSUE THREAD

**Issue by staber** [jfeinstein10/SlidingMenu#53]
If you change the list size down to not filling the view, the background is transparent using ABS.  For example, in SampleListFragment

``` javascript
public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        SampleAdapter adapter = new SampleAdapter(getActivity());
        for (int i = 0; i < 4; i++) {
            adapter.add(new SampleItem(new Fragment(), "Sample List", android.R.drawable.btn_star));
        }
        setListAdapter(adapter);
    }
```

Starting clean with @iPaulPro ABS example it's also transparent.  
I've set a solid background in both the above and behind layout and it still appears transparent after the list. 

Anyone else find a way to fix this.
BTW, this is only appearing on my 2.3.3 test device and not on 4.1.1  with the same code.

**Comment by staber** [comment]
![ABS](http://s13.postimage.org/abk9f75p3/ABStransparent.jpg)

**Comment by Tombarr** [comment]
@hiv0lt As soon as I saw that screenshot I knew it! That's Moto BLUR (or whatever they want to call their UI now). BLUR fills all transparent regions with that horrible etched gray-ish background thing.

This post on Motorola's [Developer Blog](http://community.developer.motorola.com/t5/MOTODEV-Blog/Why-Does-My-ListView-Look-Different/ba-p/17462) should clear things up! It's a known issue and one that's not to difficult too fix, just annoying that it even exists :-)

**Comment by staber** [comment]
AWESOME!!  Putting android:overScrollFooter="@null" in my ListView fixed it. Thanks.

I put my DX back to default/BLUR to test my ABS code.

Just another reason to hate BLUR.

**Comment by Tombarr** [comment]
Although the issue with MOTO BLUR is solved, I'd like to point out that with `windowBackground` set to `@null` on my Galaxy Nexus there is ghosting. Hardware acceleration causes a major issue apparently. I'll try to reproduce this with the sample app later because I cannot screenshot the app I am using SlidingMenu with.
