### ISSUE TITLE
ResponsiveUIActivity not found

### ISSUE THREAD

**Issue by larsbard** [jfeinstein10/SlidingMenu#547]
Hi.

The code refers to ResponsiveUIActivity in several functions, but it is not found in the project.

**Comment by mjkohoh** [comment]
It‘s in the package 'com.jeremyfeinstein.slidingmenu.example.fragments'

**Comment by saravanan-vdg** [comment]
ColorFragment error in sliding menu example in android

**Comment by mjkohoh** [comment]
error ,what error? @saravanan-vdg

**Comment by larsbard** [comment]
I figured it out. It was my fault, code was running properly.
