### ISSUE TITLE
Download option for jar

### ISSUE THREAD

**Issue by jjpe** [jfeinstein10/SlidingMenu#548]
I've looked but not found a download option for your lib (no releases, no link in your .md file). Since it's redundant for every user to build his/her own copy, could you please provide a jar for easy access?

If you do not want to do this (e.g. for technical reasons) then could you please update your .md to actually provide some kind of proper guide on how to set things up? the current version is not clear at all (for example it doesn't tell me how to start, how to set things up, which is the whole point of a .md file. I stopped reading after that).

**Comment by dasfuu** [comment]
You have to import the library folder as a library project into your Eclipse workspace. 
http://developer.android.com/tools/projects/index.html#LibraryProjects gives you more information about library  projects.

**Comment by jjpe** [comment]
Aha I see, thank you for the answer. May I suggest you also put this in the .md, as a "step 0" in getting started?
In retrospect it's obvious but beforehand I had no idea this was an option.
I'll also close the issue.
