### ISSUE TITLE
ft.replace method question.

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#55]
For example
I have 3 list at sliding menu.
1. Show list (first button)
2. Show second list (second button)
3. Show third list

If I chick sliding menu above view will be changed.
When I chick first button, ft.replace(R.id.test_main, new mShowListFragments); is called.
When I chick second button, ft.replace(R.id.test_main, new mShowSecondListFragments); is called.

This works find. But every time when I click sliding menu button I hava to make new fragments.

So make List<Fragment> mFragments = new ArrayList<Fragment>();
and use like this ft.replace(R.id.test_main, mFragments.get(0));

However if I use List<Fragment> sometimes view is not displaied correctly.

If you want to change fragment at above view, how did you make it?

**Comment by jfeinstein10** [comment]
You must commit() all FragmentTransactions
