### ISSUE TITLE
After SlideMenu Open/Close Dynamic UI Updates dont work

### ISSUE THREAD

**Issue by randaomiam** [jfeinstein10/SlidingMenu#556]
Hey,
I've implemented to SlideMenu on a bunch of apps but for some reason never come across an issue like this.

The issue isnt limited to this use case but I have a bunch of ImageViews which have a setOnTouchListener implemented on them to change their pressed state drawable image using setImageDrawable. Works like a charm until i slide out the menu then slide it back in and then the pressed state drawable images dont change. I thought this was because the touches werent being picked up but i displayed some Toast when you also click on the ImageViews and that still worked so it's just the UI that wasnt able to be changed.

Anyone else see this? Or could give me some suggestions?

I've attached it normally and then extended SlidingFragmentActivity as the other alternative and still have the same issue.

Cheers
Adrian

**Comment by nfirex** [comment]
Try this in your Manifest:
<application
        android:hardwareAccelerated=true
...

I watch this problem on Android 3.x.

**Comment by randaomiam** [comment]
Yep that worked....thanks mate!!
