### ISSUE TITLE
Include ListViewMenu to show on behind content

### ISSUE THREAD

**Issue by elijahsh** [jfeinstein10/SlidingMenu#56]
I've created simple [List view menu](https://github.com/elijahsh/ListViewMenu) (implementation of android.view.Menu) you can include it in lib. It support standard menus xml and uses MenuInflater.

**Comment by czaku** [comment]
Any tips how to make it work, as I am following the steps and cannot make it working properly, just the dark theme displayed, no list menu items...

**Comment by elijahsh** [comment]
Can you show code? And what android version?

**Comment by czaku** [comment]
I tested on 2.3.5, 4.0.3 and 4.1.1
Basically I create XML activity_main_menu.xml and add some items, then I create the layout with the same name and paste your code:

``` javascript
<com.elijahsh.view.ListViewMenu xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/main_menu"
    style="@style/ListViewMenu.Dark"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent" />
```

The id is changed from your code to main_menu

Then I create MainMenuActivity for setBehindContentView where I paste your code:

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    ListViewMenu navigationMenu = (ListViewMenu) findViewById(R.id.main_menu);
    MenuInflater inflater = getMenuInflater();
    inflater.inflate(R.menu.activity_main_menu, navigationMenu);
    navigationMenu.setMenuClickListener(new ListViewMenu.OnMenuClickListener() {
        public void onClick(MenuItem menuItem) {
            // TODO Auto-generated method stub

        }
    });
}
```

That's it.
I am quite newbie to Android so I am sure I do sth really wrong :/

**Comment by elijahsh** [comment]
Everything look right in your code. I've created example in https://github.com/elijahsh/ListViewMenu. Only thing you must change is text color. You need fix it to what you like in styles.xml: ListViewMenu.TextAppearance.Normal and ListViewMenu.TextAppearance.Separator

**Comment by czaku** [comment]
Still the same, I packed the ListView menu into LinearLayout (I hadn't before) and the view is empty :/ I want to have the menu as behind view using SlidingMenu... Maybe I should initialize it somehow in the above view?

**Comment by czaku** [comment]
Or worked it out :) I wasnt starting the activity :/ the thing is now I have to sort out how to start Behind Activity for the SlidingMenu, because now it shows on top as the AboveContent

**Comment by wmonasterios** [comment]
I have the same problem, i don't know how to start both activities at the same time, i want to start the behindActivity has a MenuActivity and the AboveContent has the HomeActivity, How can I do this? because I start de HomeActivity but I don't know how to Start the MenuActivity, It shows an empty view.  Sorry about my english...

**Comment by jfeinstein10** [comment]
You can't start 2 Activities at the same time. A SlidingMenu is a View that you use inside a single Activity.

**Comment by wmonasterios** [comment]
Sorry but Im new developing Android Apps, I have a Menu that is a View inside an Activity. How can I Start a New AboveActivity when clicking on a row on Menu's List?

**Comment by hwrdprkns** [comment]
Register an OnItemClicked listener in the SlidingMenu ListView that, when clicked, starts an intent for a new activity.

**Comment by jfeinstein10** [comment]
I'm going to close this issue for now. How the user implements their menu is up to them; I don't want to mandate that they do it a certain way. Maybe in the future I'll provide it if they want it.
