### ISSUE TITLE
toggle secondary menu

### ISSUE THREAD

**Issue by balasaheb143** [jfeinstein10/SlidingMenu#568]
toggle secondary menu on click button like left side menu

**Comment by MarcusSky** [comment]
<code>showSecondaryMenu(true)</code> or <code>showSecondaryMenu()</code> should do the job.

**Comment by balasaheb143** [comment]
showSecondaryMenu() work well . how i hide secondary menu on click button

**Comment by MarcusSky** [comment]
To hide the secondary menu you can use <code>getSlidingMenu().getSecondaryMenu().toggle()</code>, this will allow you to open the menu (when it is closed), and to close the menu (when it is opened). To check if the menu is opened you can use <code>getSlidingMenu().getSecondaryMenu().isShown()</code>
