### ISSUE TITLE
Custom opening animations

### ISSUE THREAD

**Issue by Tombarr** [jfeinstein10/SlidingMenu#57]
I cannot seem to find a way to add the "Enhancement" label, but that is all this is. 

The [Deal In](http://dribbble.com/shots/543645-UX-iOS-UI-iPhone-idea-with-video-process) app for iOS has an amazing folding animation. It would be amazing to see SlidingMenu support custom animations the same way Android launchers do. Folding, transparency, rotating cubes, etc. I wouldn't expect most animations to come out-of-the-box but perhaps allow for extensions or something, like dynamically setting the animation at runtime.

Just a though anyway, not sure what other people think. I'd love to help out any way I could with this.

**Comment by BartoszJarocki** [comment]
Also it will be great to have 'tip' feature like in prixing app (animation, which shows there is a menu when app is first opened).

**Comment by jfeinstein10** [comment]
Can you explain a little bit more about the tip? I just down aided the prixing app and couldn't find it. Also, any guidance in where to start with the custom animations would be much appreciated. I assume they're done in opengl for the launchers

**Comment by BartoszJarocki** [comment]
I've just checked again prixing app, and tip feature is gone :( but is described on prixing app author's page:
http://android.cyrilmottier.com/?p=717

**Comment by Tombarr** [comment]
Sorry about that, my description was definitely lacking. The good news is that on most Android launchers they are not done with OpenGL (see [ADWLauncher](https://github.com/boombuler/ADWLauncher2/)'s Tween/ LinearTween code). Unfortunately, I believe that the effect I described with Deal In would absolutely require OpenGL or something of that nature.

For the non-OpenGL animations it's a matter of Canvas transformations. You need callbacks to respond to and some interface, then for each scrolling value of x you apply some transformation. It could be a skew/ rotation, opacity change, color filter... I mean, the idea is to allow for just about anything. Most launcher animations like pinwheel won't be terribly useful, but bulldozer effect that shrinks the canvas as you scroll, or the card-stack effect might be nice options.

I'll see what else I can muster up, perhaps something of more value than my terrible descriptions. I do have a back-port of Android 3.2's [Camera](http://developer.android.com/reference/android/graphics/Camera.html) API that added `setLocation` and I'm sure I could tweak it to match Jelly Bean's, but that's really only useful for flip-style animations and requires including native libraries.

**Comment by iPaulPro** [comment]
@jfeinstein10 If you're going to implement animations, take a look at Jake Wharton's [NineOldAndroids](https://github.com/JakeWharton/NineOldAndroids). It's the new animation framework back-ported to work all the way to 1.0.

With the new framework you have fine control over animations. Check out the Demo project to see some of the new abilities (it's basically a copy of the official API demos, except using NineOldAndroids). Also have a read of [this article](http://android-developers.blogspot.com/2011/02/animation-in-honeycomb.html) to get a better idea of how it all works.

**Comment by jfeinstein10** [comment]
Thanks for the guidance guys :)

What I'm getting from this is that there are 2 main ways to expose this to the user :
1 - expose the actual Canvas through some interface (called CanvasTransformer for now and actually in the repo already). This seems more complicated but I can definitely see some devs wanting it.
2 - have CustomViewBehind do something like MyAnimationView in this example : http://source-android.frandroid.com/development/samples/ApiDemos/src/com/example/android/apis/animation/AnimationSeeking.java . This would appear to be easier to the casual dev because basically all they'd have to do is define some animation and then give it to me and I'd handle the rest.

Is my interpretation correct? Also, what kinds of things should be in each interface? I'm pretty new to Animations so any advice is good advice :)

**Comment by jfeinstein10** [comment]
Exposed the canvas. There's an Activity that shows how to do this in the sample app

**Comment by jfeinstein10** [comment]
Have you guys checked out the example app yet?

**Comment by antslava** [comment]
Did any one know how I can implement 'Deal In' menu with canvas from CanvasTransformer ?

**Comment by jfeinstein10** [comment]
Something like that would have to be done another way unless you can find a Matrix transformation that can pinch a view like that.
