### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by Gerry0927** [jfeinstein10/SlidingMenu#572]
When  i use PullToRefresh in this SlidingMenu and my ListView has a custom list_item，when I pull to refresh it has a crash with StackOverflowError  how can i fix this porblem?  It work well on 4.x but it crashes on 2.x

**Comment by MarcusSky** [comment]
Can you post the code that is crashing ?

**Comment by Gerry0927** [comment]
I have changed my Layout ,Previously In my Righ content view ,I have a ViewPager and I use FragmentAdapter with three Fragments ，perhaps there are too many  fragments so I replace the FragmentAdpter of fragments with PagerAdapter of views,it doesn't crash now,thanks all the same
