### ISSUE TITLE
Toggle menu in onCreate

### ISSUE THREAD

**Issue by akshaydashrath** [jfeinstein10/SlidingMenu#58]
Toggle menu in the on create does'nt seem to work

**Comment by staber** [comment]
I think you'll need to include some more info/code if you'd like help troubleshooting.

**Comment by jfeinstein10** [comment]
I second hiv0lt

**Comment by akshaydashrath** [comment]
Right my apologies, what I would like to do is activated the sliding menu on opening the activity. Currently I'm implementing the Sliding Menu by extending the SlidingFragmentActivity. This is what my activity looks like.

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(getActivityLayout());
    setBehindContentView(R.layout.activity_menu_sliding);
    getSupportActionBar().setDisplayHomeAsUpEnabled(true); 
    getSlidingMenu().setShadowWidthRes(R.dimen.shadow_width);
    getSlidingMenu().setShadowDrawable(R.drawable.sliding_menu_shadow);
    getSlidingMenu().setBehindScrollScale(0.25f);
    getSlidingMenu().setBehindOffsetRes(R.dimen.offset);
    setSlidingActionBarEnabled(true);

}

@Override
protected void onStart() {
    super.onStart();
    toggle();
}

@Override
public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
    case android.R.id.home:
        toggle();
        return true;
    }
    return super.onOptionsItemSelected(item);
}

public abstract int getActivityLayout();
```

**Comment by jfeinstein10** [comment]
What effect are you trying to get here? Do you want the user to see it open as soon as the main view becomes visible?

**Comment by akshaydashrath** [comment]
Yes, exactly, its the main area of navigation basically, and a user can navigate between primary activities through the menu, the primary activities extend the nav activity, a primary activity can only be accessed from the menu, and when one navigates to one of the primary activities since the state of the menu was open natural expectation is to have it open when the next screen loads, I could replace the "primary" activities with fragments, but these are complex layouts, consisting of several fragments.

**Comment by akshaydashrath** [comment]
I just noticed, the toggle works in the onStart if it is called a little while after the onCreate is called, for example screen turns off and you turn it back on, however not immediately after the onCreate is called.

**Comment by jfeinstein10** [comment]
Strange. What I've seen a lot of people do which looks really really nice is set an onClosedListener on the SlidingMenu which starts the next activity when the SlidingMenu closes and then they call close immediately after setting the listener. This way it looks really seamless from one Activity to another. If you want to get even fancier you can call overridePendingTransition within the onClosedListener so that the Activities will look more like Fragments replacing one another

**Comment by akshaydashrath** [comment]
Interesting solution, I suppose that would look like Google+ app, I'm already doing the overridePendingTransition at the moment. However I'm afraid I may not be clear, basically the sliding menu consists of a List, the list is the mode of navigation for the main areas/activities of the app. When you open the sliding menu when you first enter the app, the first item on the list is checked (I'm using a custom relative layout for the list item which implements checkable so the entire item is highlighted), when you click on another item, this item gets highlighted and I'd expect to see the activity load up in the above view with the below view still being visible. Then if you select the thrid item, the third activity loads up with the 3rd item in the slidingmenu being highlighted. If implementing this is difficult I'll implement your suggestion on closing the menu and once its closed open the new activity. There is also another scenario I was looking at, which isn't too important though, on first install I was looking at keeping the menu open, like what youtube does. Thanks for your time btw :).

**Comment by jfeinstein10** [comment]
No problem. Always here to help.
In terms of UX, I would say that this implementation is a little bit confusing. If a user clicks on an item in a navigational list, they have consciously chosen the page and they expect to be "brought" to it. In other words, they would want to see what they just selected, so the SlidingMenu should close and bring them to it.
There are two ways of doing this, either pre-loading the Activity and then closing the SlidingMenu (which it sounds like you're trying to do and it's not working) OR closing the SlidingMenu and loading the Activity (which is easy to do). It's your call on this one. Don't know how much help I can offer for the first option.

**Comment by akshaydashrath** [comment]
What I wanted to do is basically load the activity and keep the menu open, so it feels like a user is selecting options on a list and the list is fixed. But I see the logic behind your approach, at the moment its the quicker solution and I think I'll go with it. Will continue to explore the first option, will let you know if I get anywhere with it. Always nice to have options.

Closing the issue.

**Comment by akshaydashrath** [comment]
Just for anyone else interested in this feature, if you call toggle in the onResume it toggles the menu, this is because the setup of the bar is executed in the onPostCreate method of the activity.

**Comment by longvd89** [comment]
Hi everybody!

i have : mainactivity ---> LoginActivity  --successfull---->  Mainactivity and open Slidemenu

i want open slide menu in Onresume(), i have tried : 

@Override
    public void onResume() {
        // TODO Auto-generated method stub
        super.onResume();

```
        if (!getSlidingMenu().isMenuShowing()) {
             getSlidingMenu().showMenu();
        //   toggle();  

    }   
}
```

i have tried    getSlidingMenu().showMenu();       and  toggle();   but slidemenu don't open 

Should i do ?

**Comment by mjkohoh** [comment]
I think it will work.And i hava try it,it really work.so i think maybe you make some mistake in other places. @longvd89
