### ISSUE TITLE
Actionbar Sherlock above the menu

### ISSUE THREAD

**Issue by akshaydashrath** [jfeinstein10/SlidingMenu#59]
I can't seem to find a way to have the menu slide under actionbar, i.e. keep the action bar static and not moveable.

**Comment by staber** [comment]
code?

have you gotten the sample app to work?

**Comment by jfeinstein10** [comment]
There's a method called setSlidungActionBarEnabled that you have to call in onCreate

**Comment by akshaydashrath** [comment]
Oops didnt notic that, my mistake, Silly me :D
