### ISSUE TITLE
IllegalArgumentException gets thrown from SlidingMenu

### ISSUE THREAD

**Issue by danielsunyu** [jfeinstein10/SlidingMenu#598]
02-12 15:36:46.966: E/AndroidRuntime(21518): FATAL EXCEPTION: main
02-12 15:36:46.966: E/AndroidRuntime(21518): java.lang.IllegalArgumentException: pointerIndex out of range
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.MotionEvent.getX(MotionEvent.java:1974)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at com.slidingmenu.lib.CustomViewAbove.determineDrag(CustomViewAbove.java:785)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at com.slidingmenu.lib.CustomViewAbove.onTouchEvent(CustomViewAbove.java:701)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.View.dispatchTouchEvent(View.java:5549)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1951)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1712)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1912)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1371)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.app.Activity.dispatchTouchEvent(Activity.java:2364)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1860)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.View.dispatchPointerEvent(View.java:5729)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2952)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2469)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:845)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2478)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.os.Looper.loop(Looper.java:137)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at android.app.ActivityThread.main(ActivityThread.java:4424)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at java.lang.reflect.Method.invokeNative(Native Method)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at java.lang.reflect.Method.invoke(Method.java:511)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-12 15:36:46.966: E/AndroidRuntime(21518):    at dalvik.system.NativeStart.main(Native Method)

The exception is thrown from the determineDrag(MotionEvent ev) method of CustomViewAbove class.

**Comment by mjkohoh** [comment]
which version did you download.In the recent version,jfeinstein10 fixed the issue like those you meet.

**Comment by ghost** [comment]
hello, refer to this: 

https://github.com/jfeinstein10/SlidingMenu/issues/94, the last comment is the answer.
