### ISSUE TITLE
about click event

### ISSUE THREAD

**Issue by commonzhkx** [jfeinstein10/SlidingMenu#600]
hi ,  When  use the slidingmenu  library  , I can't  set any click event  in  menuFragment ,   can you  tell me  why?

**Comment by commonzhkx** [comment]
when  i  use  the following  method  ,slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);   

then  i  can't  set click  event

**Comment by commonzhkx** [comment]
when  i  use  the following  method  ,slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);   

then  i  can't  set click  event  ,please  help .

**Comment by commonzhkx** [comment]
when  i  use  the following  method  ,slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);   

then  i  can't  set click  event  ,please  help .

**Comment by commonzhkx** [comment]
when  i  use  the following  method  ,slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);   

then  i  can't  set click  event  ,please  help .

**Comment by commonzhkx** [comment]
when  i  use  the following  method  ,slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);   

then  i  can't  set click  event  ,please  help .

**Comment by commonzhkx** [comment]
when  i  use  the following  method  ,slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);   

then  i  can't  set click  event  ,please  help .

**Comment by commonzhkx** [comment]
when  i  use  the following  method  ,slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);   

then  i  can't  set click  event  ,please  help .

**Comment by mjkohoh** [comment]
please show more details
