### ISSUE TITLE
Trouble with Library

### ISSUE THREAD

**Issue by elijaelt** [jfeinstein10/SlidingMenu#608]
Hi,

I imported the "library" project into my Workspace.
In my project, i added refrence to "library" using Properties->Android->Add (Library).
I wrote the simple example from the front page, and i get "NoClassDefFoundError", what have i done wrong ?
do i need to write something in the Manifest ?

Please help ...

**Comment by act262** [comment]
Why NoClassDefFoundError? You should see this project's property  ,and is the red cross,than you can restart eclipse,that's how I do,and it work
