### ISSUE TITLE
Implementing prixing app bounce animation with this library

### ISSUE THREAD

**Issue by tom47b** [jfeinstein10/SlidingMenu#61]
Hi guys,

first of all, a big thanks to the developer. The library works beautifully and runs smooth even on older devices. Now I am trying to implement a prixing app like animation using the library but I have no clue on how to proceed. I am fairly new to android, so I am not familiar with all other libraries. So please nudge me in the right direction.
.thanks in advance

tom

Edit:

I am not really looking for fancy animations. basically , i want my app to start with the side menu pulled out a little.Then i can called the toggle() function to achieve nearly the same effect as the prixing app bounce animation.

**Comment by jfeinstein10** [comment]
I was told before that you can do all that stuff in the onResume method

**Comment by jfeinstein10** [comment]
You can use a bunch of delayed Handlers / onOpen/CloseListeners. Also, for a more in depth answer you can take a look at the Plume fork of SlidingMenu https://github.com/levelup/SlidingMenu/commit/3d2397a4bc31adbe8015315fd0074f67c361630b
