### ISSUE TITLE
View doesn't refresh properly

### ISSUE THREAD

**Issue by lancelotspa** [jfeinstein10/SlidingMenu#63]
Hi,

Thanks for a nice library, well done.

I'm trying to implement the library and so far it was working good but I've noticed a few issues when coming back to the main activity.

If I open a different activity and the come back to the main one with the sliding menu sometimes I don't see the full UI, some components of the UI are missing (black).

Any ideas? If I take an action on that screen somehow it refresh the UI properly.

Regards,

Roberto.

**Comment by iPaulPro** [comment]
Try to include some code snippets and screenshots, if possible. Be as specific about your implementation as you can.

**Comment by lancelotspa** [comment]
Hi,

I have a quite complex UI in the main activity of my application. This is what I've done to integrate the library:

My Main Activity - onCreate:

```
           // set the Behind View
    setBehindContentView(R.layout.menu_frame);

    // customize the SlidingMenu
    SlidingMenu sm = getSlidingMenu();
    sm.setShadowWidthRes(R.dimen.shadow_width);
    sm.setShadowDrawable(R.drawable.shadow_slider);
    sm.setBehindOffsetRes(R.dimen.actionbar_home_width);

             if(getSupportActionBar()!=null){
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setDisplayShowTitleEnabled(false);
    }

    setContentView(R.layout.act_main);
```

The layout_menu_frame is a simple layout with two buttons than do nothing at the moment.

Act_main is the layout of my activity which contains a list view and a few other layers (a bit complex UI).

Without making any more changes, I'm able to see the side navigation bar, everything works fine. The problem is that while using the application even without exiting the main class sometimes I miss part of the UI. For example I have different categories that loads different content on the listView, sometimes the listView just dissapear. 

I have an interstitial that appears a few times while changing cateogires and after the changed sometimes this interstitial is gone.

I have a search button on the navigation bar, if I press that button while any of this views is gone they all appear perfectly. Is like if it wasn't refreshing the whole UI.

Any ideas?

**Comment by lancelotspa** [comment]
I'm afraid the last commit didn't fix the issue I'm having.

The solution so far has been to add something like this on my Activity:

sm.setOnClosedListener(new OnClosedListener() {

```
        @Override
        public void onClosed() {
            getSlidingMenu().requestLayout();

        }
    });
```

Every time I come back from displaying the menu I need to call requestLayout otherwise part of the UI get's affected (some components are not longer on the screen even if the appear as visible)

R.

**Comment by jfeinstein10** [comment]
And this solution works well for you?

**Comment by lancelotspa** [comment]
Apologies!

Reviewing the changes you made on the last commit I found out that somehow I didn't get the latest code. 

I'm now using the latest code (for sure) and seems to be working fine, I need to do some more testing.

Regarding your question, that solution was working fine, what I don't know if is there any performance issue by doing that all the time.

To clarify what my error was:
- As soon as you open the menu the next time you display the main UI and you try to refresh it (like getting a new list) some components weren't getting displayed.

Thanks for your help!
