### ISSUE TITLE
Lag on open but not on close

### ISSUE THREAD

**Issue by alicanbatur** [jfeinstein10/SlidingMenu#636]
Hello. Thanks for the lib.

When i close the menu ,everything works like a charm. But when i wanted to open menu, it does some lag and menu opens with a little delay. When i use my left menu(fragment) with no ui elements ( i just put a textview) it is opened very well . But if i use  imageview, and a listview i have this annoying problem.

What do you advice me to do ?

Regards

**Comment by mjkohoh** [comment]
Did you open hardware accelerate?

---

发件人: alicanbatur
发送时间: 2014/4/15 23:16
收件人: jfeinstein10/SlidingMenu
主题: [SlidingMenu] Lag on open but not in close (#636)

Hello. Thanks for the lib.

When i close the menu ,everything works like a charm. But when i wanted to open menu, it does some lag and menu opens with a little delay. When i use my left menu(fragment) with no ui elements ( i just put a textview) it closes very good. But if i use  imageview, and a listview i have this annoying problem.

Whay do you advice me to do ?

Regards

---

Reply to this email directly or view it on GitHub:
https://github.com/jfeinstein10/SlidingMenu/issues/636

**Comment by alicanbatur** [comment]
@KOHOH1992 , i did it already.  I think this is about the menus ui. I need to do to something about ui but i am not sure. So i'm waiting some advice from you

**Comment by alicanbatur** [comment]
FinallY! I found out the problem!

Here is my explanation:

Guys, i have a fragment as a left menu. Inside it, i have a listview with icons and texts. And i have a header for listview which contains an avatar and some text informations. 
Here is the point ; NEVER USE wrap_content in your ListView's height ! Coz, if you use wrap_content in height, adapter's getView method calls much more times and it affects the performance. When i change listview height to fill_parent, everything fixed.

Thanks,
Best Regards :))

**Comment by shumin0809** [comment]
Good job @alicanbatur , you save me! Thanks man!
