### ISSUE TITLE
Dark and Light Theme

### ISSUE THREAD

**Issue by woutergoossens** [jfeinstein10/SlidingMenu#64]
Is it possible to have a (Sherlock) Light theme for the content and a (Sherlock) Dark theme for the slide menu (list)?

For example the Google+ application. The list in the slide menu there is dark (gray).

I tried to inflate the layout in the onCreateView method and use  the ContextThemeWrapper but I am getting a Light list.

Is there a solution? Thanks!

**Comment by jfeinstein10** [comment]
Does the light list have light text as well? The faulty ContextThemeWrapper doesn't have to do with this library, although the windowBackground is maintained from the original theme (in your case light). You may have to manually style the list :/

**Comment by iPaulPro** [comment]
You can set the style of the ListView to `@style/Sherlock.__Widget.Holo.ListView`.

**Comment by jfeinstein10** [comment]
^ do that!
