### ISSUE TITLE
Can't replace fragment on aboveView after opening behindView

### ISSUE THREAD

**Issue by dmarcato** [jfeinstein10/SlidingMenu#66]
I'm trying to replace a fragment in aboveView from behindView, but it seems that after you open the slider if you replace a fragment in aboveView it will not be shown.
I tried to have a look with PixelPerfect and it seems to be a measure problem since it show that the fragment is a small square in the upper left angle of the screen.

To reproduce the problem you can simply create a new Fragment in your example code (I've called mine MySampleListFragment) and change onActivityCreated in SampleListFragment like so:

``` java
public void onActivityCreated(Bundle savedInstanceState) {
    super.onActivityCreated(savedInstanceState);
    SampleAdapter adapter = new SampleAdapter(getActivity());
    for (int i = 0; i < 20; i++) {
        adapter.add(new SampleItem("Sample List", android.R.drawable.btn_star));
    }
    setListAdapter(adapter);
    getListView().setOnItemClickListener(new OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> arg0, View arg1, int arg2, long arg3) {
            getFragmentManager().beginTransaction().replace(R.id.content_frame, new MySampleListFragment()).commit();
        }
    });
}
```

You will notice that when you click on a list item the aboveView will result empty also if the fragment is correctly created and every method of his lifecycle are called.

Is there any fix for that?

**Comment by jfeinstein10** [comment]
If you make this call, it will resize correctly immediately:
((SlidingFragmentActivity) getActivity()).getSlidingMenu().requestLayout();

**Comment by lancelotspa** [comment]
If I call requestLayout() I stop having problems with some of the views of my UI not showing. Any idea why is that? I'm not using fragments at this point but I'm experiencing some issues with view disappearing randomly. 

Is there any way of avoiding this issue or the best solution is just to call requestLayout()?

Thanks,

R.

**Comment by jfeinstein10** [comment]
Pull the latest code, I think I may have fixed the error. It now works for me without calling requestLayout

**Comment by dmarcato** [comment]
Yeah, your last commit fixed the problem, it works perfect for me now.
Thank you! :)

**Comment by jfeinstein10** [comment]
No problem! Glad I could help :D
