### ISSUE TITLE
About SlidingMenu library   setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN)

### ISSUE THREAD

**Issue by gtchjc** [jfeinstein10/SlidingMenu#666]
I am Bob,I am using Jfeinstein10 SlidingMenu Library by mSlidingMenu.setTouchModeBehind (SlidingMenu.TOUCHMODE_FULLSCREEN); After setting the parameters and found the left side of the open view of the click event is not availableAfter that I made ​​some reference “https://github.com/jfeinstein10/SlidingMenu/issues/446” the modifications still exist the following problems:
       found that the left can slide off, but can not slide off the right side.
Please help me.
Thank you very much!

**Comment by gtchjc** [comment]
please help.

**Comment by gtchjc** [comment]
There is no one way, please help

**Comment by gtchjc** [comment]
This issue has been resolved, then this I thank rekire, because before I did not view it leads to the right side of the slide can not add the View view after the OK 
Specific solutions, please refer to # 466 
Thank you very much

**Comment by DawnYu9** [comment]
I also have this problem
can you help me ?
very thanks
sorry about my poor English
