### ISSUE TITLE
Sliding animation janky in current state

### ISSUE THREAD

**Issue by mattkranzler5** [jfeinstein10/SlidingMenu#67]
We are using this in the latest Zappos app in our search/browse UI. I just tried out the current version in the repo and while the fading is nice, and it fixed a couple of bugs I saw previously, it is now very janky when sliding the drawer open/closed compared to the one in the current version of the app (before the fading was fixed). Anything that can be done to smooth this animation again? It was working very smoothly previously.

**Comment by jfeinstein10** [comment]
Hmmm the only thing I can think of is to go into CustomViewAbove's scrollTo(...) method and to comment out requestLayout() and invalidate(). These were added to make the animations work, but if you don't need them it should work without those calls. I'll look into fixing this or adding an option to leave the calls out.

Also, I haven't looked at all, but have you guys included the SlidingMenu license in your app? (as per the terms of usage) Zappos is a terrific service that reaches a large audience so any mention of the library would be terrific for getting the word out there. I also use the app myself and love it; great job with the design and performance!

**Comment by mattkranzler5** [comment]
We are currently working on a screen that lists the open source licenses we are using. We will definitely add your license and a link for you. Where would you like us to link to? This project? Thanks for your feedback about the app too!

**Comment by jfeinstein10** [comment]
Yeah, currently this is the "homepage" for the project, but I'll be working on a real website soon.
No, problem. It's wonderful to see a big company following the Android design guidelines. There are way too many who don't :\

Did commenting out those lines help?

**Comment by jfeinstein10** [comment]
In master right now, requestLayout has been removed and invalidate is only called when there is a drawable that needs updating. This should fix the issues you're seeing. Let me know when you try it out!

**Comment by mattkranzler5** [comment]
The fix fixed it for us. Back to silky smooth! Thank you!

**Comment by jfeinstein10** [comment]
No problem :)
Keep me posted if you need/find anything else!
