### ISSUE TITLE
OnSlideListener

### ISSUE THREAD

**Issue by Bystysz** [jfeinstein10/SlidingMenu#678]
Is there any easy way to get a current slide offset value? Something like we have in Google DrawerLayout.SimpleDrawerListener.onDrawerSlide (View drawerView, float slideOffset)?

**Comment by Bystysz** [comment]
I've solved my problem. In CustomViewAbove.java file there is a function getPercentOpen(). You can use it for making listener

**Comment by ghost** [comment]
I'm troubled in this  too, in method CustomViewAbove.scrollTo()  you could add some codes to listen scrolling , and the getPercentOpen() method should help

**Comment by litao0621** [comment]
You can use this method  

``` java
setBehindCanvasTransformer(new CanvasTransformer() {

            @Override
            public void transformCanvas(Canvas canvas, float percentOpen) {
                // Here is the percent of open you need
            }
});
```
