### ISSUE TITLE
SlidingMenu with ActionBarSherlock

### ISSUE THREAD

**Issue by czaku** [jfeinstein10/SlidingMenu#69]
Any tutorial, brief description how to setup both to work together? Cannot manage to achieve this...

**Comment by staber** [comment]
@iPaulPro made a working fork for this a while back. It's not current but it's a good place to start and to see what's changed.

https://github.com/iPaulPro/SlidingMenu

**Comment by jfeinstein10** [comment]
Also there's a quick explanation in the readme file. Or you can look at the many forks that have done this.
