### ISSUE TITLE
not showing actionbar in android2.2

### ISSUE THREAD

**Issue by farzaneh-kh** [jfeinstein10/SlidingMenu#697]
hi im used this library but not showing actionbar into android 2.2

**Comment by theBlbDan** [comment]
Did you use it in conjunction with ABS? http://actionbarsherlock.com/
Read the small section from https://github.com/jfeinstein10/SlidingMenu -- 'Setup with ActionBarSherlock'

**Comment by farzaneh-kh** [comment]
yes im Add ActionBarSherlock as a dependency to SlidingMenu @theBlbDan
