### ISSUE TITLE
BehindView Content Dimensions Wrong on Tablet

### ISSUE THREAD

**Issue by hwrdprkns** [jfeinstein10/SlidingMenu#70]
On tablet the behind content view does not take up the whole screen. I'm not sure if this is a problem with figuring out the status bar height. For reference I was using a Motrola XOOM tablet and am on the lastest master commit. 

![Bad Layout](https://dl.dropbox.com/u/4676303/badLayout.png)

**Comment by jfeinstein10** [comment]
Fixed in Pull Request #72
