### ISSUE TITLE
SlidingMenu don't show items in ListFragment.

### ISSUE THREAD

**Issue by minamic** [jfeinstein10/SlidingMenu#717]
I try to use slidingmenu as a drawer navigation, with a fragment.
I put a textview and a listview in the drawer's layout, and use arrayadapter to show some items.
Everything is right except items in listview not showing, but listview is there.
And if i do replace the fragment in main_activity layout, items show up now.

**Comment by theBlbDan** [comment]
Can you paste the code for the menu fragment.

**Comment by minamic** [comment]
//------------------NavigationFragment.java-----------------------
public class NavigationFragment extends ListFragment {

```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState){
    return inflater.inflate(R.layout.fragment_nav, null);
}

@Override
public void onActivityCreated(Bundle savedInstanceState){
    super.onActivityCreated(savedInstanceState);
    ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(getActivity(), android.R.layout.simple_list_item_1, new String[]{"item1","item2","item3"});
    setListAdapter(arrayAdapter);
    Log.i("list", "adapter size" + getListAdapter().getCount());
}
```

}
//------------fragment_nav.xml-----------------
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fragment_nav_container"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >
    <TextView
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:gravity="center"
        android:text="Menus"/>
    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Button"/>
    <ListView
        android:id="@android:id/list"
        android:background="@color/OrangeRed"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</LinearLayout>

//--------------------------------------------------------------
Thanks for reply.
This is a very simple listfragment, so i wonder why it doesn't work. I also try to use custom list item and get the same result.
