### ISSUE TITLE
Whyextending AppCompatActivity  instead of FragmentActivity ,the  view goes down ?

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#752]
In the project SlidingFragmentActivity extends FragmentActivity , while I need to extend 
AppCompatActivity ,which  causes problems on several devices(nexus 6) the view goes down as much as the navigation bat height

**Comment by theBlbDan** [comment]
Screenshot please.  Are you referring to the softnav keys at the bottom or the actionbar at the top?

**Comment by ghost** [comment]
![1](https://cloud.githubusercontent.com/assets/9461300/15600929/1ab448de-23fe-11e6-9a62-730d15f436de.png)
![screenshot_20160527-111335](https://cloud.githubusercontent.com/assets/9461300/15600932/1dc6c4ca-23fe-11e6-8d9d-bd8393d22e39.png)

I have the first reault ,while should be as in 2_n png.

**Comment by ghost** [comment]
@theBlbDan any news?

**Comment by theBlbDan** [comment]
Chk out this issue https://github.com/jfeinstein10/SlidingMenu/issues/680

It sounds like what you're describing.

**Comment by theBlbDan** [comment]
Did this help solve your problem?  If so, it would be courteous toe close the issue.

**Comment by ghost** [comment]
Thanks .

**Comment by Yokamoz** [comment]
what happened
