### ISSUE TITLE
Load intent behide

### ISSUE THREAD

**Issue by Blucreation** [jfeinstein10/SlidingMenu#78]
Is it possible to load an intent behind. at the moment if i call an intent it will come in front and you lose the slideout menu.

Situation:

i have a webview and the guts of my app is a mobile website. i have a preference activity and an xml feed activity which are in native code.

How do i replace the webview with the preference/xml activities as it just load them over the top?

**Comment by hwrdprkns** [comment]
You should probably be using a fragment for this. This way you won't really be changing anything except the fragment the web view lives in -- and the SlidingMenu should remain untouched.

**Comment by jfeinstein10** [comment]
^ Seconded!

**Comment by Blucreation** [comment]
Will look into that cheers.

Another quick one how do i show.hide menu? is there a show() hide() classes? i want it to hide once a listivew item has been clicked and to have it open when app first loads

**Comment by bondjpf** [comment]
You can use toggle()

**Comment by Blucreation** [comment]
getSlidingMenu().toggle(); give an error: undefined for the type SlideMenu

**Comment by jfeinstein10** [comment]
That's because its a method of the activity, not the slidingmenu

**Comment by Blucreation** [comment]
ook... so how do i call it then as just calling toggle() does nothing in onCreate

**Comment by hwrdprkns** [comment]
You can't call it in `onCreate`. You have to do it sometime later (onResume maybe?). OnPostCreate is necessary for everything to be registered.
