### ISSUE TITLE
How to change front fragment from back fragment menu item click?

### ISSUE THREAD

**Issue by bob9** [jfeinstein10/SlidingMenu#79]
I am trying to work out how to change the front fragment from the back menu fragment. I'd like to have the user select an option from the back menu and based on that selection change the front fragment. If anyone can provide any sample code I'd appreciate it. I have been working with the sample code in com.slidingmenu.example.

**Comment by bob9** [comment]
Ok i worked it out myself, really come down to my lack of understanding of fragments. After a little reading i added the following.

I added this to SampleListFragment.java

@Override
    public void onListItemClick(ListView l, View v, int position, long id) {
        SlidingTitleBar parent = (SlidingTitleBar) getActivity();
        parent.getSupportFragmentManager()
        .beginTransaction()
        .replace(R.id.content_frame, new NewFragment())   //NewFragment is what I wanted to replace on the front menu
        .commit();
        parent.toggle();

```
}
```

**Comment by jfeinstein10** [comment]
Yup, just regular fragment management!

**Comment by bob9** [comment]
Thanks. Maybe it will help someone else.

The library is great by the way..

Cheers

bob9
