### ISSUE TITLE
SlidingMenu from BOTH left AND right side

### ISSUE THREAD

**Issue by ajf214** [jfeinstein10/SlidingMenu#8]
Add the ability to add a third view which will display when slid out from the right side.  Literally the same functionality that currently exists, but mirrored on the opposite side of the screen

**Comment by samuelngs** [comment]
That's also what I want! :)

**Comment by ajf214** [comment]
Hey Jeremy,

Any updates on when this might be a possibility?  Obviously, you're flying through these issues so you're keeping yourself busy! 

Thanks again.

**Comment by jfeinstein10** [comment]
I don't know when I'll have the time this week to get to it. I definitely want to address bugs before I get to this feature. Sorry to make you wait. You can try to implement it yourself if you really need it now.

**Comment by ajf214** [comment]
I'll give it a shot tonight and see what I can put together.  If you do have some time next week that would be awesome.  I am presenting the app I'm working on on July 30th

**Comment by chrisjenx** [comment]
This would be cool, but by no means high priority :)

**Comment by jfeinstein10** [comment]
Just to keep you guys posted, there's a near fully functional version of this is the slidingright branch. Pretty exciting stuff :)
Sorry it took so long!

**Comment by jfeinstein10** [comment]
In\*

**Comment by DazzyG** [comment]
Looking forward to this jfeinstein10!

**Comment by amannepid** [comment]
Looking forward for this feature ... :)

**Comment by musaulker** [comment]
I'm waiting also :)

On Tue, Sep 18, 2012 at 8:25 AM, Dipendra Sunar notifications@github.comwrote:

> Looking forward for this feature ... :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jfeinstein10/SlidingMenu/issues/8#issuecomment-8641393.

## 

M.Musa Ülker

**Comment by ajf214** [comment]
Great job Jeremy.  I'm gonna pull this later today and run through it.  Although, I think this UI paradigm might be a little too complex for my target audience right now (building an app for autistic adults).

**Comment by czaku** [comment]
any news when is this feature being released? :)

**Comment by jfeinstein10** [comment]
Pretty much done. Just needs more testing. You can check out the progress in the slidingright branch

**Comment by jfeinstein10** [comment]
If anybody wants to check it out and play with it, your feedback would be greatly appreciated :)

**Comment by a85** [comment]
Wow I was just looking how to do this. Will test this out.

**Comment by scruffyfox** [comment]
Works pretty well, but the threshold for the right menu seems a lot less than the left menu, alot trickier to get the damn thing open

**Comment by jfeinstein10** [comment]
Haha still a work in progress, don't worry :)

**Comment by scruffyfox** [comment]
Ofcourse :) Just though I would mention the issue. I would try and fix it
myself, but I have an app deadline to finish :(

**Comment by edamo** [comment]
Working fine for me :)

**Comment by czaku** [comment]
Hi, how is the status of the "right" branch? Is it anyway going to be merged with the master branch any soon?

**Comment by chrisjenx** [comment]
I think just testing @czaku give it a go, if you see any issues report them :)

**Comment by jfeinstein10** [comment]
Been done for a while haha

**Comment by satyan** [comment]
is there an example of using both left and right side menu at the same time..

**Comment by chrisjenx** [comment]
Yeah look at the demo app on the  play store

**Comment by satyan** [comment]
thanks @chrisjenx .. do you have some code examples.. i see only one behindContentView method.. what if I wanted to add two behind content views, one for left and other for right.

**Comment by chrisjenx** [comment]
setSecondMenu, also look at the samples under sample. The Options one shows you how to change between them etc.

**Comment by ViliusKraujutis** [comment]
Next request would be to allow to swipe menu from top or bottom. :)

**Comment by chrisjenx** [comment]
Look at the BIZZBY fork or the all branch
