### ISSUE TITLE
Software keyboard bug

### ISSUE THREAD

**Issue by DazzyG** [jfeinstein10/SlidingMenu#81]
When using SlidingMenu with any EditText and the Software keyboard in it's default state i.e 

```
<activity android:windowSoftInputMode="adjustResize">
```

The Software keyboard will deform the current view, if you dismiss the keyboard and focus on the edit text again the view will shrink again.

Adding the following to your activities seems to fix the issue.

```
<activity android:windowSoftInputMode="adjustPan">
```

You should be able to recreate the issue by changing the first Textview in https://github.com/jfeinstein10/SlidingMenu/blob/master/example/res/layout/properties.xml
to an EditText, That worked for me.

This happened on ICS and Gingerbread

edit: attached screenshot

http://i.imgur.com/MHcsn.png

**Comment by laurencerackham** [comment]
I've hit this too. It only seems to occur when the sliding action bar is enabled

**Comment by jfeinstein10** [comment]
This should actually be fixed in the latest commit. Make sure you have the most recent code and let me know

**Comment by DazzyG** [comment]
Can confirm it is fixed and working on ICS and Gingerbread
