### ISSUE TITLE
Lag when implementing the sliding menu library with fragments

### ISSUE THREAD

**Issue by tom47b** [jfeinstein10/SlidingMenu#83]
Hey, I have been trying to find the most effective way to implement a list based fly in menu using this library similar to fb and youtube apps . I keep the main view in fragments and when the user presses an item in the side list , I simply replace the fragment with a new fragment depending the selection. Then I call the toggle function to close the sliding menu. But this method produces some noticeable lag when the sliding menu closes and the fragments gets replaced with a new fragment. Is there a better way to replicate the behaviour of youtube and google+ . I am a bit of a newbie android developer so any help is appreciated. Thanks in advance.

Tom

**Comment by iPaulPro** [comment]
Try using the OnClosedListener to commit the Fragment transaction.

**Comment by jfeinstein10** [comment]
^ +1 thanks for catching this one so quickly Paul.
If you try to do both at the same time it'll put a lot of strain on the UI thread, which is where the lag comes from

**Comment by tom47b** [comment]
Thanks a lot for the prompt reply.

**Comment by tom47b** [comment]
The method recommended by iPaulPro works, but its since the change only happens after the side menu closes, the effect doesnt look seamless. Is there way commit the transaction first, then  after the transaction is done, the toggle function can be called so then change in view appears more natural. Thanks.

**Comment by tom47b** [comment]
I solved it using asynctask. Thanks for all the help guys

**Comment by brodarnikola** [comment]
how did you solve this using asynctask? 
Can you please describe? It will help a lot :))

**Comment by theBlbDan** [comment]
@brodarnikola 
The elegant solution is to use a loader or async task to load the list.
A good discussion:
http://www.androiddesignpatterns.com/2012/07/loaders-and-loadermanager-background.html

Another good example:
http://www.grokkingandroid.com/using-loaders-in-android/
