### ISSUE TITLE
OnClosed and OnOpened Listeners

### ISSUE THREAD

**Issue by betomaluje** [jfeinstein10/SlidingMenu#88]
First of all, I love this library! I was implementing another one but it didn't scroll so smooth like this one! I'm really greatful to all of you who made this library :).

I have a custom component that implements a runnable. It starts it and stops it great before using this library. Now it doesn't stops :(. I'd tryied to implement a OnClose and a OnOpen listener so when the behind view is shown, the component stops and when it doesn't it restarts.

My code is:

``` java
import com.slidingmenu.lib.SlidingMenu.OnClosedListener;
import com.slidingmenu.lib.SlidingMenu.OnOpenedListener;

public class MainActivity extends SlidingActivity implements OnClosedListener,
        OnOpenedListener{

... all the OnCreate and bla bla

    @Override
    public void onOpened() {
        // TODO Auto-generated method stub      
        component.stop();
        Log.v("MainActivity", "Menu Opened");
    }

    @Override
    public void onClosed() {
        // TODO Auto-generated method stub
        component.restart();
        Log.v("MainActivity", "Menu Closed");
    }

}
```

It doesn't even displays the Log :(

can you help me implement it?

thanks! :D

**Comment by jfeinstein10** [comment]
Thanks a lot! :)
Do you attach the MainActivity as a listener to the SlidingMenu in your onCreate method?

**Comment by betomaluje** [comment]
I don't think so, this is my OnCreate:

``` java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        // TODO Auto-generated method stub
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);
        setBehindContentView(R.layout.menu);

        sm = getSlidingMenu();
        setupSlidingMenu();
    }

    private void setupSlidingMenu() {
        sm.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
        sm.setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);
        sm.setBehindOffset(20);
        sm.setBehindWidth(350);
        sm.setBehindScrollScale(0.5f);
        sm.setShadowDrawable(R.drawable.drop_shadow);
        sm.setShadowWidth(30);
    }
```

how can I do what you said?
PS: the method setupSlidingMenu() was created because, strangely using the xml attributes didn't worked for me :/

**Comment by jfeinstein10** [comment]
xml attributes won't work because you aren't actually inflating your own SlidingMenu
In order to attach the listeners you have to call `sm.setOnOpenedListener(this)` and `sm.setOnClosedListener(this)`
