### ISSUE TITLE
'Disable' the above part when slided

### ISSUE THREAD

**Issue by blackcarth** [jfeinstein10/SlidingMenu#9]
First of all : nice work !

My request :
With a behindOffset > 0, when the behind part is showed, the above part  is still visible on the right  : nice.
But the above part also receives the touch input events (list, button, ...) : 
Is it possible to "disable"  the above part  and handle only the events to close the above part (drag-to-close, home button, ...) ?

**Comment by ajf214** [comment]
It has something to do with setAbove/setBehindTouchMode.  SlidingMenu has 2 static ints: TOUCHMODE_FULLSCREEN, TOUCHMODE_MARGIN which you would use as the parameter for these methods.

I tried playing with it just now, but was unable to get the margin to be "untouchable", I could only get the pullout menu to be "untouchable".  I would recommend playing around with these methods and you might have more success than me

**Comment by ajf214** [comment]
That being said I just looked at the source a little closer, particularly the method thisTouchAllowed() in the CustomViewAbove class, and it looks like when the menu is open, there is nothing that will disable the above view.

**Comment by jfeinstein10** [comment]
I'm looking into this now. It's a little more complicated because you have to sort things around when the ActionBar is populated in the above view. I'll let you know what I can do.

**Comment by jfeinstein10** [comment]
Made a little headway. Now just have to recognize touches on the home button.

**Comment by jfeinstein10** [comment]
Alright this should be semi-working in the master branch.
I decided to move away from the original request and to treat the menu like the Google+ app does when the menu is showing. You don't necessarily click on the home button, but a single click anywhere on the above view will close the menu.

**Comment by jfeinstein10** [comment]
Alright everything is implemented in the master branch.
I'm going to close the issue now, but please comment back and let me know what you think of the changes.
