### ISSUE TITLE
Unable to touch right side view for slidingright branch

### ISSUE THREAD

**Issue by jc4p** [jfeinstein10/SlidingMenu#90]
I'm unable to do any touch interactions with my behindRightView, I think it's because this line in thisTouchAllowed:

```
int x = (int) (ev.getX() + mScrollX);
```

will always return a number bigger than mContent.getRight(); because mScrollX is really big. Not quite sure though. I have a listview in my right view and am unable to interact with it at all, same with my buttons that have on touch state and so on. Let me know if you want a code sample to take a look at.

**Comment by jfeinstein10** [comment]
I believe this is fixed? Check it out again and let me know.

**Comment by jc4p** [comment]
Oh yeah, I forgot about this bug. It was fixed in https://github.com/jfeinstein10/SlidingMenu/commit/2d72045bd6f2a5cc8cf13115dbf326b5ac415058

Thanks!
