### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by zengar** [jfeinstein10/SlidingMenu#93]
I'm getting a inflate exception in the onCreate of the SlidingMenuActivityHelper (see below for exact error)

android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true

Could this be from something I missed setting or an issue with one of the layouts?

**Comment by jfeinstein10** [comment]
Probably an issue with one of the layouts. I've never seen this before :\
