### ISSUE TITLE
Increase default margin to 16dp?

### ISSUE THREAD

**Issue by cnordvik** [jfeinstein10/SlidingMenu#98]
Increasing the default margin to 16dp like this: 
http://mailman.videolan.org/pipermail/android/2012-September/001164.html

really improved the chance of opening the menu with a gesture. I was close to looking elsewhere for a sliding menu, but that trick turned the menu into the best menu there is :-)

**Comment by hwrdprkns** [comment]
Er, that constant should probably be `getScaledEdgeSlop ()`.

**Comment by jfeinstein10** [comment]
It has since been increased. Closing this issue :)
