### ISSUE TITLE
Fragments issue with toggle

### ISSUE THREAD

**Issue by hordurhauks** [jfeinstein10/SlidingMenu#99]
Hi!

I'm using the slidingright branch. My setup is like this: I have a MainActivity which extends SlidingFragmentActivity. For the left and right menus I have a few buttons inside a linearlayout. The MainActivity contains a linearlayout where I swap my fragments in and out. On pressing a button from the menu I would like a new fragment to appear in the MainActivity AND I want to toggle the menu(close it). Now, if I do toggle the menu calling toggle(SlidingMenu.Left) the correct fragment actually appears but the problem starts now: if I now press another menu button the new fragment does not appear in the MainActivity even though it's callback methods are called (onCreateView, onActivityCreated etc.). To solve this problem I had to do it like this:

``` android
// Get the sliding menu and set a listener to the event where it closes
getSlidingMenu().setOnClosedListener(closedListener);

// The clicklistener on the menubuttons in the left menu
private OnClickListener menuClickListener = new OnClickListener() {
    @Override
    public void onClick(View v) {
        if(v==btnHome) {
            mTogglingFragment = HomeFragment.newInstance();
        } else if (v==btnArtists) {
            mTogglingFragment = ArtistsFragment.newInstance();
        } 
        isTogglingMenu = true;
        toggle(SlidingMenu.LEFT);
    }
};

// The closed listener on the slidingmenu
private OnClosedListener closedListener = new OnClosedListener() {
    @Override
    public void onClosed() {
        if(isTogglingMenu && mTogglingFragment != null) {
            FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
            ft.replace(mFragmentContainer, mTogglingFragment);
            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN);
            ft.commit();            
            isTogglingMenu = false;
        }
    }
};
```

So what I've done here is that I set the new fragment as a private variable  and set a private boolean variable that states that I'm toggling from menu, then I call toggle and when the menu has closed I swap in the fragment I assigned earlier this works great except it is not very intuitive.

However, If I would've put the code that's in the onClosedListener into the menuClickListener I would get this weird state where it would work for the first fragment but on second click(and all clicks from there) the fragment would get instantiated but not drawn on screen.

A little bit extra about this issue: in my left menu I have an EditText widget. When I select something from the menu I want the edittext to settext(""). So, if I put the code mEditTextSearch.setText(""); into either the onClosedListener or the menuClickListener it enters the weird state again with the fragments.

Do you have any idea what's going on here?

**Comment by jfeinstein10** [comment]
Just a general tip. I've found that doing Fragment stuff with LinearLayouts can be problematic. Instead, I would use a FrameLayout.
I can't tell you exactly what's going wrong, but I can tell you that `slidingright` is definitely a work in progress (hence why it's a separate branch and not in the trunk) and that it does have some bugs.
For the regular SlidingMenu, I'll point you to how FragmentTransactions are performed in this class:
http://mtg-familiar.googlecode.com/svn/trunk/MTGFamiliar/src/com/gelakinetic/mtgfam/fragments/MenuFragment.java
This is an open source implementation that works really well and without the side effects that you've been seeing.
I would be interested to know if you're seeing these same errors in the trunk version of SlidingMenu

**Comment by hordurhauks** [comment]
Thanks for the tip, altough I've never had any problems with LinearLayouts and fragments ;). 

I switched to the master branch and that one works like a charm so it's definitely some problem with the slidingright branch.
